// Process-local rule variants for side-by-side comparison. Production defaults live in lib/.
// A shard applies exactly one variant before running; nothing here changes the shipped game.
import { ECONOMY_RULES, AGITATION_RULES, FARE_RULES, MOTOR_RULES, NIGHT_UNREST, V9_AGITATION } from '../../lib/balance-v832.ts';
import { BOX_PRICES, CHARGE_PRICES, EMERGENCY_PRICES } from '../../lib/power-box.ts';
import { CALM_PURCHASE, CALM_RULES, INSULATION_RULES, RISK_RULES, SHOP_PRICES, SOUNDPROOF_RULES, START_RULES } from '../../lib/game-engine.ts';
import { LEGEND_RULES } from '../../lib/legends.ts';
import { PARCEL_RULES } from '../../lib/game-engine.ts';
import { PASSENGERS } from '../../lib/game-data.ts';
const scaleBoxes = (k: number) => { for (const size of ['small', 'big'] as const) for (const tier of ['common', 'rare', 'legendary'] as const) PARCEL_RULES.values[size][tier] = Math.round(PARCEL_RULES.values[size][tier] * k); };
const parcel = (fare: number, coins: number, power: number) => () => { PASSENGERS.courier.fare = fare; PARCEL_RULES.payoutCoins = coins; PARCEL_RULES.payoutPower = power; };

export const VARIANTS: Record<string, () => void> = {
  baseline: () => {},
  // v9.16 Courier parcel study: parcel off (pre-9.16 Courier), then Courier fare × unclaimed-parcel payout (coins / power).
  noParcel: () => { PARCEL_RULES.enabled = false; },
  // v9.17 Courier study: two-part box odds / reward, Thief pickpocketing, Inspector coins.
  v916: () => { VARIANTS.oldThief(); VARIANTS.noBig(); VARIANTS.noInteractions(); VARIANTS.noTiers(); VARIANTS.noBombCarry(); VARIANTS.noMimicCopy(); PARCEL_RULES.adopt = false; PARCEL_RULES.contest = false; },
  oldThief: () => { ECONOMY_RULES.thiefTravel = 3; ECONOMY_RULES.thiefPerVictim = 0; },
  pick1: () => { ECONOMY_RULES.thiefPerVictim = 1; },
  pick3: () => { ECONOMY_RULES.thiefPerVictim = 3; },
  noBig: () => { PARCEL_RULES.bigChance = 0; },
  // Box contents scaled (all tiers and sizes), and tier odds.
  val70: () => { scaleBoxes(0.7); },
  val140: () => { scaleBoxes(1.4); },
  noTiers: () => { PARCEL_RULES.rareChance = 0; PARCEL_RULES.legendaryChance = 0; },
  tiers2x: () => { PARCEL_RULES.rareChance = 0.32; PARCEL_RULES.legendaryChance = 0.08; },
  noBombCarry: () => { PARCEL_RULES.bombCarry = false; },
  noBoxAbility: () => { PARCEL_RULES.abilityChance = { common: 0, rare: 0, legendary: 0 }; PARCEL_RULES.crateAbilityBonus = 0; },
  boxAbility2x: () => { PARCEL_RULES.abilityChance = { common: 0.06, rare: 0.2, legendary: 0.5 }; PARCEL_RULES.crateAbilityBonus = 0.1; },
  noMimicCopy: () => { PARCEL_RULES.mimicCopiesBox = false; },
  big25: () => { PARCEL_RULES.bigChance = 0.25; },
  insp3: () => { PARCEL_RULES.inspectCoins = 3; },
  insp8: () => { PARCEL_RULES.inspectCoins = 8; },
  noInteractions: () => { PARCEL_RULES.childOpens = false; PARCEL_RULES.mechanicParts = false; PARCEL_RULES.inspectCoins = 0; PARCEL_RULES.thiefShare = 0; },
  f3c6p3: parcel(3, 6, 3),
  f3c8p4: parcel(3, 8, 4),
  f3c10p6: parcel(3, 10, 6),
  f6c6p3: parcel(6, 6, 3),
  f6c8p4: parcel(6, 8, 4),
  f6c10p6: parcel(6, 10, 6),
  f8c6p3: parcel(8, 6, 3),
  f8c8p4: parcel(8, 8, 4),
  f8c10p6: parcel(8, 10, 6),
  f10c6p3: parcel(10, 6, 3),
  f10c8p4: parcel(10, 8, 4),
  f10c10p6: parcel(10, 10, 6),
  uLate61: () => { NIGHT_UNREST.from = 61; },
  uArr41: () => { NIGHT_UNREST.arrivalsCalm = true; },
  uArr61: () => { NIGHT_UNREST.from = 61; NIGHT_UNREST.arrivalsCalm = true; },
  a41e15: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 15; },
  a41e15c3: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 15; NIGHT_UNREST.cap = 3; },
  a41e10c3: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 10; NIGHT_UNREST.cap = 3; },
  k62: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 15; NIGHT_UNREST.cap = 3; CALM_PURCHASE.base = 6; CALM_PURCHASE.perTen = 2; },
  k62e20: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 20; NIGHT_UNREST.cap = 3; CALM_PURCHASE.base = 6; CALM_PURCHASE.perTen = 2; },
  k63: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 15; NIGHT_UNREST.cap = 3; CALM_PURCHASE.base = 6; CALM_PURCHASE.perTen = 3; },
  m1: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 15; NIGHT_UNREST.cap = 4; CALM_PURCHASE.base = 6; CALM_PURCHASE.perTen = 2; },
  m2: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 12; NIGHT_UNREST.cap = 4; CALM_PURCHASE.base = 6; CALM_PURCHASE.perTen = 2; },
  m3: () => { NIGHT_UNREST.arrivalsCalm = true; NIGHT_UNREST.every = 15; NIGHT_UNREST.cap = 5; CALM_PURCHASE.base = 6; CALM_PURCHASE.perTen = 3; },
  uNone: () => { NIGHT_UNREST.from = 0; },
  flat2: () => { MOTOR_RULES.flat = 2; },
  f3g41e20: () => { MOTOR_RULES.flat = 3; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 20; },
  f3g51e20: () => { MOTOR_RULES.flat = 3; NIGHT_UNREST.from = 51; NIGHT_UNREST.every = 20; },
  f3g61e20: () => { MOTOR_RULES.flat = 3; NIGHT_UNREST.from = 61; NIGHT_UNREST.every = 20; },
  c2p6s4: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 20; CALM_PURCHASE.price = 6; CALM_PURCHASE.perSector = 4; },
  c2p8s6: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 20; CALM_PURCHASE.price = 8; CALM_PURCHASE.perSector = 6; },
  c2p10s8: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 20; CALM_PURCHASE.price = 10; CALM_PURCHASE.perSector = 8; },
  c2up: () => { VARIANTS.c2p8s6(); CHARGE_PRICES.splice(0, 4, 3, 2.6, 2.2, 1.9); EMERGENCY_PRICES.base = 6; EMERGENCY_PRICES.topTransformer = 5; },
  c2up25: () => { VARIANTS.c2p8s6(); CHARGE_PRICES.splice(0, 4, 2.5, 2.2, 1.9, 1.6); EMERGENCY_PRICES.base = 5; EMERGENCY_PRICES.topTransformer = 4; },
  k1: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 15; CALM_PURCHASE.price = 8; CALM_PURCHASE.perSector = 20; },
  k2: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 31; NIGHT_UNREST.every = 15; CALM_PURCHASE.price = 8; CALM_PURCHASE.perSector = 20; },
  g41e15: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 15; },
  g41e20: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 41; NIGHT_UNREST.every = 20; },
  g51e20: () => { MOTOR_RULES.flat = 2; NIGHT_UNREST.from = 51; NIGHT_UNREST.every = 20; },
  r41e10: () => { MOTOR_RULES.flat = 2; MOTOR_RULES.rampFrom = 41; MOTOR_RULES.rampEvery = 10; },
  r41e10c: () => { MOTOR_RULES.flat = 2; MOTOR_RULES.rampFrom = 41; MOTOR_RULES.rampEvery = 10; V9_AGITATION.crowdSteps = [61, 81]; },
  r61e10: () => { MOTOR_RULES.flat = 2; MOTOR_RULES.rampFrom = 61; MOTOR_RULES.rampEvery = 10; },
  r51e10: () => { MOTOR_RULES.flat = 2; MOTOR_RULES.rampFrom = 51; MOTOR_RULES.rampEvery = 10; },
  r61e7: () => { MOTOR_RULES.flat = 2; MOTOR_RULES.rampFrom = 61; MOTOR_RULES.rampEvery = 7; },
  r51e7: () => { MOTOR_RULES.flat = 2; MOTOR_RULES.rampFrom = 51; MOTOR_RULES.rampEvery = 7; },
  f2c3151: () => { MOTOR_RULES.flat = 2; V9_AGITATION.crowdSteps = [31, 51]; },
  f2c4161: () => { MOTOR_RULES.flat = 2; V9_AGITATION.crowdSteps = [41, 61]; },
  f2c314661: () => { MOTOR_RULES.flat = 2; V9_AGITATION.crowdSteps = [31, 46, 61]; },
  f2c21416181: () => { MOTOR_RULES.flat = 2; V9_AGITATION.crowdSteps = [21, 41, 61, 81]; V9_AGITATION.crowdMin = 2; },
  flat3: () => { MOTOR_RULES.flat = 3; },
  insul1: () => { INSULATION_RULES.coinsPerLink = 1; },
  insul2: () => { INSULATION_RULES.coinsPerLink = 2; INSULATION_RULES.cap = 4; },
  late51: () => { MOTOR_RULES.lateStart = 51; },
  slope4: () => { MOTOR_RULES.lateSlope = 4; },
  l51s6: () => { MOTOR_RULES.lateStart = 51; MOTOR_RULES.lateSlope = 6; },
  l46s7: () => { MOTOR_RULES.lateStart = 46; MOTOR_RULES.lateSlope = 7; },
  l46s8: () => { MOTOR_RULES.lateStart = 46; MOTOR_RULES.lateSlope = 8; },
  n5: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; BOX_PRICES.splice(0, 3, 15, 35, 60); SOUNDPROOF_RULES.riskCap = 99; CALM_RULES.relief = 3; MOTOR_RULES.lateStart = 56; },
  n5x40s55: () => { VARIANTS.n5x40(); START_RULES.energy = 55; },
  n5x40s60: () => { VARIANTS.n5x40(); START_RULES.energy = 60; },
  n5x40: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; BOX_PRICES.splice(0, 3, 15, 35, 60); SOUNDPROOF_RULES.riskCap = 99; CALM_RULES.relief = 3; MOTOR_RULES.lateStart = 56; SHOP_PRICES.extraAbility = 40; },
  n5x30: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; BOX_PRICES.splice(0, 3, 15, 35, 60); SOUNDPROOF_RULES.riskCap = 99; CALM_RULES.relief = 3; MOTOR_RULES.lateStart = 56; SHOP_PRICES.extraAbility = 30; },
  n5noExtra: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; BOX_PRICES.splice(0, 3, 15, 35, 60); SOUNDPROOF_RULES.riskCap = 99; CALM_RULES.relief = 3; MOTOR_RULES.lateStart = 56; SHOP_PRICES.extraAbility = 9999; },
  n4: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; BOX_PRICES.splice(0, 3, 15, 35, 60); SOUNDPROOF_RULES.riskCap = 99; CALM_RULES.relief = 3; V9_AGITATION.lateCrowdingFloor = 51; },
  n4noLateCrowd: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; BOX_PRICES.splice(0, 3, 15, 35, 60); SOUNDPROOF_RULES.riskCap = 99; CALM_RULES.relief = 3; },
  n1: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; BOX_PRICES.splice(0, 3, 20, 40, 65); },
  n2: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; BOX_PRICES.splice(0, 3, 20, 40, 65); MOTOR_RULES.lateSlope = 7; MOTOR_RULES.lateCap = 12; },
  n3: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; BOX_PRICES.splice(0, 3, 20, 40, 65); MOTOR_RULES.lateSlope = 5; MOTOR_RULES.lateCap = 12; },
  cheapPowerMotor21: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 21; START_RULES.energy = 50; },
  cheapPowerMotor11: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 11; START_RULES.energy = 50; },
  cheapPowerMotor31s45: () => { CHARGE_PRICES.splice(0, 4, 2, 1.75, 1.5, 1.25); EMERGENCY_PRICES.base = 4; EMERGENCY_PRICES.topTransformer = 3; MOTOR_RULES.surchargeFrom = 31; START_RULES.energy = 45; },
  start50: () => { START_RULES.energy = 50; },
  start40: () => { START_RULES.energy = 40; },
  start40tips: () => { START_RULES.energy = 40; V9_AGITATION.lowTip = 0; },
  start50legend5: () => { START_RULES.energy = 50; },
  hr2: () => { RISK_RULES.highRiskBonus = 2; },
  chargeUp: () => { CHARGE_PRICES.splice(0, 4, 3, 2.6, 2.2, 1.9); EMERGENCY_PRICES.base = 6; EMERGENCY_PRICES.topTransformer = 5; },
  hr2chargeUp: () => { RISK_RULES.highRiskBonus = 2; CHARGE_PRICES.splice(0, 4, 3, 2.6, 2.2, 1.9); EMERGENCY_PRICES.base = 6; EMERGENCY_PRICES.topTransformer = 5; },
  slope20: () => { MOTOR_RULES.lateSlope = 20; },
  lateCrowd: () => { V9_AGITATION.lateCrowdingFloor = 51; },
  slope20LateCrowd: () => { MOTOR_RULES.lateSlope = 20; V9_AGITATION.lateCrowdingFloor = 51; },
  slope20LateCrowdIncident: () => { MOTOR_RULES.lateSlope = 20; V9_AGITATION.lateCrowdingFloor = 51; V9_AGITATION.incidentChance = 0.3; },
  slope15LateCrowd: () => { MOTOR_RULES.lateSlope = 15; V9_AGITATION.lateCrowdingFloor = 51; },
};
export function applyVariant(name = 'baseline') {
  const v = VARIANTS[name]; if (!v) throw Error('unknown variant ' + name);
  v();
  return { AGITATION_RULES, FARE_RULES, MOTOR_RULES, V9_AGITATION, BOX_PRICES, CHARGE_PRICES, LEGEND_RULES };
}
