export type ChangelogEntry = {
  version: string;
  date: string;
  title: string;
  summary: string;
  changes: string[];
  experiments: string[];
  watch: string[];
};

export const GAME_VERSION = '8.24';

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '8.24', date: '2026-09-04', title: '临时顶班，没有尽头',
    summary: '玩家现在是被临时派往古怪大楼的电梯操作员。开场立即说清这是一场没有最后一层的生存夜班：守住两项资源，尽可能活久一点。',
    changes: [
      '开场从乘客视角改为玩家视角：明确你是临时电梯操作员，地点是一座古怪且没有尽头的大楼。',
      '三步引导改为“接客并安排站位→守住电量与躁动→尽可能生存下去”，不再把世界观、操作和细节规则挤进同一段文字。',
      '值班手册摘要与班次标签同步为“临时夜班 / 无尽夜班”，中英文叙事保持一致。',
      '打开“躁动说明”或“更新记录”时切换为 theme 主题曲；关闭后恢复当前楼层音乐，统一暂停阅读界面的听觉语法。',
      '躁动说明底部新增“开始游戏”主按钮，与当前站位预测并排，无需滚动即可继续。',
      '补齐英文版漏翻：手册的商店说明、人物详情的邻座/到站规则、躁动帮助和辅助功能标签现在全部是英文。',
      '本版未改动任何人物数值、资源结算、掉落权重或难度曲线。',
    ],
    experiments: [
      '对开场文案做信息层级检查：标题只建立身份与悬念，正文只解释生存条件，三步条只保留开始游玩前必需的决策。',
      '英文回归样本从1,281条扩展到1,595条，新增21种人物的完整详情卡覆盖；浏览器逐页检查开场、主界面、手册、躁动说明、人物详情、档案、升级清单与更新记录，除语言切换键“中文”外没有中文残留。',
      '验证中英文本地化与生产构建；开场保留单个主按钮，不增加进入游戏前的额外步骤。',
      '增加音乐场景回归：开场、躁动说明与更新记录均选中 theme，关闭后重新选中当前楼层曲，商店与失败曲不受影响。',
    ],
    watch: ['观察“古怪大楼”是否能激起好奇、同时不让玩家误以为存在剧情终点；后续叙事应通过乘客与楼层事件展开，而不是继续加长开场文案。'],
  },
  {
    version: '8.23', date: '2026-09-04', title: '人物卡只说三件事',
    summary: '候客卡统一成“自身、绿色邻座、红色邻座”三段；同一种摆位操作不再混用“相邻、协作、阻止”等多套说法，状态栏也改成更直接的当前值/上限。',
    changes: [
      '21种人物全部改用同一信息结构：卡头只放到站金币、每层耗电和非零躁动；自身能力、绿色邻座收益、红色邻座损失各自只出现一次。',
      '删除“Prevented by…”等条件复述。通用绿色到站奖励提到绿色标题旁只显示一次；绿色列表只列对象与特殊后果，相同红色后果的多个人物合并成同一行。',
      '金币结算时点统一写明：“每上1层立即”会在每次上行后直接改变余额；“本人到站时”只在该人物离开电梯时结算，不再用含混的“收益 +1/层”。',
      '隐藏“躁动 +0”；需要表达控制结果时改写成“不加躁动”。候客提示、开场和手册统一使用“绿色收益 / 红色损失 / 邻座叠加”。',
      '手机候客区改成一次显示一张完整卡，并提供三个人名标签切换；不再把三张完整规则卡压进三列。',
      '电量与躁动改为50/60、0/6式当前值/上限；余额下方删除班次累计，只保留距商店层数。',
      '本版没有改动人物数值、掉落权重、结算顺序或叠加公式；这是一次纯信息架构与响应式布局更新。',
    ],
    experiments: [
      '为21种人物逐张生成三段式卡面并做自动审计：每张都保留绿色决策，红色对象没有重复，同一卡面不再出现“协作/冲突/相邻/挨/旁边”等竞争术语。',
      '对警察、小偷和音乐家做定向回归：警察的小偷控制与炸弹倒计时各一行；相同的小偷金币损失对象合并；音乐家仍明确对每位邻座−2躁动。',
      '在1440×900桌面和390×844手机浏览器实测中英文、三段结构、零值隐藏和仪表栏；卡面正文没有横向或纵向截断，手机页面没有横向溢出。',
    ],
    watch: ['观察真人是否能只凭三段卡面完成第一次站位；若仍需频繁打开详情，优先继续缩短个别人物的自身能力，不再增加第四个卡面区块。'],
  },
  {
    version: '8.22', date: '2026-09-04', title: '每个邻座都是构筑的一部分',
    summary: '相邻能力现在明确面向所有相邻人物并线性叠加；音乐家、护士、教练与小偷重新定位后，少载客不再是远远领先的唯一理性路线。',
    changes: [
      '音乐家成为稀有的短期控场核心：出现权重7→4、到站车费8→14、路程4–8→2–5、每层耗电1→2；位于中间位时，所有相邻乘客每人各抵消2躁动，多位音乐家继续逐人叠加。',
      '护士改为常见的轻量控场：到站车费9→8、出现权重7→8、每层耗1电；所有相邻乘客每人各抵消1躁动。两个职业都能照顾多个邻座，但在稀有度、强度和耗电上有明确取舍。',
      '教练每层耗电2→1，保留车费20、3–6层路程、每位相邻教练使基础车费+50%与本人到站每邻座+3金币。高价卡不再因持续占用2电成为隐性陷阱。',
      '小偷路程3–7→2–6层，保留未受控时每层+4金币与+1躁动；现在是更短、更可管理的高风险窗口。',
      '每位正常到站乘客让当层躁动−1，同层最多−2；这让多人周转获得可预测的小额回报，但不能无限清空躁动。',
      '警察卡面同步明确：会同时控制所有相邻小偷，并分别锁住所有相邻炸弹客的倒计时，不存在隐藏的单目标上限。',
      '修复音乐淡出最后一帧可能因浮点误差写入负音量、触发浏览器运行时错误的问题；现在音量始终限制在0–1。',
    ],
    experiments: [
      '迭代阶段累计运行481,055局，筛选了到站舒缓、1币充电、护士全邻座、教练短程/倍率/耗电、初始46电、音乐家长短周期与小偷路程。否决1币充电、教练+100%倍率、初始46电和长途高耗电音乐家。',
      '最终独立留出测试50,950局：均衡打法平均45.60层、中位46，94.52%到20层、79.12%到40层；失败中11.64%断电、88.24%躁动、0.12%炸弹倒计时。高风险打法则74.88%断电，两项资源会约束不同构筑。',
      '节俭三人打法平均50.65层，与均衡打法的差距从基线约10层缩小到5.05层；协作打法平均43.58层，高风险打法25.59层。它们仍有不同风险曲线，但少载客已不再领先整整一个商店周期。',
      '21种人物全部做正常/偏爱/禁用同种子对照：正常选取率18.0%–62.2%，没有弃牌、自动拿、不可替代或陷阱警报。音乐家39.9%选取，偏爱−1.26层；教练62.2%，偏爱−0.02层；小偷35.8%，偏爱−1.52层。因此本版不删除或新增人物，先用重做定位解决重叠与无分量问题。',
      '穷举21种中心人物×三个邻座的194,481种排列，并跑过4,000条随机状态预测回归；所有相邻效果、红绿线、到站舒缓、电量与躁动预测误差为0。',
    ],
    watch: ['程序策略不等于真人最优解。真人试玩重点观察：中间位音乐家影响三人是否足够爽快；高耗电是否让它仍需要规划；三人节俭路线的5层优势是安全风格差异还是仍需继续缩小。'],
  },
  {
    version: '8.21', date: '2026-09-04', title: '午夜班次有了完整配乐',
    summary: '主题、楼层、商店与失败画面现在各有对应音乐；1–120层按十层一段推进，超过120层后随机轮播此前的楼层音乐。音乐和操作音效可以分别开关。',
    changes: [
      '接入15首玩家制作的音乐：主题曲、12段楼层曲、商店曲与失败曲。补齐51–60层后，1–120层没有音乐空档。',
      '每十层自动换到对应曲目；同一十层区间内摆放人物或继续上行不会让音乐从头播放。进入商店和失败画面会切换专属曲目，离开后恢复当前楼层段落。',
      '121层起进入无尽随机播放：每首播完后从12段楼层音乐中重抽，并避免立即重复刚播完的一首。',
      '页首新增独立音符按钮。它只开关背景音乐并记住玩家选择；原扬声器按钮现在只控制操作音效。',
      '无损WAV母带保留在本地项目的source-audio目录；线上使用统一响度的128 kbps MP3，将约503 MB母带压缩为约48 MB发布资源。',
    ],
    experiments: [
      '自动验证15个线上音频文件存在且非空，覆盖1、10、11、51、120、121和超高楼层选曲边界。',
      '验证主题→楼层→商店→失败的场景切换、同区间不重启、独立静音与121层后的随机防连播逻辑。',
    ],
    watch: ['真人试听重点观察各曲之间的主观响度、循环接缝和场景切换是否自然；如果48 MB仍影响首次加载，将进一步按曲目内容降低码率，而不是缩短音乐。'],
  },
  {
    version: '8.20', date: '2026-09-04', title: '红线成为真正的代价网络',
    summary: '冲突不再只有躁动一种答案：35种红线会损失金币、额外耗电、增加躁动，或用双倍耗电换双倍车费；三条续航路线重新定价后，没有人物成为必拿或必禁。',
    changes: [
      '静态红色关系从19组扩展到35组：12组每层+1躁动、12组每层损失2金币、8组每层额外耗1电、2组使双方耗电×2、1组同时使双方耗电×2与到站车费×2。',
      '红线不再依赖奇偶层，也不会被绿线消除；绿色协作与红色代价分别结算。多条同类倍率按基础值线性叠加：两条×2红线合计为×3，不会指数翻成×4。',
      '红虚线中央直接显示🔥、⚡或🪙；候客卡写出每个冲突对象的具体代价。神秘人、百变人与复制关系也携带当前可见的红线类型。',
      '能源经济锁定为初始50电、容量60、抵达商店先补5电、额外充电2金币换1电。快递员到站补2电，出现权重9→4；维修工耗2电、每层节能2电，出现权重7→3；每位受控幽灵每层节能1→2电。',
      '无警察或律师的小偷途中收入从每层3提高到4金币，保留每层+1躁动与受控后改赚1金币、到站+5的取舍。',
      '警察与炸弹客的联动不再依赖偶数层：两者相邻期间直接锁住炸弹倒计时。它是占用两个站位的稳定保命组合，分开后倒计时立即恢复每层−1。',
    ],
    experiments: [
      '本轮迭代累计运行超过28.5万局完整程序实验，依次筛选初始电量、商店免费补电、充电价格、维修工净耗电、快递员与维修工供给权重、受控幽灵强度；否决了商店补6、补3以及维修工条件式红线抵消等方案。',
      '最终独立留出测试35,200局：均衡打法平均39.60层、中位44层，83.44%抵达20层、58.52%抵达40层；失败中32.72%断电、67.16%躁动、0.12%炸弹倒计时，保持双资源夹击。',
      '警察锁定倒计时加入后再做同种子对照：偏爱警察只增加1.83层，禁用警察改变+0.10层；炸弹客偏爱改变0.00层、禁用改变−0.07层，没有形成必拿保命组合。',
      '21个人物分别做同种子正常、偏爱、禁用对照，没有必拿、必禁、强制堆叠或陷阱警报。最强偏爱变化为恋人+1.96层；禁用快递员−3.45层、维修工−3.76层，续航不再由单一人物垄断。',
      '穷举21种中心人物与三名邻座的194,481种排列，并增加35组红线图谱、五种代价、双红线与红绿并存回归；倍率保持线性，所有完整实验及4,000条随机状态的下一层电量/躁动预测误差为0。',
    ],
    watch: ['真人试玩重点观察：红线图标是否能让乘法代价在关门前一眼读懂；稀有续航牌的出现频率是否形成“拿到很高兴、没拿到也能活”的体验；教练高收益高耗电路线是否仍值得主动承担。'],
  },
  {
    version: '8.19', date: '2026-09-03', title: '旅伴成为真正可叠加的多人路线',
    summary: '游客现在会把每一位相邻乘客都当作旅伴，包括另一位游客；收益与绿色连线逐人叠加，不再有 2 人上限。',
    changes: [
      '旅伴收益改为“每位相邻乘客：每站+1金币”；同职业与其他游客都会分别计数。',
      '删除 2 人规则上限和“x/2”显示；单个站位的最多3位旅伴只来自六格轿厢的几何关系。',
      '任意两名相邻游客现在会显示绿色旅伴连线；每一条有效旅伴关系都和卡面即时收益一致。',
      '旅伴绿线只表示游客途中收益，不会暗中发放卡面没有写的通用到站协作奖励；教练仍只倍增基础车费。',
    ],
    experiments: [
      '穷举21种中心人物与三名邻座的194,481种组合，并定向验证216种游客三邻座排列；0/1/2/3位旅伴稳定对应0/1/2/3金币，游客互邻连线与收益一致。',
      '新规则运行27,000局完整程序测试，预测误差为0。同种子前后对照中，均衡打法平均生存42.67→42.78层，平均收入683.86→699.35，提升收益而没有拉高生存。',
      '独立种子17,000局留出测试中，游客正常选择率44.7%，偏爱后58.9%；强制偏爱反而少生存0.46层，禁用只改变+0.16层，没有必选、无法替代或堆叠必胜警报。',
      '六游客满舱共7条相邻边，中途收益上限为14金币/层；与六恋人的中途连线收益同量级，但没有恋人的到站车费倍增。',
    ],
    watch: ['观察真人是否会因为绿线更直观而更愿意组成多游客团；如果满舱旅游在实际操作中过度稳定，优先调整游客的路程或基础车费，不破坏逐人叠加。'],
  },
  {
    version: '8.18', date: '2026-09-03', title: '炸弹风险改成一眼能懂的倒计时',
    summary: '所有玩家可见的“引信”统一改为“炸弹倒计时”，直接说明每层如何变化、何时失败以及警察怎样暂停它；玩法数值不变。',
    changes: [
      '炸弹客卡面现在写明“炸弹倒计时”：初始3–6层，每上升一层−1，到站前归零则本局失败，到站当层归零仍然安全。',
      '警察卡面改为“邻炸弹：偶数层倒计时不减”；律师则明确写成不能暂停炸弹倒计时，不再使用“引信”或“延缓”。',
      '车内标签、人物详情、失败标题、失败原因、下一局建议、乘客档案和复制人限制全部使用同一套说法。',
      '英文同步改为“Bomb timer”，避免“Fuse”要求玩家先理解隐喻。',
    ],
    experiments: [
      '逐项验证炸弹客候客卡、已上车标签、详情弹窗、警察/律师联动、失败原因与中英文翻译；所有可见状态都能从“倒计时数字”直接读出剩余安全层数。',
      '规则回归继续验证倒计时每层−1、警察只在偶数层暂停、到站前归零失败、到站当层归零安全；未调整车费26、耗电1、路程2–6或初始倒计时3–6。',
    ],
    watch: ['“炸弹倒计时”更直白但字数更长；继续观察极窄手机屏幕上的车内短标签是否需要进一步压缩为“炸弹 4”。'],
  },
  {
    version: '8.17', date: '2026-09-03', title: '叠加规则终于和卡面完全一致',
    summary: '全面审计21个人物的重复上车、扇形控制、协作与冲突叠加；修复红色冲突在奇数层也暗中增加躁动的问题，不改动人物公开数值。',
    changes: [
      '每条红色邻座冲突现在严格只在即将抵达偶数层时增加1躁动，与人物卡一直显示的规则一致；奇数层不再暗中结算冲突躁动。',
      '绿色协作仍按每条连接线性结算；一条绿色协作仍会免除该人物的红线冲突，但不会免除高危、自身躁动、未受控小偷等人物技能。',
      '维修工仍每位节能2电；受控幽灵、快递回电、游客职业数、教练倍率、护士/警察扇形控制与复制人三项复制均保持原参数。',
      '新增可重复运行的全人物叠加审计，记录同类共存率、协作覆盖率、三邻座穷举、随机属性分布和每种核心叠加曲线。',
    ],
    experiments: [
      '运行55,604局完整程序实验，并检查306,663个受控叠加与随机属性样本；其中穷举21种中心人物与三名邻座的194,481种排列，所有电量和躁动预测误差为0。',
      '每种人物分别做600局正常、偏爱与禁用对照。偏爱后同类共存最高的是恋人25.2%，但平均生存−0.67层；没有任何人物堆叠带来超过+1.09层优势，因此不存在单一叠加必胜路线。',
      '六恋人满舱在同层全部到站时为176币，每级默契契约再线性增加28币；三名教练让游客基础车费18→45，礼宾小费仍只逐级+3，不参与倍率。',
      '维修工节能降为1的9,800局对照被否决：均衡打法到40层从约69%降至56.5%，激进打法中位只剩10层，但完全禁用维修工仍损失11.43层，没有真正解决续航依赖。',
    ],
    watch: ['维修工仍是通用续航核心，但额外偏爱只+1.09层，暂不复杂化其叠加规则。小偷只有与警察/律师一起堆叠才成立；盲目偏爱小偷会−4.50层，应继续观察卡面是否足够提醒这个条件。'],
  },
  {
    version: '8.16', date: '2026-09-03', title: '每个人物都要面对双资源选择',
    summary: '游客、快递员与教练不再因耗电机会成本沦为华丽陷阱；能源现在有持续节能和短途回电两条路线，同时保留躁动与断电的夹击。',
    changes: [
      '初始电量从48调整为42，容量仍为60；用于抵消新增的短途回电，不改变每站运转1电、商店充电1币换1电与至少搭载1人的规则。',
      '游客每站耗电从2降为1；基础车费18、4–7站路程与不同职业旅伴每站+1币（最多+2）保持不变。',
      '快递员到站时补充1电，不超过电量上限；候客卡、车内状态、结算动画与下一站电量预测都会明确显示这次补电。',
      '教练仍每站耗2电，路程从4–8站缩短为3–6站；+50%邻座基础车费倍率和本人到站每邻座+3币不变。',
    ],
    experiments: [
      '本轮共运行221,126局完整程序实验，并用86,016条受控轨迹检查21个人物的协作、冲突、耗电、躁动与到站结算；弃用了神秘人隐藏车费按0估值、初始36电、快递补2电、教练耗1电及低电商店保底能源卡等方案。',
      '最终独立随机种子留出测试33,200局：四种整体打法各2,000局，21个人物各做400局正常、400局偏爱、400局禁用；所有下一站电量与躁动预测误差为0。',
      '均衡打法平均41.45层、中位44层；91.55%抵达20层、66.75%抵达40层。失败中26.95%断电、72.90%躁动、0.15%引信，双资源威胁会随打法改变。',
      '21个人物正常选择率为17.7%–62.2%，没有绝对弃牌或必拿牌。游客偏爱只改变+0.20层，快递−0.38层，教练−0.68层；高风险小偷偏爱−3.34层，仍保留明确代价。',
    ],
    watch: ['维修工仍是最强续航支柱：正常选择率62.2%，额外偏爱只+0.27层，但完全禁用会少13.95层。继续用真人局观察它是健康的流派核心，还是需要第三条续航路线。'],
  },
  {
    version: '8.15', date: '2026-09-03', title: '游客变成拼邻座的长线投资',
    summary: '游客不再是单纯高耗电白板：他的价值现在来自不同职业旅伴，玩家需要为长途收益设计站位。',
    changes: [
      '游客基础车费从22调整为18，路程从3–7层调整为4–7层，每站耗电保持2。',
      '每种不同职业的非游客邻座，让游客每层多赚1金币，最多+2；相邻游客不计，同职业不重复。',
      '车内游客会实时显示“旅伴 0/2–2/2”和下站收益；候客卡增加旅行网格纸材质与“旅伴加成”纪念章，但仍诚实标为精良卡。',
      '游客的途中收益与基础车费分开结算：教练只放大基础车费，旅伴金币不参与倍率。',
    ],
    experiments: [
      '定向验证216种三邻座组合，覆盖空座、同职业、多职业、游客互邻、到站层与教练/绿线分开结算。',
      '同随机种子的10,000局前后对照中，均衡策略中位数保持25层，平均收入从322.79微升到324.06，没有形成必选游客。',
      '另用新随机种子留出测试20,000局、367,691次楼层结算，所有电量/躁动预测误差为0；均衡策略中位仍为25层。',
      '同时对“说书人”概念进行600,000次隔离测试：原案中位解锁需15–19层，存在软锁；每层额外20%吸引儿童后中位降至6层，超过20层未解锁降至4.72%–5.92%。该人物本版尚未加入正式游戏。',
    ],
    watch: ['观察玩家是否会为游客主动保留多职业邻座；说书人建议参数需经玩家确认后再进入正式规则。'],
  },
  {
    version: '8.14', date: '2026-09-03', title: '人物卡头部不再互相抢位',
    summary: '人物卡最上方重新严格区分“数值”和“能力”：三项数值保持短而稳定，完整条件留在下方规则区。',
    changes: [
      '躁动总览统一显示为简短的“自身 +0/+1”；音乐家、护士等较长的抵消规则只在能力区显示一次，不再侵入稀有度与路程标签。',
      '桌面卡头改用可收缩身份列和固定宽度数值列；英文长姓名使用更稳妥的字号，避免数值、姓名、材质标签和帮助按钮互相覆盖。',
      '手机卡的材质与数值区补充最小宽度约束，保持完整规则且不出现横向溢出。',
    ],
    experiments: [
      '在1280×720浏览器中检查三批中文候客卡和一批英文候客卡，覆盖长条件、材质标签与紧凑桌面栏；目视确认身份、数值、标签和规则区不再相叠。',
      '逐段审查桌面、短屏、手机与横屏媒体规则；完整规则、双语、构建与版本记录回归继续通过。本次未调整任何人物或资源数值。',
    ],
    watch: ['继续收集极窄桌面窗口与系统大字体设置下的卡面截图。'],
  },
  {
    version: '8.13', date: '2026-09-03', title: '本层决策一眼可见',
    summary: '候客、车内风险与十层商店获得更明确的即时反馈；本次只改善信息层级，不改变人物或生存数值。',
    changes: [
      '右侧已上车的候客卡改为灰色半透明；本层新上车人物在车厢内显示高亮金圈，旧乘客不会被误标。',
      '若按当前站位上行会让电量耗尽或躁动达到上限，左栏对应的下一站变化数字会变红并抖动；减少动态效果的系统设置下保留静态警示色。',
      '每个9、19、29层等商店前一层都会明确显示“下一站：商店”，并用高亮提示取代普通班次预告。',
      '玩家界面统一称为“商店”，商店说明与离开操作进一步精简。金币总额移到商店最上方并显著放大。',
    ],
    experiments: [
      '新增楼层9与39的商店预告回归，并继续验证下一站电量、躁动预测与实际结算一致。',
      '完整规则验证继续覆盖定向人物配对、随机状态跳转、堆叠、连接、双语与版本记录约束；本次未调整平衡参数。',
    ],
    watch: ['观察持续抖动是否足够醒目但不过度干扰，以及灰色候客卡在不同屏幕亮度下是否仍清楚可撤回。'],
  },
  {
    version: '8.12', date: '2026-09-03', title: '双资源夹击',
    summary: '躁动改成完全可追踪的人物风险，能源重新成为必须规划的生存资源；玩家要在充电、升级和高危高回报乘客之间持续取舍。',
    changes: [
      '躁动上限固定为6；移除拥挤、班次压力、空驶休整与高躁动倍率。躁动现在只来自卡片明示的人物自身、高危标记、人物事件和未被保护的红线。',
      '护士与音乐家每位每层抵消一名相邻乘客的1躁动，可堆叠但不产生负数；本层只要有人正常到站，总躁动最多降低1。舒缓系统改为上限+1并立即−2。',
      '高危乘客固定多+1躁动、到站多得8金币；30层起逐步出现，40层起每批至少1张，80层至少2张，120层起三张均为高危。',
      '初始电量48、容量60、每点充电1金币、推荐补至50电。玩家必须至少搭载一名乘客才能上行，不能用空载绕过人物风险。',
      '检查员改为每层检查总耗电；不超过4电每层+1金币，超过则每层+1躁动。高危卡增加铜红材质、火焰标签与车内标记。',
    ],
    experiments: [
      '先后筛选初始电量36–60、容量48–72、充电价1–2、躁动上限6–10，以及六组高危起点、保底间隔和爬升速度。',
      '最终独立留出测试共40,000局、1,050,768次楼层结算，电量与躁动预测误差均为0。',
      '均衡策略平均38.07层、中位43层；96.92%抵达10层、81.20%抵达20层、57.85%抵达40层、6.26%抵达60层。失败中28.66%为电量耗尽、70.89%为躁动失控，形成双资源威胁。',
      '忽略躁动与贪收益策略的中位数均为9层；限制载客并保守留电的策略中位49层，说明不存在靠单一高收益或满载策略稳定碾压的路径。',
    ],
    watch: ['真人是否会觉得30–40层的高危爬升过慢；高危+8金币是否足以诱惑玩家在低躁动时主动承险。'],
  },
  {
    version: '8.11', date: '2026-09-03', title: '维修工节能行完成本地化',
    summary: '最终线上检查发现维修工独有的紧凑能源行仍为中文；现已补齐，并把能源行加入全人物运行时翻译回归。',
    changes: [
      '维修工卡面的“每位每层节能2电、可叠加”现在完整显示为英文。',
      '21类人物的英文回归现在同时检查能源、收益、躁动与技能四类运行时行。',
      '教练仍保持通用说明，不点名神秘人；本次未改变任何玩法数值或材质分级。',
    ],
    experiments: [
      '普通与高躁动两种状态共检查21类人物的全部紧凑卡面字段，确认不再残留中文。',
      '完整规则验证继续覆盖52,920个定向配对/站位案例、48,000次随机状态跳转、60个连接案例、8类堆叠与768个交互案例。',
    ],
    watch: ['持续用线上实际候客组合验证新增动态文案。'],
  },
  {
    version: '8.10',
    date: '2026-09-03',
    title: '英文卡面规则完整可读',
    summary: '线上目视复测发现部分人物的紧凑规则仍混有中文；本次补齐全部21类人物的运行时卡面翻译，并把这些动态句式纳入自动回归。',
    changes: [
      '补齐小偷、警察、律师、醉汉、音乐家、护士、儿童、幽灵、驱魔师、教练、名人、检查员、炸弹客、神秘人、百变人与复制人的紧凑规则翻译。',
      '修复数值会变化的偶数层躁动、25%闹事、检查员阈值、炸弹引信和复制属性句式，避免运行时替换后残留中文。',
      '教练卡仍只写通用相邻加成规则，不为神秘人组合增加特例文案；隐藏车费结算逻辑保持不变。',
      '本次未改变任何人物数值、材质分级、出现概率、耗电、躁动、金币或升级效果。',
    ],
    experiments: [
      '新增21类人物在普通与高躁动两种状态下的运行时卡面翻译回归，覆盖静态规则与动态数值句式。',
      '线上目视复测确认英文候客卡不再中英混排，卡面正文无裁切，主操作按钮保持单行。',
      '完整规则验证继续覆盖52,920个定向人物配对/站位案例、48,000次随机状态跳转、60个连接案例、8类堆叠与768个交互案例。',
    ],
    watch: ['继续观察高规则密度人物在较窄桌面宽度下的阅读节奏。'],
  },
  {
    version: '8.9',
    date: '2026-09-03',
    title: '乘客卡获得价值材质',
    summary: '候客卡不再像同一批印刷品：出现稀有度与基础回报共同决定材质层级，高价值人物会在第一眼就显得不同，同时彻底避免规则被截断。',
    changes: [
      '新增常规、精良、稀有、传奇四档卡牌材质：常规为深色纸面，精良为拉丝铜，稀有为金箔漆面，传奇为克制的虹彩黑曜石。',
      '分级阈值固定为：出现权重≤4或基础车费≥30为传奇；权重≤6或车费≥20为稀有；权重≤8或车费≥14为精良；其余为常规。教练为稀有，百变人与炸弹客为传奇。',
      '神秘人只按公开出现权重分级，不读取隐藏车费，因此卡面不会泄露封存奖励。',
      '桌面候客区改为内容决定卡高；三张完整规则超过可用高度时只滚动右侧候客区，不再在卡片内部截掉文字。',
      '补齐教练与隐藏车费的结算回归：神秘人的封存基价仍会接受每位相邻教练50%的线性倍率，但不把特殊组合写进卡面。',
      '本次未改变任何实际人物、耗电、躁动、金币、出现概率或升级数值。',
    ],
    experiments: [
      '新增双教练夹住神秘人的结算回归：隐藏基础车费31经两位教练线性叠加后精确结算62金币，揭晓日志仍只在到站时出现。',
      '验证常规、精良、稀有、传奇四档代表人物，并确认分级函数不接收神秘人的隐藏参数。',
      '完整规则验证继续覆盖52,920个定向人物配对/站位案例、48,000次随机状态跳转、60个连接案例、8类堆叠与768个交互案例。',
    ],
    watch: [
      '材质现在表达“出现稀有度或基础回报”，不是无条件强度；继续观察玩家是否会把金卡误解成必选。',
      '右侧候客区只在长规则组合时出现内部滚动；继续观察是否需要更明显的末端渐隐提示。',
    ],
  },
  {
    version: '8.8',
    date: '2026-09-03',
    title: '候客卡只保留有用反馈',
    summary: '移除每张候客卡底部重复出现的操作说明，让空间留给人物规则；真正影响下一步操作的状态仍会即时显示。',
    changes: [
      '未选中且可正常上车的候客卡不再显示“拖入空位 / 点选上车”。',
      '“已选中 · 点空位”“点此撤回”“车厢已满”以及可立即形成联动的提示继续按状态显示。',
      '本次未改变人物、耗电、躁动、金币、难度段或升级的任何玩法数值。',
    ],
    experiments: [
      '中英文界面均检查默认候客卡、选中、已上车、满载与可联动状态，确认只有默认重复说明被移除。',
      '完整规则验证继续覆盖 52,920 个定向人物配对/站位案例、48,000 次随机状态跳转、60 个连接案例、8 类堆叠与 768 个交互案例。',
      '生产构建与 GitHub Pages 静态构建通过；候客卡渲染路径中不再包含被删除的中英文默认提示。',
    ],
    watch: [
      '规则较少的人物卡底部会自然留白；暂时保留这段呼吸空间，不再用通用说明填满。',
      '继续观察首次游玩的玩家是否能仅凭拖拽反馈和选中状态顺利完成上车操作。',
    ],
  },
  {
    version: '8.7',
    date: '2026-09-03',
    title: '午夜班次走向双语',
    summary: '游戏现在默认以完整英文呈现，同时保留一键切换的完整中文界面；玩法与平衡数值不变。',
    changes: [
      '默认语言改为英文；顶部新增“中文 / EN”切换按钮，选择中文后网址会保留 ?lang=zh，刷新后仍进入中文界面。',
      '英文覆盖开场、人物卡、车内状态、协作与冲突、值班手册、乘客档案、升级商店、结算、失败提示和完整更新记录。',
      '浏览器页面语言默认标记为 en，切换中文时同步改为 zh-CN，辅助技术可识别当前语言。',
      '本次未改变人物、耗电、躁动、金币、难度段或升级的任何玩法数值。',
    ],
    experiments: [
      '新增本地化覆盖校验，逐项检查人物、升级、规则、动态界面文案及版本记录，不允许默认英文界面残留未授权中文。',
      '完整规则验证继续覆盖 52,920 个定向人物配对/站位案例、48,000 次随机状态跳转、60 个连接案例、8 类堆叠与 768 个交互案例。',
      '生产构建与 GitHub Pages 静态构建均通过；默认静态 HTML 的 lang 为 en，并保留中文入口。',
    ],
    watch: [
      '继续观察英文长规则在 375×667 等短手机上的阅读密度；必要时只压缩措辞，不隐藏关键数值。',
      '新人物与新机制以后必须同时补齐中英文文案，避免两种语言的规则产生分叉。',
    ],
  },
  {
    version: '8.6',
    date: '2026-09-03',
    title: '把难度墙改成生存考题',
    summary: '保留高压段的压迫感，但让正确管理躁动的玩家有稳定穿越机会；同时收紧手机操作区与新手文案。',
    changes: [
      '17–19、27–29 等高压三层的班次躁动由每层 +5 调整为 +4；4–6 段仍为每层 +1，其他难度节奏不变。',
      '手机操作区移除重复的下一站预测、耗电公式与换位说明；关门上行按钮由 44 高提升至常态 74 高。',
      '需要选位置时才显示一行即时操作提示，不再持续占用游戏画面。',
      '新手班次改写为“用恋人观察绿色协作线”的示例，不再暗示恋人是唯一正确打法。',
      '候客列表补齐列表语义，并移除动态数字上无效的辅助属性；自动无障碍检查无违规项。',
    ],
    experiments: [
      '修正模拟器此前从不在补给站充电的问题，使电脑策略遵守游戏内“先留充电费”的决策提示。',
      '新参数运行 20,000 局、累计 370,594 次楼层结算；电量与躁动预测误差为 0。',
      '均衡策略 99.92% 抵达 10 层、44.58% 抵达 20 层、19.60% 抵达 30 层，最高 100 层；忽略躁动策略只有 2.66% 抵达 20 层，说明控躁决策具有决定性。',
      '在 1440×900、390×844 与 375×667 三种视口复测首屏、配对、结算反馈与十层商店；均无需页面滚动，商店主操作保持在首屏。',
    ],
    watch: [
      '均衡模拟的中位数仍为 19 层，符合“举步维艰”的目标，但真人是否觉得首个高压段过于陡峭仍需继续观察。',
      '短手机为保留完整人物规则会一次重点展示一张候客卡；继续观察横向切换是否足够自然。',
    ],
  },
  {
    version: '8.5',
    date: '2026-09-03',
    title: '版本记录进入游戏',
    summary: '版本号现在是入口，而不再只是页脚装饰；手机和桌面都能随时查看改动依据。',
    changes: [
      '顶部新增可点击版本按钮；桌面页脚版本号也可打开同一份更新记录。',
      '更新记录统一写明玩法变化、数值变化、测试规模、结论和待观察项。',
      '加入发布校验：版本号、游戏内记录和项目记录不一致时，测试会直接失败。',
    ],
    experiments: [
      '继承 v8.4 的 17,750 局流派测试与 1,083,654 次楼层结算结果。',
      '重新运行 52,920 个定向人物配对/站位案例与 48,000 次随机状态跳转，预测误差为 0。',
      '生产构建和版本入口自动校验通过。',
    ],
    watch: [
      '观察玩家是否会主动使用更新记录理解数值变化。',
      '以后每次发布必须先补齐本页记录，再提高版本号。',
    ],
  },
  {
    version: '8.4',
    date: '2026-09-03',
    title: '堆叠与流派成型',
    summary: '让重复人物和多条连接真正形成构筑，同时保留明确的物理上限。',
    changes: [
      '每条绿色协作线分别支付到站奖励；卡片直接显示“+3×2”一类当前结果。',
      '每条红色冲突线分别增加躁动；存在绿色协作时，该人物免除邻座冲突。',
      '每位维修工每层节能 2；受控幽灵、节能线路与维修工可以逐项相加。',
      '恋人与教练改为线性叠加；护士、音乐家、检查员等重复人物继续各自结算。',
    ],
    experiments: [
      '两轮共 17,750 局流派对照，覆盖维修工、恋人、教练、灵异、控躁和混合策略。',
      '累计 1,083,654 次楼层结算，能量与躁动预测误差为 0。',
      '21 种人物完成双绿线、双红线和绿线保护的定向检查；另验证 8 类特殊堆叠。',
    ],
    watch: [
      '纯堆叠构筑没有超过动态混合策略，但实战玩家可能比启发式策略更会集中资源。',
      '节能最多抵完人物耗电，不能抵消电梯运转，也不能形成倒充电。',
    ],
  },
  {
    version: '8.3',
    date: '2026-09-03',
    title: '维修工改为持续节能',
    summary: '移除“3 的倍数层”记忆负担，让维修工每站都能产生可预测价值。',
    changes: [
      '维修工从周期触发改为每层节能，单人机制更容易理解。',
      '躁动统一使用火焰图标，避免与计时器混淆。',
      '十层商店压缩信息密度，并把“继续上行”保留在一屏内。',
    ],
    experiments: [
      '验证维修工独处、搭载低耗电人物和搭载高耗电人物的边界。',
      '检查节能不会抵消电梯运转，也不会让电量反向增长。',
    ],
    watch: ['该版维修工仍为共享上限；v8.4 根据实玩反馈进一步改成可堆叠。'],
  },
  {
    version: '8.2',
    date: '2026-09-03',
    title: '躁动表达与商店可读性',
    summary: '把难以理解的耐心概念完全收束为金币、耗电、躁动三个核心值。',
    changes: [
      '人物卡片直接描述会增加或减少多少躁动。',
      '技能数值补齐对应图标，缩短重复文字。',
      '商店卡片重新压缩，保留购买判断所需的信息。',
    ],
    experiments: ['复查高躁动倍率、检查员耗电判定和商店离开条件。'],
    watch: ['继续观察小屏设备上长人物能力是否仍会换行。'],
  },
  {
    version: '8.1',
    date: '2026-09-03',
    title: '车内人物信息常驻',
    summary: '玩家不必依赖记忆或悬停，也能看见已经上车人物的关键参数。',
    changes: [
      '车内人物保留金钱、耗电、躁动和剩余站数。',
      '人物图片采用裁切而非拉伸，并强化已上车状态与连接线。',
    ],
    experiments: ['验证不同卡片宽度下姓名和三个核心值不被挤压。'],
    watch: ['持续控制卡片文字长度，避免状态变化造成布局跳动。'],
  },
  {
    version: '8.0',
    date: '2026-09-03',
    title: '人物卡片与档案修复',
    summary: '重组候客卡片信息层级，并修复乘客档案开局全部解锁的问题。',
    changes: [
      '核心参数移动到姓名旁，以更大的字号展示。',
      '修复长姓名和能力文字覆盖、截断问题。',
      '乘客档案只记录本机实际遇见过的人物。',
    ],
    experiments: ['验证旧存档、异常档案数据和重复人物不会错误解锁档案。'],
    watch: ['档案仍保存在当前设备，更换浏览器不会同步。'],
  },
];

export const CHANGELOG_EN: ChangelogEntry[] = [
  {
    version: '8.24', date: '2026-09-04', title: 'Temporary cover, no end in sight',
    summary: 'The player is now the elevator operator sent to cover a shift in a strange building. The opening immediately frames an endless survival shift: protect two resources and stay alive for as long as possible.',
    changes: [
      'Reframed the opening from the riders\' perspective to the player\'s: you are the temporary elevator operator, and the setting is a strange building with no final floor.',
      'The three-step briefing is now “Board and place riders → Manage power and agitation → Survive as long as you can,” instead of mixing story, interaction, and secondary rules into one paragraph.',
      'The manual summary and phase labels now share the Temporary Shift / Endless Shift language in both English and Chinese.',
      'Opening Agitation help or the changelog now switches to the theme track. Closing either restores the current floor music, giving pause-and-read screens one consistent audio language.',
      'Added a prominent Start Game button beside the current-formation forecast, so the Agitation screen has an explicit way into play without scrolling.',
      'Completed missing English localization in the Shop manual copy, neighbor/arrival rules in rider details, Agitation help, and accessibility labels.',
      'No rider values, resource resolution, offer weights, or difficulty curves changed in this release.',
    ],
    experiments: [
      'Audited the opening hierarchy: the headline establishes identity and mystery, the paragraph states the survival conditions, and the three-step strip retains only decisions needed before play begins.',
      'Expanded English regression coverage from 1,281 to 1,595 samples by rendering full detail-card rules for all 21 riders. Browser-audited the intro, main screen, manual, Agitation help, rider details, archive, upgrades, and changelog; only the intentional Chinese language-switch label remains Chinese.',
      'Verified English and Chinese localization and the production build. The opening keeps one primary action and adds no extra step before play.',
      'Added music-scene regressions: the intro, Agitation help, and changelog select the theme track; closing them selects the current floor track again, while Shop/death music remain unchanged.',
    ],
    watch: ['Watch whether “strange building” creates curiosity without implying a story ending. Future narrative should emerge through riders and floor events instead of making the opening longer.'],
  },
  {
    version: '8.23', date: '2026-09-04', title: 'Rider cards say only three things',
    summary: 'Candidate cards now share three sections: Self, Green Neighbors, and Red Neighbors. One placement action no longer uses competing terms such as adjacent, cooperate, and prevent, while the instrument rail now shows direct current/cap values.',
    changes: [
      'All 21 riders use one information structure. The header holds arrival coins, power per floor, and non-zero agitation only; self abilities, green-neighbor rewards, and red-neighbor costs each appear once.',
      'Removed conditional restatements such as “Prevented by…”. The universal green arrival bonus appears once beside the green heading; rows below show only targets and special outcomes, while red targets with identical costs share one row.',
      'Coin timing is now explicit: “Each ascent immediately” changes Balance after every floor, while “Own arrival” resolves only when that rider exits. The ambiguous “Income +1/floor” is gone.',
      'Hidden “Agitation +0”. A controlled outcome now says “No agitation”. Candidate guidance, the intro, and the manual consistently use green rewards, red costs, and neighbor stacking.',
      'Phones now show one complete candidate card at a time with three named tabs instead of compressing three full rule cards into narrow columns.',
      'Power and Agitation now use current/cap notation such as 50/60 and 0/6. The Balance card removes shift-total copy and shows only the number of floors to the Shop.',
      'No rider values, offer weights, resolution order, or stacking formulas changed in this release; it is strictly an information-architecture and responsive-layout update.',
    ],
    experiments: [
      'Generated and audited the three-part card for all 21 riders: every card retains a green decision, red targets do not repeat, and compact card data no longer uses competing cooperation/conflict/adjacency wording.',
      'Added focused Officer, Thief, and Musician regressions: Officer control and timer lock occupy one row each, identical Thief coin-loss targets merge, and Musician still states −2 agitation for every neighbor.',
      'Browser-tested English and Chinese at 1440×900 desktop and 390×844 phone sizes. Card bodies had no horizontal or vertical clipping, and the phone page had no horizontal overflow.',
    ],
    watch: ['Watch whether first-time players can place riders using only the three card sections. If details are still opened too often, shorten individual self abilities before adding any fourth card section.'],
  },
  {
    version: '8.22', date: '2026-09-04', title: 'Every neighbor becomes part of the build',
    summary: 'Adjacency abilities now explicitly affect every adjacent rider and stack linearly. After redefining Musician, Nurse, Coach, and Thief, low-occupancy play is no longer the overwhelmingly dominant rational route.',
    changes: [
      'Musician becomes a rare short-term control centerpiece: appearance weight 7→4, arrival fare 8→14, trip 4–8→2–5, and power 1→2 per floor. From a center position it cancels 2 agitation from every adjacent rider; multiple Musicians stack per rider.',
      'Nurse becomes common lightweight control: fare 9→8, appearance weight 7→8, and 1 power per floor. It cancels 1 agitation from every adjacent rider. Both roles fan out, but their rarity, strength, and power cost create distinct choices.',
      'Coach power changes 2→1 while fare 20, trip 3–6, +50% base-fare bonus per adjacent Coach, and +3 coins per neighbor on its own arrival remain. The premium income card is no longer a hidden power trap.',
      'Thief trip changes 3–7→2–6 while retaining +4 coins and +1 agitation per uncontrolled floor. Its risk now sits inside a shorter, more manageable window.',
      'Each normal rider arrival reduces agitation by 1 that floor, capped at 2. Multi-rider turnover gains a predictable reward without allowing unlimited agitation clearing.',
      'Officer copy now explicitly states that it controls every adjacent Thief and locks every adjacent Bomb Carrier timer, with no hidden single-target cap.',
      'Fixed a browser runtime error where floating-point fade undershoot could assign a tiny negative music volume; volume is now always clamped to 0–1.',
    ],
    experiments: [
      'Ran 481,055 iterative games covering arrival relief, one-coin charging, Nurse fan-out, Coach trip/multiplier/power, 46 starting power, long and short Musician cycles, and Thief trip length. Rejected one-coin charging, +100% Coach multipliers, 46 starting power, and the long high-power Musician.',
      'Final independent holdout: 50,950 games. Balanced play averaged floor 45.60 with median 46; 94.52% reached floor 20 and 79.12% reached floor 40. Failures were 11.64% power, 88.24% agitation, and 0.12% Bomb timer. The risk style failed to power 74.88% of the time, so the two resources constrain different builds.',
      'Three-rider frugal play averaged floor 50.65. Its lead over balanced play shrank from roughly 10 floors at baseline to 5.05; synergy averaged 43.58 and risk 25.59. The routes retain different risk curves without low occupancy leading by an entire shop cycle.',
      'All 21 riders received same-seed normal/favor/ban comparisons. Normal acceptance spans 18.0%–62.2%, with no dead-card, auto-pick, indispensability, or trap alert. Musician accepts at 39.9% with −1.26 favored floors; Coach 62.2% with −0.02; Thief 35.8% with −1.52. No rider is removed or added in this release because clearer roles solved the overlap first.',
      'Exhausted all 194,481 center-rider plus three-neighbor formations and ran 4,000 random forecast regressions. Adjacency fan-out, red/green links, arrival relief, power, and agitation all resolved with zero forecast misses.',
    ],
    watch: ['Program policies are not proof of optimal human play. Human testing should check whether a center-position Musician affecting three riders feels sufficiently exciting, whether its power cost still demands planning, and whether the remaining five-floor frugal advantage is healthy safety-style identity or needs further narrowing.'],
  },
  {
    version: '8.21', date: '2026-09-04', title: 'A complete soundtrack for the midnight shift',
    summary: 'The title, floor bands, shop, and failure screen now have dedicated music. Floors 1–120 advance in ten-floor bands; after floor 120, earlier floor tracks shuffle. Music and interaction effects have separate controls.',
    changes: [
      'Integrated 15 player-made tracks: a theme, 12 floor-band tracks, shop music, and failure music. With floors 51–60 supplied, there are no gaps from floor 1 through 120.',
      'Music changes at each ten-floor boundary. Rider placement and ordinary ascents inside the same band never restart the track. The shop and failure screen switch to dedicated music, then restore the appropriate floor band when play resumes.',
      'Floor 121 begins endless shuffle. Each completed track draws from all 12 earlier floor tracks and cannot immediately repeat the one that just ended.',
      'A separate music-note button now toggles background music and remembers the choice. The existing speaker button controls interaction effects only.',
      'Lossless WAV masters remain local under source-audio. Deployment uses loudness-normalized 128 kbps MP3 encodes, reducing roughly 503 MB of masters to about 48 MB of web audio.',
    ],
    experiments: [
      'Automated checks require all 15 web tracks and cover selection boundaries at floors 1, 10, 11, 51, 120, 121, and far beyond 120.',
      'Verified title-to-floor-to-shop-to-failure switching, no restart inside a floor band, independent mute behavior, and no immediate repeat in endless shuffle.',
    ],
    watch: ['Human listening should check perceived loudness, loop seams, and scene transitions. If 48 MB still affects first load, reduce bitrate selectively by track content instead of shortening the music.'],
  },
  {
    version: '8.20', date: '2026-09-04', title: 'Red links become a real cost network',
    summary: 'Conflict is no longer synonymous with agitation. Thirty-five red relationships can drain coins, consume extra power, add agitation, or trade doubled power for doubled fare. After repricing three sustain routes, no rider is an auto-pick or indispensable.',
    changes: [
      'Static red relationships expand from 19 to 35: 12 add 1 agitation per floor, 12 lose 2 coins per floor, 8 consume 1 extra power per floor, 2 double both riders’ power, and 1 doubles both power and arrival fare.',
      'Red links no longer depend on odd/even floors and green links never erase them. Cooperation and conflict resolve independently. Multiple multipliers stack linearly from base: two x2 red links total x3, never exponential x4.',
      'Dashed red links show a fire, power, or coin icon at their midpoint, and candidate cards state the exact cost for each conflict target. Mystery, Shifter, and copied relationships also carry a visible current red-link type.',
      'Power economy is now 50 starting power, 60 capacity, +5 power on shop entry, and 2 coins per additional power. Courier recharges 2 on arrival and appearance weight changes 9→4. Mechanic costs 2, saves 2 per floor, and weight changes 7→3. Each controlled Ghost saves 1→2 power per floor.',
      'An uncontrolled Thief now earns 4 instead of 3 coins per floor, while retaining +1 agitation. Control still changes this to 1 coin per floor, no theft agitation, and +5 arrival fare.',
      'Officer/Bomb cooperation no longer depends on even floors: the timer stays locked while they remain adjacent, then resumes dropping by 1 per floor when separated.',
    ],
    experiments: [
      'Ran more than 285,000 complete simulated games across iterative candidates, screening starting power, free shop power, recharge price, Mechanic net cost, Courier/Mechanic appearance weights, controlled-Ghost strength, and the final Officer timer lock. Rejected shop +6, shop +3, and conditional Mechanic red-line protection.',
      'Final independent holdout: 35,200 games. Balanced play averaged floor 39.60 with median 44; 83.44% reached floor 20 and 58.52% reached floor 40. Failures were 32.72% power, 67.16% agitation, and 0.12% Bomb timer, preserving the two-resource squeeze.',
      'After adding the timer lock, same-seed checks found that favoring Officer added only 1.83 floors and banning it changed +0.10; favoring Bomb changed 0.00 and banning it changed −0.07. The protection pair did not become mandatory.',
      'Normal/favor/ban same-seed comparisons covered all 21 riders with no auto-pick, indispensable, forced-stack, or trap alert. The largest favor gain was Lover at +1.96 floors. Banning Courier cost 3.45 floors and banning Mechanic 3.76, so neither owns sustain alone.',
      'Exhausted all 194,481 center-plus-three-neighbor formations and added regressions for all 35 red pairs, five cost types, doubled red links, and simultaneous green/red links. Multipliers stayed linear; all full games and 4,000 random state transitions had zero next-floor power or agitation forecast misses.',
    ],
    watch: ['Human play should test whether midpoint icons make multiplier costs readable before departure, whether rare sustain cards feel exciting without feeling mandatory, and whether Coach’s high-income, high-power route remains worth choosing.'],
  },
  {
    version: '8.19', date: '2026-09-03', title: 'Companions become a real stackable group route',
    summary: 'Tourists now treat every adjacent rider as a companion, including another Tourist. Income and green links stack per rider with no two-companion rules cap.',
    changes: [
      'Companion income is now “each adjacent rider: +1 coin per floor.” Duplicate professions and other Tourists each count separately.',
      'Removed the two-companion rules cap and x/2 display. A position can still have at most three companions because of the six-position cabin geometry.',
      'Any two adjacent Tourists now draw a green companion link. Every visible companion link matches the live per-floor income on the card.',
      'A companion link represents Tourist floor income only. It does not secretly award the generic arrival cooperation bonus, and Coaches still multiply base fare only.',
    ],
    experiments: [
      'Exhausted all 194,481 combinations of 21 center riders with three neighbors, plus 216 targeted three-neighbor Tourist arrangements. Zero, one, two, and three companions reliably pay zero, one, two, and three coins; Tourist-to-Tourist links and income agree.',
      'Ran 27,000 complete games under the new rule with zero forecast misses. Same-seed before/after tests moved balanced mean survival only from 42.67 to 42.78 floors while mean income rose from 683.86 to 699.35, improving reward without increasing survival.',
      'In a 17,000-game unseen-seed holdout, normal Tourist acceptance was 44.7% and favored acceptance 58.9%. Favoring Tourist changed survival by −0.46 floors, while banning it changed +0.16; no auto-pick, indispensable, or forced-stack alert fired.',
      'A six-Tourist cabin has seven adjacency edges and therefore tops out at 14 companion coins per floor. That matches the per-floor edge scale of six Lovers but lacks their arrival-fare multiplication.',
    ],
    watch: ['Watch whether clearer green links make human players assemble Tourist groups more consistently. If full travel parties become too reliable, tune trip length or base fare before weakening the per-rider stacking rule.'],
  },
  {
    version: '8.18', date: '2026-09-03', title: 'Bomb risk is now a readable countdown',
    summary: 'Every player-facing “fuse” is now a “Bomb timer,” with direct wording for its per-floor change, failure condition, and Officer pause. Gameplay values are unchanged.',
    changes: [
      'Bomb Carrier cards now state the full timer rule: it starts at 3–6, drops by 1 each floor, ends the run if it reaches zero before arrival, and remains safe when it reaches zero on the arrival floor.',
      'Officer cards now say an adjacent Bomb Carrier timer does not drop on even floors. Counsel cards explicitly say they cannot pause a Bomb Carrier timer.',
      'Cabin labels, rider details, failure headings, failure explanations, retry advice, the archive, and Mimic exclusions now use one consistent term.',
      'The English interface uses “Bomb timer” instead of the more metaphorical “Fuse.”',
    ],
    experiments: [
      'Checked candidate cards, cabin labels, the rider-details dialog, Officer/Counsel interactions, failure messaging, and both languages. Every visible state now connects the number directly to safe floors remaining.',
      'Regression coverage still verifies −1 per floor, Officer pauses only on even floors, zero before arrival fails, and zero on the arrival floor is safe. Fare 26, power 1, trip 2–6, and starting timer 3–6 are unchanged.',
    ],
    watch: ['“Bomb timer” is clearer but longer; keep watching very narrow cabin labels to see whether the compact form should become “Bomb 4.”'],
  },
  {
    version: '8.17', date: '2026-09-03', title: 'Stacking rules now match every card',
    summary: 'Audited duplicate riders, fan-out control, cooperation, and conflict across all 21 riders. Red conflicts no longer add hidden agitation on odd floors; public rider values are unchanged.',
    changes: [
      'Each red adjacency conflict now adds 1 agitation only when the next destination floor is even, exactly as the cards state. Odd floors no longer settle hidden conflict agitation.',
      'Green cooperation remains linear per link. Any green link still suppresses that rider’s red-link conflict layer, but never suppresses volatile, intrinsic, uncontrolled-Thief, or other rider-specific agitation.',
      'Mechanics still save 2 power each. Controlled Apparitions, Courier recharge, Tourist profession cap, Coach multipliers, Nurse/Officer fan-out, and Mimic’s three distinct copied fields keep their existing values.',
      'Added a repeatable full-roster stacking audit that records duplicate occupancy, cooperation coverage, exhaustive three-neighbor formations, random-trait distributions, and every core stacking curve.',
    ],
    experiments: [
      'Ran 55,604 complete games and 306,663 controlled stacking and random-trait cases, including all 194,481 combinations of 21 center riders with three neighbors. Power and agitation forecast misses: zero.',
      'For every rider, ran 600 normal, 600 favor, and 600 ban comparisons. Lover reached the highest favored duplicate-cabin rate at 25.2% but changed survival by −0.67 floors. No favored rider stack gained more than +1.09 floors, so no single duplicate strategy dominates.',
      'A six-Lover cabin pays 176 coins when all arrive on the same floor; each Cooperation Contract level adds a linear 28 coins. Three Coaches move Tourist base fare 18→45, while Concierge tips still add only 3 per level and are never multiplied.',
      'Rejected a 9,800-game Mechanic-save-1 variant: balanced floor-40 reach fell from about 69% to 56.5% and aggressive median to floor 10, while banning Mechanic still cost 11.43 floors. It increased power pressure without solving sustain dependence.',
    ],
    watch: ['Mechanic remains the universal sustain anchor, but favoring more copies adds only +1.09 floors, so its simple stack stays. Thief stacking works only with Officer/Counsel support; blind Thief favoring costs −4.50 floors, so keep watching whether the card communicates that condition strongly enough.'],
  },
  {
    version: '8.16', date: '2026-09-03', title: 'Every rider now competes across two resources',
    summary: 'Tourist, Courier, and Coach no longer become ornate traps through power opportunity cost. Sustained savings and short-haul recharge now form two energy routes while agitation and power still squeeze different builds.',
    changes: [
      'Initial power changes from 48 to 42; capacity remains 60. This offsets the new short-haul recharge without changing the 1-power motor, 1 coin per shop recharge, or mandatory-rider rule.',
      'Tourist power changes from 2 to 1 per floor. Base fare 18, 4–7-floor trip, and +1 coin per distinct adjacent profession per floor (max +2) remain unchanged.',
      'Courier recharges 1 power on arrival, capped by capacity. Candidate rules, cabin state, settlement feedback, and next-floor forecast all disclose the recharge.',
      'Coach still costs 2 power per floor, but its trip changes from 4–8 to 3–6 floors. Its +50% adjacent base-fare multiplier and +3 coins per neighbor on its own arrival are unchanged.',
    ],
    experiments: [
      'Ran 221,126 complete simulated games and 86,016 controlled trajectories across all 21 riders, covering cooperation, conflict, power, agitation, and arrival settlement. Rejected variants included valuing hidden Mystery fare at zero, start power 36, Courier recharge 2, Coach power 1, and guaranteed low-power shop cards.',
      'Final unseen-seed holdout: 33,200 games—2,000 for each of four whole-run styles, plus 400 normal, 400 favor, and 400 ban runs for every rider. Next-floor power and agitation forecast misses: zero.',
      'Balanced play averaged floor 41.45 with median 44; 91.55% reached floor 20 and 66.75% reached floor 40. Failures were 26.95% power, 72.90% agitation, and 0.15% fuse, with the dominant threat changing by play style.',
      'Normal selection rates span 17.7%–62.2%, with no universal reject or auto-pick. Favoring Tourist changes +0.20 floors, Courier −0.38, and Coach −0.68. Favoring high-risk Thief costs −3.34 floors, preserving a real downside.',
    ],
    watch: ['Mechanic remains the strongest sustain anchor: 62.2% normal selection and only +0.27 floors when favored further, but −13.95 floors if banned completely. Human play should determine whether this is a healthy build anchor or needs a third sustain route.'],
  },
  {
    version: '8.15', date: '2026-09-03', title: 'Tourist becomes a formation investment',
    summary: 'Tourist is no longer a high-power blank card. Its long-haul value now comes from arranging a diverse set of adjacent professions.',
    changes: [
      'Tourist base fare changes from 22 to 18, trip length from 3–7 to 4–7 floors, while power remains 2 per floor.',
      'Each distinct adjacent non-Tourist profession earns +1 coin per floor, capped at +2. Other Tourists do not count and duplicate professions count once.',
      'Cabin Tourist cards show Companions 0/2–2/2 and current floor income live. Candidate cards receive a travel-grid postcard material and Companion Bonus stamp while honestly remaining Fine rarity.',
      'Companion income settles separately from base fare: Coaches multiply only the base fare, never the banked floor income.',
    ],
    experiments: [
      'Verified 216 directed three-neighbor formations covering empty, duplicate, diverse, Tourist-to-Tourist, arrival-floor, Coach, and green-link settlement boundaries.',
      'A paired 10,000-game before/after run kept balanced median at floor 25 while average income moved only from 322.79 to 324.06, showing no automatic Tourist dominance.',
      'A separate 20,000-game holdout used 367,691 floor settlements with zero power or agitation forecast misses; balanced median remained floor 25.',
      'Also ran 600,000 isolated Storyteller concept trials. The raw two-Child exit condition took a median 15–19 floors and created a soft lock. Adding a 20% per-floor Child-call chance reduced median release to 6 floors and >20-floor locks to 4.72%–5.92%. Storyteller is research only and is not in this release.',
    ],
    watch: ['Observe whether players actively preserve diverse neighbors for Tourist. Storyteller parameters require player approval before entering the live ruleset.'],
  },
  {
    version: '8.14', date: '2026-09-03', title: 'Card headers stop competing for space',
    summary: 'The top of every rider card now strictly separates values from abilities: three short values stay stable while complete conditions remain in the rule area below.',
    changes: [
      'The agitation overview is always a compact “Self +0/+1.” Long cancellation rules for Musician, Nurse, and similar riders appear once in the ability area instead of invading trip and rarity badges.',
      'Desktop headers use a shrinkable identity column and a fixed-content value column. Long English names use a safer size so names, values, material badges, and help controls cannot overlap.',
      'Mobile rarity and value areas gain minimum-width constraints to prevent horizontal overflow while keeping full rules.',
    ],
    experiments: [
      'At 1280×720, browser-checked three Chinese candidate sets and one English set covering long conditions, material badges, and the compact desktop rail. Identity, values, badges, and rule rows no longer overlap visually.',
      'Reviewed desktop, short-screen, phone, and landscape media rules line by line. Full rules, localization, build, and release-history regressions pass. No rider or resource values changed.',
    ],
    watch: ['Keep collecting card screenshots from unusually narrow desktop windows and enlarged system text settings.'],
  },
  {
    version: '8.13', date: '2026-09-03', title: 'This-floor decisions read at a glance',
    summary: 'Candidates, cabin danger, and ten-floor shops now give clearer immediate feedback. This release changes information hierarchy only, not rider or survival values.',
    changes: [
      'A candidate card turns grey and translucent after boarding. Its cabin rider gains a bright gold ring for the current floor; existing riders are never marked as new.',
      'If the current arrangement would exhaust power or reach the agitation cap on the next ascent, the matching forecast number turns red and shakes. Reduced-motion settings keep the static warning color.',
      'Floors 9, 19, 29, and every later pre-shop floor clearly show “Next: Shop” with a highlighted notice instead of an ordinary shift forecast.',
      'Player-facing supply-stop labels are now simply “Shop.” Shop instructions and departure copy are shorter, and the total coin balance is larger at the very top.',
    ],
    experiments: [
      'Added shop-warning regressions for floors 9 and 39 while retaining exact next-floor power and agitation forecast checks.',
      'Full verification still covers targeted rider pairs, random transitions, stacks, links, localization, and release invariants. No balance parameter changed.',
    ],
    watch: ['Watch whether the continuous danger shake is salient without becoming distracting, and whether a dimmed candidate remains clearly undoable across display brightness levels.'],
  },
  {
    version: '8.12', date: '2026-09-03', title: 'Two-resource squeeze',
    summary: 'Agitation is now a fully traceable rider risk, while power again demands active survival planning. Every shift asks how much money to spend on charge, upgrades, and visibly dangerous high-reward riders.',
    changes: [
      'Agitation cap is 6. Removed crowding, shift pressure, empty-car rests, and the hidden high-agitation multiplier. Agitation now comes only from visible rider values, high-risk tags, rider events, and unprotected red links.',
      'Each Nurse or Musician cancels 1 agitation from one adjacent rider per floor. Multiple calmers stack but never go below zero. Any normal arrival reduces total agitation by at most 1 that floor. Calm System now gives cap +1 and immediate −2.',
      'High-risk riders add +1 agitation and +8 arrival coins. They begin ramping at floor 30; each offer set guarantees at least one from floor 40, two from floor 80, and all three from floor 120.',
      'Initial power is 48, capacity is 60, charging costs 1 coin per power, and the reference target is 50. At least one rider is required to ascend, so an empty car cannot bypass rider risk.',
      'Inspector now checks total power every floor: at 4 or less it earns +1 coin; above 4 it adds +1 agitation. High-risk cards receive a copper-red material, flame badge, and cabin marker.',
    ],
    experiments: [
      'Screened initial power 36–60, capacity 48–72, charging price 1–2, agitation caps 6–10, and six combinations of high-risk start, guarantee interval, and ramp speed.',
      'The independent holdout ran 40,000 games and 1,050,768 floor settlements with zero power or agitation forecast misses.',
      'Balanced play averaged floor 38.07 with median 43; 96.92% reached 10, 81.20% reached 20, 57.85% reached 40, and 6.26% reached 60. Of failures, 28.66% were power and 70.89% agitation, establishing a real two-resource squeeze.',
      'Agitation-blind and greedy play both had median floor 9. A conservative two-rider reserve strategy reached median 49, so neither full-cabin nor pure high-income play dominates.',
    ],
    watch: ['Watch whether the floor 30–40 risk ramp feels too slow in human play, and whether +8 coins is enough to tempt players into visible danger when agitation is low.'],
  },
  {
    version: '8.11', date: '2026-09-03', title: 'Mechanic savings reads fully in English',
    summary: 'The final production pass found the Mechanic’s compact power-savings line still in Chinese. It is now localized, and energy rows are included in the all-rider runtime regression.',
    changes: [
      'The Mechanic card now renders its stackable 2-power-per-floor saving fully in English.',
      'Runtime localization coverage for all 21 riders now checks power, income, agitation, and ability rows.',
      'Coach copy remains general and does not name Mystery. No gameplay value or material tier changed.',
    ],
    experiments: [
      'Checked every compact card field for all 21 riders at normal and high agitation, with no Chinese fragments remaining.',
      'Full verification still covers 52,920 targeted pair/position cases, 48,000 random transitions, 60 connection cases, 8 stacking families, and 768 interaction cases.',
    ],
    watch: ['Keep validating new dynamic copy against actual production candidate combinations.'],
  },
  {
    version: '8.10', date: '2026-09-03', title: 'Every English rider rule reads cleanly',
    summary: 'Production visual testing found Chinese fragments in several compact rider rules. All 21 runtime card faces are now fully localized, and those dynamic phrases are covered by regression tests.',
    changes: [
      'Completed compact-rule translations for Thief, Officer, Lawyer, Drunk, Musician, Nurse, Child, Ghost, Exorcist, Coach, Celebrity, Inspector, Bomb Carrier, Mystery, Shifter, and Mimic.',
      'Covered dynamic even-floor agitation, 25% incident, Inspector threshold, bomb fuse, and copied-stat phrases so runtime values cannot leave Chinese fragments behind.',
      'The Coach card still states only its general adjacency rule. It does not call out Mystery as a special case, and hidden-fare settlement is unchanged.',
      'No rider value, material tier, appearance weight, power, agitation, coin, or upgrade effect changed.',
    ],
    experiments: [
      'Added runtime-card localization checks for all 21 riders at both normal and high agitation, covering static rules and value-dependent phrases.',
      'Production visual testing confirmed fully English candidate cards, unclipped card copy, and a single-line primary action.',
      'Full verification still covers 52,920 targeted rider-pair and position cases, 48,000 random state transitions, 60 connection cases, 8 stacking families, and 768 interaction cases.',
    ],
    watch: ['Continue observing reading rhythm for rule-dense riders at narrower desktop widths.'],
  },
  {
    version: '8.9', date: '2026-09-03', title: 'Rider value becomes a physical material',
    summary: 'Candidate cards no longer look like one uniform print run. Appearance rarity and base reward now determine the material tier, while full rules can never be clipped inside a card.',
    changes: [
      'Added four card materials: Standard dark stock, Fine brushed copper, Rare gilt lacquer, and restrained Legendary iridescent obsidian.',
      'Tiers use fixed public values: appearance weight ≤4 or base fare ≥30 is Legendary; weight ≤6 or fare ≥20 is Rare; weight ≤8 or fare ≥14 is Fine; everything else is Standard. Coach is Rare; Shifter and Bomb Carrier are Legendary.',
      'Mystery uses public appearance weight only and never reads its hidden fare, so its material cannot leak the sealed reward.',
      'Desktop candidate cards now size to their complete rules. If three full cards exceed the available height, only the candidate rail scrolls; text is never clipped inside a card.',
      'Added a Coach-and-hidden-fare regression: sealed Mystery base fare still receives the linear 50% multiplier from every adjacent Coach, without adding special-case copy to the card.',
      'No rider, power, agitation, coin, appearance, or upgrade value changed in this release.',
    ],
    experiments: [
      'Added an exact two-Coach Mystery regression: a sealed base fare of 31 resolves to 62 coins, while the original value remains hidden until arrival.',
      'Verified representatives of all four material tiers and that the grading function accepts no hidden Mystery traits.',
      'Full verification still covers 52,920 targeted rider-pair and position cases, 48,000 random state transitions, 60 connection cases, 8 stacking families, and 768 interaction cases.',
    ],
    watch: [
      'Materials communicate appearance rarity or base reward, not unconditional strength. Watch whether players mistake a gilt card for an automatic pick.',
      'The candidate rail scrolls only for combinations of long rules; watch whether it needs a stronger end fade.',
    ],
  },
  {
    version: '8.8', date: '2026-09-03', title: 'Candidate cards keep only useful feedback',
    summary: 'Removed the repeated boarding instruction from every candidate card so rider rules have room to breathe. Contextual states that affect the next action remain visible.',
    changes: [
      'Available, unselected candidate cards no longer show “Drag to a position / click to board.”',
      'Selected, on-board, cabin-full, and immediate-link messages still appear when their state makes them useful.',
      'No rider, power, agitation, coin, difficulty-wave, or upgrade values changed in this release.',
    ],
    experiments: [
      'Checked default, selected, boarded, full-cabin, and link-ready cards in both English and Chinese; only the redundant default instruction is removed.',
      'Full rules verification still covers 52,920 targeted rider-pair and position cases, 48,000 random state transitions, 60 connection cases, 8 stacking families, and 768 interaction cases.',
      'Production and GitHub Pages static builds pass, and the candidate-card render path no longer contains the removed English or Chinese default message.',
    ],
    watch: [
      'Riders with short rules now retain deliberate breathing room at the bottom of the card instead of filling it with generic instructions.',
      'Keep watching whether first-time players can board smoothly from drag feedback and the selected state alone.',
    ],
  },
  {
    version: '8.7', date: '2026-09-03', title: 'The midnight shift goes bilingual',
    summary: 'The complete game now opens in English by default, with one-click access to the full Chinese interface. Gameplay and balance values are unchanged.',
    changes: [
      'English is now the default. A 中文 / EN switch appears in the header; Chinese mode keeps ?lang=zh in the URL and survives refreshes.',
      'English covers the intro, rider cards, cabin states, cooperation and conflict, shift manual, archive, upgrade shop, results, failures, and the full release archive.',
      'The document language defaults to en and changes to zh-CN with the interface, so assistive technology can identify the active language.',
      'No rider, power, agitation, coin, difficulty-wave, or upgrade values changed in this release.',
    ],
    experiments: [
      'Added localization coverage checks across riders, upgrades, rules, dynamic interface copy, and release notes; the default English interface may not contain unapproved Chinese text.',
      'Full rules verification still covers 52,920 targeted rider-pair and position cases, 48,000 random state transitions, 60 connection cases, 8 stacking families, and 768 interaction cases.',
      'Production and GitHub Pages static builds pass. The default static document declares lang=en and retains a direct Chinese entry point.',
    ],
    watch: [
      'Watch the density of long English rules on short 375×667 phones. If needed, shorten wording without hiding decision-critical values.',
      'Future riders and mechanics must ship with both English and Chinese copy so the two rulesets never drift.',
    ],
  },
  {
    version: '8.6', date: '2026-09-03', title: 'Turn the difficulty wall into a survival test',
    summary: 'The pressure wave stays threatening, but players who manage agitation correctly now have a reliable path through it. Mobile controls and tutorial copy are tighter too.',
    changes: [
      'Shift agitation on floors 17–19, 27–29, and later pressure waves drops from +5 to +4 per floor. The +1 rhythm on floors ending 4–6 is unchanged.',
      'Mobile controls remove repeated forecasts, power formulas, and move reminders. Close Doors & Ascend grows from 44 to 74 pixels tall.',
      'A one-line placement hint appears only when a position is required instead of occupying the screen continuously.',
      'The tutorial now uses Lovers as an example for reading a green link, not as the only correct strategy.',
      'Candidate lists gain proper list semantics; invalid accessibility attributes were removed from animated numbers.',
    ],
    experiments: [
      'Fixed the simulator so computer strategies recharge at supply stations and follow the in-game reserve guidance.',
      'Ran 20,000 games and 370,594 floor resolutions with zero power or agitation forecast errors.',
      'The balanced strategy reached floor 10 in 99.92% of runs, floor 20 in 44.58%, floor 30 in 19.60%, and peaked at 100. Ignoring agitation reached floor 20 only 2.66% of the time.',
      'Retested the opening screen, pairing, settlement feedback, and floor-10 shop at 1440×900, 390×844, and 375×667 without page scrolling.',
    ],
    watch: ['The balanced median remains floor 19, matching the hard-fought target; keep watching whether the first pressure wave feels too abrupt to human players.', 'Short phones focus on one candidate card at a time to preserve full rules; watch whether horizontal switching feels natural.'],
  },
  {
    version: '8.5', date: '2026-09-03', title: 'Release history enters the game',
    summary: 'The version number is now an entrance to release history rather than footer decoration.',
    changes: ['Added a clickable version button in the header and footer.', 'Release notes now record gameplay changes, exact values, test scale, findings, and watch items.', 'A release invariant fails verification when the visible version and repository history disagree.'],
    experiments: ['Inherited v8.4’s 17,750 build tests and 1,083,654 floor resolutions.', 'Reran 52,920 targeted rider-pair/position cases and 48,000 random transitions with zero forecast error.', 'Production build and release-entry checks passed.'],
    watch: ['Watch whether players use release notes to understand value changes.', 'Every public release must add its record before the version is raised.'],
  },
  {
    version: '8.4', date: '2026-09-03', title: 'Stacks and builds take shape',
    summary: 'Duplicate riders and multiple links now form real builds while respecting clear physical limits.',
    changes: ['Each green link pays its own arrival bonus; cards show current results such as +3×2.', 'Each red conflict link adds agitation. Any green cooperation link protects that rider from neighbor conflicts.', 'Each Mechanic saves 2 power per floor; controlled Ghosts, Eco Circuit, and Mechanics stack.', 'Lovers and Coaches stack linearly; Nurses, Musicians, Inspectors, and other duplicates resolve independently.'],
    experiments: ['Two rounds totaling 17,750 build comparisons covered Mechanic, Lover, Coach, occult, agitation-control, and mixed strategies.', '1,083,654 floor resolutions produced zero power or agitation forecast errors.', 'All 21 rider types passed double-green, double-red, and green-protection checks, plus 8 special stacking families.'],
    watch: ['Pure stacking builds did not outperform adaptive mixed play, but humans may concentrate resources better than the heuristic.', 'Savings can cancel passenger power only; they never cancel the motor or charge the battery.'],
  },
  {
    version: '8.3', date: '2026-09-03', title: 'Mechanic becomes a steady saver',
    summary: 'Removed the “multiple of three” memory burden so the Mechanic provides predictable value every floor.',
    changes: ['Mechanic changed from periodic activation to savings every floor.', 'Agitation now consistently uses a flame icon instead of a clock-like symbol.', 'The supply shop is denser and keeps Continue Upward within one screen.'],
    experiments: ['Verified a lone Mechanic with low- and high-power rider groups.', 'Checked that savings never cancel motor power or increase the battery.'],
    watch: ['This release still used a shared Mechanic cap; v8.4 made savings stack in response to play feedback.'],
  },
  {
    version: '8.2', date: '2026-09-03', title: 'Clearer agitation and shop',
    summary: 'The unclear patience concept is fully reduced to three core values: coins, power, and agitation.',
    changes: ['Rider cards state exactly when they raise or lower agitation.', 'Ability values include their matching icons and avoid duplicate labels.', 'Shop cards are compressed while preserving the information needed to buy.'],
    experiments: ['Rechecked high-agitation multipliers, Inspector power checks, and shop exit conditions.'],
    watch: ['Keep watching whether long rider abilities wrap on small screens.'],
  },
  {
    version: '8.1', date: '2026-09-03', title: 'On-board stats stay visible',
    summary: 'Players can see the essential values of riders already aboard without relying on memory or hover.',
    changes: ['On-board riders retain coins, power, agitation, and floors remaining.', 'Portraits crop instead of stretch; on-board states and connection lines are stronger.'],
    experiments: ['Verified that names and three core values remain intact across card widths.'],
    watch: ['Keep card copy concise so state changes do not cause layout jumps.'],
  },
  {
    version: '8.0', date: '2026-09-03', title: 'Passenger cards and archive repaired',
    summary: 'Rebuilt the candidate-card hierarchy and fixed the archive starting fully unlocked.',
    changes: ['Moved core stats beside the rider name and increased their type size.', 'Fixed long names and abilities overlapping or being cut off.', 'The archive records only riders actually encountered on this device.'],
    experiments: ['Verified old saves, malformed archive data, and duplicate riders cannot unlock the archive incorrectly.'],
    watch: ['Archive discovery remains local to this device and does not sync across browsers.'],
  },
];
