import type { PassengerKind } from './game-data';

type Line = [string, string];
/** Short in-character lines: said on boarding (sometimes) and on getting off. Flavour only. */
export const QUIPS: Record<PassengerKind, { board: Line[]; arrive: Line[] }> = {
  parcel: { board: [['……', '…']], arrive: [['（纸箱被打开了）', '(The parcel is opened)']] },
  commuter: { board: [['又是这一班。', 'Same lift again.'], ['别叫醒我。', 'Don’t wake me.']], arrive: [['明天见。', 'See you tomorrow.'], ['准点，谢了。', 'On time. Thanks.']] },
  tourist: { board: [['这层的地毯好看！', 'Lovely carpet here!'], ['可以拍一张吗？', 'Mind if I take a photo?']], arrive: [['下一层还会更漂亮吗？', 'Is the next floor prettier?'], ['拍到了！', 'Got the shot!']] },
  courier: { board: [['加急件，快点。', 'Rush parcel, hurry.'], ['签收在上面。', 'Signature’s upstairs.']], arrive: [['送达！', 'Delivered!'], ['电给你留了点。', 'Left you some charge.']] },
  mechanic: { board: [['听，电机在咳嗽。', 'Hear that cough?'], ['别晃，我在听。', 'Keep it steady, I’m listening.']], arrive: [['修好了，别谢。', 'Fixed. Don’t mention it.'], ['老家伙还能撑。', 'The old thing will hold.']] },
  lover: { board: [['你见过一个人吗？', 'Have you seen someone?'], ['是这一层吗？', 'Is it this floor?']], arrive: [['找到了……', 'Found them…'], ['谢谢你等我。', 'Thanks for waiting.']] },
  musician: { board: [['这嗡鸣是降 B 调。', 'That hum is a B-flat.'], ['给我四拍。', 'Give me four beats.']], arrive: [['下一场见。', 'Catch the next set.'], ['谢幕。', 'Curtain.']] },
  thief: { board: [['我什么都没拿。', 'I didn’t take anything.'], ['好表。', 'Nice watch.']], arrive: [['后会有期。', 'Until next time.'], ['口袋检查一下？', 'Check your pockets?']] },
  cop: { board: [['都站好。', 'Everyone stand still.'], ['我盯着呢。', 'I’m watching.']], arrive: [['治安良好。', 'All in order.'], ['收工。', 'Shift over.']] },
  lawyer: { board: [['按规定，请靠边。', 'Per regulation, step aside.'], ['我记下了。', 'Noted.']], arrive: [['合同已履行。', 'Contract fulfilled.'], ['账单稍后寄到。', 'Invoice to follow.']] },
  drunk: { board: [['就是这里……吧？', 'This is it… right?'], ['嗝。', '*hic*']], arrive: [['到家啦！', 'Home at last!'], ['不是这里。算了。', 'Wrong floor. Whatever.']] },
  nurse: { board: [['谁不舒服？', 'Who’s not feeling well?'], ['深呼吸。', 'Deep breaths.']], arrive: [['保重。', 'Take care.'], ['下一床。', 'Next patient.']] },
  child: { board: [['按钮可以我来按吗？', 'Can I press the button?'], ['兔子也要坐。', 'Bunny rides too.']], arrive: [['再坐一次！', 'Again!'], ['谢谢叔叔！', 'Thank you, mister!']] },
  ghost: { board: [['……', '…'], ['好冷啊。', 'So cold.']], arrive: [['我想起来了。', 'I remember now.'], ['晚安。', 'Goodnight.']] },
  exorcist: { board: [['有东西跟着我们。', 'Something follows us.'], ['别怕。', 'Don’t be afraid.']], arrive: [['它该下车了。', 'Its stop, too.'], ['愿你安宁。', 'Rest easy.']] },
  coach: { board: [['打起精神！', 'Look alive!'], ['你可以的！', 'You’ve got this!']], arrive: [['干得漂亮！', 'Nice work!'], ['下一组！', 'Next set!']] },
  celebrity: { board: [['别拍照。', 'No photos.'], ['只要一个人陪我。', 'Just one of you, please.']], arrive: [['亲一个。', 'Kisses.'], ['别告诉别人。', 'Don’t tell anyone.']] },
  inspector: { board: [['保持安静。', 'Keep it quiet.'], ['我在记录。', 'I’m taking notes.']], arrive: [['合格。', 'Passed.'], ['盖章。', 'Stamped.']] },
  bomb: { board: [['别碰这个箱子！', 'Don’t touch the case!'], ['快，快，快。', 'Faster, faster.']], arrive: [['赶上了……', 'Made it…'], ['呼——', 'Phew—']] },
  mystery: { board: [['你没见过我。', 'You never saw me.'], ['信封别拆。', 'Don’t open the envelope.']], arrive: [['车费在这。', 'Here’s your fare.'], ['我们两清了。', 'We’re square.']] },
  shifter: { board: [['今晚我是谁？', 'Who am I tonight?'], ['换张脸。', 'New face.']], arrive: [['下次认不出我。', 'You won’t know me next time.'], ['再会。', 'Adieu.']] },
  mimic: { board: [['你说什么，我说什么。', 'I say what you say.'], ['学得像吗？', 'Good likeness?']], arrive: [['谢谢——谢谢。', 'Thanks—thanks.'], ['我也到了。', 'My stop too.']] },
  operator: { board: [['我来暖暖电机。', 'Let me warm the motor.'], ['四十年了。', 'Forty years.']], arrive: [['交给你了，孩子。', 'She’s yours now, kid.'], ['扳手留给你。', 'Keep the wrench.']] },
  matchmaker: { board: [['红线牵好了吗？', 'Threads tied?'], ['有缘人在车上。', 'Someone here is meant for someone.']], arrive: [['成了。', 'A match.'], ['红绳收好。', 'Keep the red string.']] },
  don: { board: [['别紧张。', 'Relax.'], ['记我账上。', 'Put it on my tab.']], arrive: [['我欠你一次。', 'I owe you one.'], ['怀表是你的了。', 'The watch is yours.']] },
  matron: { board: [['都安静。', 'Quiet, all of you.'], ['查房。', 'Rounds.']], arrive: [['记录交给你。', 'Here’s the log.'], ['今晚平安。', 'A calm night.']] },
  nightingale: { board: [['还有人醒着吗？', 'Anyone still awake?'], ['来一首？', 'A song?']], arrive: [['晚安，亲爱的。', 'Goodnight, darling.'], ['唱片送你。', 'The record’s yours.']] },
  medium: { board: [['他们都在这里。', 'They’re all here.'], ['请给他们让座。', 'Make room for them.']], arrive: [['铃给你。', 'Take the bell.'], ['他们安心了。', 'They’re at peace.']] },
  tycoon: { board: [['慢一点，好思考。', 'Slowly. I’m thinking.'], ['这台老电梯不错。', 'Good old lift.']], arrive: [['尾款。', 'The balance.'], ['股票拿好。', 'Hold the shares.']] },
  stranger: { board: [['十三号房。', 'Room thirteen.'], ['这不是我的东西。', 'This isn’t mine.']], arrive: [['给你的。', 'For you.'], ['别找我。', 'Don’t look for me.']] },
  nightoperator: { board: [['灯我关了。', 'I turned the lights off.'], ['夜班开始了。', 'The night shift starts.']], arrive: [['配电箱给你修好了。', 'Fixed your fuse box.'], ['天亮前别开灯。', 'No lights till dawn.']] },
  severer: { board: [['线太多了。', 'Too many threads.'], ['吵吧，吵得好。', 'Fight. Good.']], arrive: [['都剪干净了。', 'All cut.'], ['缘分到此为止。', 'That’s where fate ends.']] },
  kingpin: { board: [['这层我包了。', 'This floor is mine.'], ['钱放我这儿。', 'Leave the money with me.']], arrive: [['账清了。', 'We’re square.'], ['别让我再找你。', 'Don’t make me find you.']] },
  coldmatron: { board: [['伸出手来。', 'Hold out your arm.'], ['一针就安静了。', 'One shot and it’s quiet.']], arrive: [['病历给你。', 'Here’s the chart.'], ['今晚没人再哭。', 'No one cries tonight.']] },
  banshee: { board: [['有人要走了。', 'Someone is leaving.'], ['听我唱。', 'Listen to me sing.']], arrive: [['歌唱完了。', 'The song is over.'], ['替我记住他们。', 'Remember them for me.']] },
  necromancer: { board: [['让他们都上来。', 'Let them all on.'], ['黑夜里的人是我的。', 'The night people are mine.']], arrive: [['收成不错。', 'A good harvest.'], ['他们会跟我走。', 'They’ll follow me.']] },
  highroller: { board: [['押上全部。', 'All in.'], ['安静点，我在算。', 'Quiet, I’m counting.']], arrive: [['赢了！', 'Winner!'], ['庄家总是赢。', 'The house always wins.']] },
  otherthirteen: { board: [['我才是十三号。', 'I’m the real Thirteen.'], ['镜子里见。', 'See you in the mirror.']], arrive: [['轮到你了。', 'Your turn.'], ['别回头。', 'Don’t look back.']] },
  overtimer: { board: [['再坐一层。', 'One more floor.'], ['加班费照算。', 'Overtime counts.']], arrive: [['……还不能下。', '…Not yet.'], ['明天还来。', 'Back tomorrow.']] },
  voyeur: { board: [['笑一个。', 'Say cheese.'], ['别动，就这样。', 'Hold still, just like that.']], arrive: [['底片满了。', 'Film’s full.'], ['会登报的。', 'You’ll be in the papers.']] },
  smuggler: { board: [['别碰箱子。', 'Hands off the box.'], ['没人检查吧？', 'No inspectors, right?']], arrive: [['货到了。', 'Delivered.'], ['你什么都没看见。', 'You saw nothing.']] },
  scrapper: { board: [['这颗螺丝不错。', 'Nice bolt.'], ['借一根线。', 'Borrowing a wire.']], arrive: [['零件归我了。', 'Parts are mine.'], ['它还能跑，暂时。', 'Still runs. For now.']] },
  exlover: { board: [['别让我坐他旁边。', 'Don’t seat me next to him.'], ['又是你。', 'You again.']], arrive: [['再也不见。', 'Never again.'], ['这次是真的结束了。', 'This time it’s over.']] },
  noisemaker: { board: [['太安静了。', 'Too quiet.'], ['大声点！', 'Louder!']], arrive: [['安可！', 'Encore!'], ['耳朵还好吗？', 'Ears okay?']] },
  robber: { board: [['钱包。', 'Wallet.'], ['别出声。', 'Not a sound.']], arrive: [['谢了。', 'Thanks.'], ['下次还来。', 'See you next time.']] },
  crookedcop: { board: [['一人三块。', 'Three each.'], ['我罩着你们。', 'I’ve got you covered.']], arrive: [['生意不错。', 'Good business.'], ['收工，结账。', 'Shift over. Pay up.']] },
  shyster: { board: [['我闻到了官司。', 'I smell a lawsuit.'], ['请继续吵。', 'Please, keep arguing.']], arrive: [['胜诉。', 'Case won.'], ['账单寄到了。', 'The bill is in the mail.']] },
  brawler: { board: [['看什么看？', 'What are you looking at?'], ['来啊！', 'Come on!']], arrive: [['算你们走运。', 'Lucky for you.'], ['下次再打。', 'Next time.']] },
  pusher: { board: [['来一颗？', 'Want one?'], ['马上就不疼了。', 'It’ll stop hurting soon.']], arrive: [['下次再来找我。', 'Come find me again.'], ['别想我太多。', 'Don’t miss me too much.']] },
  creepychild: { board: [['兔子不喜欢你。', 'Bunny doesn’t like you.'], ['……', '…']], arrive: [['终于只剩我了。', 'Finally, just me.'], ['再见。永远。', 'Bye. Forever.']] },
  wraith: { board: [['你欠我的。', 'You owe me.'], ['好冷……', 'So cold…']], arrive: [['还没完。', 'It isn’t over.'], ['我会回来。', 'I’ll be back.']] },
  summoner: { board: [['听，有人要上车。', 'Listen, someone wants to ride.'], ['铃响了。', 'The bell rings.']], arrive: [['它们会跟着我走。', 'They’ll follow me.'], ['车费已付。', 'Fares paid.']] },
  taskmaster: { board: [['快一点！', 'Faster!'], ['谁在偷懒？', 'Who’s slacking?']], arrive: [['还不够。', 'Not enough.'], ['明天加倍。', 'Double tomorrow.']] },
  scandal: { board: [['拍吧，拍大一点。', 'Go on, bigger.'], ['今晚上头条。', 'Tonight’s headline.']], arrive: [['明天见报。', 'See you in the papers.'], ['别让警察看见。', 'Don’t let the police see.']] },
  grafter: { board: [['检查费。', 'Inspection fee.'], ['合格——交钱。', 'Passed. Pay up.']], arrive: [['手续齐了。', 'Paperwork’s done.'], ['合作愉快。', 'A pleasure doing business.']] },
  madbomber: { board: [['它在唱歌！', 'It’s singing!'], ['别让它停下。', 'Don’t let it stop.']], arrive: [['还没响……可惜。', 'Didn’t go off… pity.'], ['下一颗更大。', 'The next one is bigger.']] },
};

export function quip(kind: PassengerKind, moment: 'board' | 'arrive', zh: boolean, rng: () => number = Math.random) {
  const lines = QUIPS[kind]?.[moment]; if (!lines?.length) return '';
  const line = lines[Math.floor(rng() * lines.length)];
  return zh ? line[0] : line[1];
}
