import type { ChangelogEntry } from './changelog';

export const V10_ZH: ChangelogEntry = {
  version: '10.0.0', date: '2026-09-25', title: '符号链接：绿线红线由符号决定，一眼看懂，组合更多',
  summary: '以前的绿线红线是一张手写名单：每人只喜欢一两个特定人物、讨厌零到两个，要靠背；统计显示真人型玩家 78% 的楼层车里一条绿线都没有，链接几乎不起作用。v10 把名单换成符号：每位乘客两个符号，相同符号挨着坐是绿线，相反符号是红线，每种符号的绿线有自己的效果。人物能力（警察管住小偷、恋人配对、护士、教练……）不变。规则和数值都是模拟实验里一轮轮试出来的，下面列出了每一步。',
  changes: [
    '六个符号，三组相反：🎉热闹↔🤫安静、📋秩序↔🎲江湖、🏠人间↔👻幽冥。每位乘客两个（不会是相反的一对），显示在卡片和座位的名字旁，悬停可看规则。暗黑版多是热闹、江湖、幽冥，和白天的乘客容易起冲突。',
    '绿线和红线：邻座有相同符号＝绿线，有相反符号＝红线；同一对邻座的相同和相反符号一对一抵消（一个相同、一个相反＝没有线）。',
    '每种符号只要车里有一条它的绿线，每层就生效一次：🎉 +2 币；🎲 +3 币但 +1 躁动；📋 −1 躁动；🏠 −1 躁动；🤫 省 1 电；👻 省 1 电（省电不超过乘客自己的耗电）。同一符号连成一排再加 1 级、四人方块加 2 级、满车加 4 级。',
    '红线只有一种：每条每层 +1 躁动。原来的“红线耗电”“红线扣钱”“耗电翻倍”“赌局红线”都取消了。',
    '卡片不再列“协作 / 冲突”的名单，只留人物能力带来的搭档（如警察—小偷）。人物详情里新增“符号”一栏，写清每个符号的绿线效果和相反符号。',
    '新面板“这一层的链接”：列出生效的符号、等级、效果和红线数；连线上显示共同的符号，红线显示 🔥+1。说明书新增“符号与链接”，躁动说明和邻座说明也改写了。',
    '车费：白天乘客 ×0.6（链接成了主要收入）；暗黑版为 v9.22 的 80%（劫匪保留 14、召魂人 6）；幽灵 1；神秘人四种身份 6 / 16 / 20 / 6。',
    '能力与信物：默契契约和红绳改为“🎉🎲 每级绿线每层 +2 币”（契约 2 级 +3）；绝缘衬层只剩“每条红线每层 +1 币冲突小费（最多 3）”。',
    '发牌：和主牌一起发的搭档一定和他真的有链接（能力搭档，或不抵消的符号关系），也会发和他有共同符号的人；“冲突包”发的是和他有相反符号的人。',
  ],
  experiments: [
    '改之前的统计（每种机器人 100 局）：真人型每层 0.26 条绿线、78% 的楼层没有绿线；均衡型 0.75 条、53%。',
    '规则是按实验一步步定的（每步 150 局 × 3–4 种机器人）：',
    '① 每条绿线每层 +1 币、红线 +1 躁动：真人型机器人 15 层就被躁动压垮（一对邻座 58% 的机会有相反符号），熟练型离开 70 层商店时还有 317 币。',
    '② 加入“相同减相反”：红线机会降到 42%，真人型到 63–68 层；但钱仍然太多（617 币）。',
    '③ 每种符号的绿线各管一种资源：钱不再只从链接里涨，但新手从 34 层变成 68 层——按每条线计的奖励叠得太多，所有人都变容易了。',
    '④ 改成“每种符号有一条绿线就生效一次，形状加级”：新手回到 59 层、钱降下来；再把车费降到 ×0.6：新手 29–32 层、熟练型 87 层。',
    '红线 +2 躁动和 +1 几乎没有区别，保留 +1（更简单）。',
    '单符号流派（每种各 100 局，只偏爱带这个符号的乘客）：六种都在 87–88 层；每个流派最常生效的都是自己的符号（热闹 64%、安静 65%、人间 63%、秩序 53%、江湖 38%、幽冥 37%）。',
    '18 种符号流派（6 种单符号 + 12 种双符号，每种 60 局，最终数值）：都在 86–88 层。单符号流派差别明显，自己的符号生效率最高（热闹 64%、安静 66%、人间 62%、秩序 58%）；含江湖或幽冥的双符号流派和普通打法差别不大（自己的符号只有 21–30%）。',
    '最终验收 4200 局：五种流派 86–87 层（98.9%）；均衡型中位 87 层（p10–p90 80–94）；抵达 100 层 0.5%；熟练型死因 断电 43.6% / 躁动 55.5% / 炸弹 0.9%；新手 32 层；真人型 76 层；均衡型上车率全部在 16–64%。躁动来源第一是红线（29.9%），这是站位能控制的部分。',
    '链接现在的存在感（每种 150 局）：真人型每层 4.6 条绿线、只有 4% 的楼层没有；均衡型 3.0 条、19%。离开 70 层商店时剩余金币：真人型 29（v9.22 是 81），均衡型 77（64）。',
    '组合数：6 个座位 × 43 种人物（加空座）约 72.6 亿种坐法；只看符号，每个座位 14 种状态（空、无符号、12 种符号组合），共 7,529,536 种符号布局，产生 6,593 种不同的链接结果、33,598 种“哪些符号几级 + 几条红线”的组合。',
    '调人物的过程：×0.6 后有 4–5 位暗黑版上车率跌破 15%（监工、狂徒、劫匪、疯炸客……），暗黑版改为 v9.22 的 80%；之后劫匪、召魂人、神秘人在边缘，劫匪 14、召魂人 6、神秘人身份车费 ×0.8；幽灵两个符号都省电、自己又不耗电，上车率 67.6%，车费降到 1 后 64%。',
    '浏览器试玩（中文窄屏、英文手机）：卡片和座位的符号、连线上的符号、“这一层的链接”面板、人物详情的符号栏、躁动说明都看过；英文模式从 1 层自动跑到 66 层，界面里没有中文。试玩中把 ⚖️ 换成 📋（灰色的天平在深色座位上看不清，🚦 缩小后是一条细线）；把座位上的符号放大；人物详情里重复的符号说明删掉。',
    'verify：verify-conflicts 改写成符号规则的测试（每人两个不相反的符号、每个符号至少 4 位白天乘客、抵消、单次生效、形状等级、六种效果、省电上限、契约和红绳、复制人、神秘人、百变人）；其他测试里写死的旧车费改成按数据计算。全部通过。',
  ],
  watch: [
    '真人型机器人仍到 76 层，离“普通玩家 60 层左右”还远。它现在很会排座（每层 4.6 条绿线），真实玩家可能没这么熟练；需要真人试玩确认。',
    '“不宽裕”两项验收仍不通过（62.4%，离店中位 26 币），来自熟练型机器人 20–60 层的富余。',
    '江湖和幽冥更难搭（流派实验里只有 37–38% 的楼层生效），暗黑版的上车率贴着 15–20%。',
    '符号用表情显示，不同系统的表情样式不同；卡片上的符号在手机上是 22px。',
  ],
};

export const V10_EN: ChangelogEntry = {
  version: '10.0.0', date: '2026-09-25', title: 'Symbol links: green and red links come from symbols, readable at a glance, with far more combinations',
  summary: 'Green and red links used to come from a hand-written list: each rider liked one or two specific riders and avoided up to two, and you had to memorise it. On 78% of the human-like bot’s floors there was not a single green link; links barely mattered. v10 replaces the list with symbols. Every rider carries two symbols; neighbours sharing a symbol get a green link, neighbours with opposite symbols a red one, and each symbol’s green link has its own effect. Rider abilities (the Officer holding a Thief, the Lovers’ pairing, the Nurse, the Coach…) are unchanged. The rules and numbers were found step by step in simulation; every step is listed below.',
  changes: [
    'Six symbols in three opposite pairs: 🎉 Lively↔🤫 Quiet, 📋 Order↔🎲 Street, 🏠 Hearth↔👻 Spirit. Every rider carries two (never an opposite pair), shown beside the name on cards and seats with the rule in the tooltip. Dark riders are mostly Lively, Street and Spirit, so they clash easily with daytime riders.',
    'Green and red links: neighbours who share a symbol = green link; neighbours with opposite symbols = red link. A pair’s matches and clashes cancel one for one: one match and one clash draw no line.',
    'Each symbol with at least one green link in the cabin works once a floor, all effects per floor:',
    '• 🎉: +2 coins.',
    '• 🎲: +3 coins, but +1 agitation.',
    '• 📋 and 🏠: −1 agitation each.',
    '• 🤫 and 👻: 1 power saved each (never more than the riders use).',
    'Shapes raise a symbol’s level: a row of one symbol adds 1, a 2×2 square 2, a full cabin 4.',
    'Red links are one kind only: +1 agitation per red link per floor. Red links that cost power or coins, doubled power and gamble links are gone.',
    'Cards no longer list named partners and opponents; only ability partners remain (e.g. Officer–Thief). The rider sheet has a new “Symbols” block with each symbol’s green-link effect and its opposite.',
    'New “Links this floor” panel: the active symbols, their levels and effects, and the red-link count. Link lines show the shared symbols, and red ones show 🔥+1. The manual has a new “Symbols and links” section, and the agitation and neighbour notes were rewritten.',
    'Fares:',
    '• Daytime riders ×0.6, since links became the main income.',
    '• Dark riders 80% of v9.22 (the Robber keeps 14, the Summoner 6).',
    '• Ghost 1; the Mystery’s four identities 6 / 16 / 20 / 6.',
    'Abilities and keepsakes:',
    '• The Cooperation Pact and the Red String now give “🎉🎲 +2 coins per green-link level per floor” (Pact level 2: +3).',
    '• Insulation keeps only its conflict tip: +1 coin per red link per floor, at most 3.',
    'Offers: the partner dealt with an anchor card always really links with him (an ability partner, or a symbol relation that does not cancel). Riders who share a symbol with him are dealt too. A tense packet deals someone with an opposite symbol.',
  ],
  experiments: [
    'Before the change (100 runs per bot): the human-like bot averaged 0.26 green links a floor with none on 78% of floors; the balanced bot 0.75 and 53%.',
    'The rules were settled step by step (150 runs × 3–4 bots each):',
    '• Step 1, every green link +1 coin a floor and red links +1 agitation. The human-like bot broke down by 15F: a random pair of neighbours has a 58% chance of an opposite symbol. The skilled bot left the 70F shop with 317 coins.',
    '• Step 2, “matches minus opposites”. The red chance fell to 42% and the human-like bot reached 63–68F, but money was still far too plentiful (617 coins).',
    '• Step 3, each symbol’s green link paying in its own resource. Money no longer grew from links alone, but the novice went from 34F to 68F: per-link rewards stacked up and made the game easier for everyone.',
    '• Step 4, “a symbol with any green link works once, shapes add levels”. The novice fell back to 59F and money came down. Fares ×0.6 then gave novice 29–32F and skilled 87F.',
    'Red links at +2 agitation behaved almost the same as +1, so +1 stays (simpler).',
    'Single-symbol styles, 100 runs each, favouring only riders with that symbol:',
    '• All six end at 87–88F.',
    '• In each style its own symbol is the one most often active: Lively 64%, Quiet 65%, Hearth 63%, Order 53%, Street 38%, Spirit 37%.',
    'Eighteen symbol styles (6 single-symbol, 12 two-symbol; 60 runs each, final numbers):',
    '• All end at 86–88F.',
    '• The single-symbol styles clearly differ: their own symbol is the most active one (Lively 64%, Quiet 66%, Hearth 62%, Order 58%).',
    '• Two-symbol styles with Street or Spirit barely differ from ordinary play (their own symbols active only 21–30% of floors).',
    'Final acceptance, 4,200 runs:',
    '• Five styles at 86–87F (98.9%).',
    '• Balanced median 87F (p10–p90 80–94); 100F reached in 0.5% of runs.',
    '• Skilled endings: 43.6% power, 55.5% agitation, 0.9% bomb.',
    '• Novice 32F, human-like 76F.',
    '• Every balanced boarding rate is within 16–64%.',
    '• Red links are the largest agitation source (29.9%), the part a player controls by seating.',
    'How much links matter now, 150 runs per bot:',
    '• Human-like: 4.6 green links a floor, with none on only 4% of floors.',
    '• Balanced: 3.0 a floor, none on 19%.',
    '• Coins left after the 70F shop: human-like 29 (v9.22: 81), balanced 77 (v9.22: 64).',
    'Combinations:',
    '• 6 seats × 43 rider kinds (plus empty) give about 7.26 billion seatings.',
    '• By symbols alone, each seat has 14 states (empty, no symbol, or one of 12 symbol pairs): 7,529,536 symbol layouts.',
    '• These produce 6,593 distinct link results and 33,598 distinct “which symbols at which level + how many red links” patterns.',
    'Rider tuning:',
    '• After ×0.6, four or five dark riders dropped under 15% boarding (Taskmaster, Brawler, Robber, Mad Bomber…). Dark fares went to 80% of v9.22.',
    '• The Robber, Summoner and Mystery then sat at the edge: Robber 14, Summoner 6, Mystery identity fares ×0.8.',
    '• The Ghost, whose two symbols both save power and who uses none himself, was at 67.6%; fare 1 brings him to 64%.',
    'Browser playtest (Chinese on a narrow window, English on a phone):',
    '• Checked: symbols on cards and seats, symbols on link lines, the “Links this floor” panel, the sheet’s Symbols block and the agitation notes.',
    '• An English autopilot run from 1F to 66F showed no Chinese in the interface.',
    '• Fixed along the way: ⚖️ became 📋 (the grey scales vanished on dark seats, and 🚦 shrank to a thin bar); seat symbols were enlarged; the repeated symbol lines on the rider sheet were removed.',
    'verify: verify-conflicts is rewritten as the symbol rulebook. It tests:',
    '• two non-opposite symbols per rider, and each symbol on at least four day riders;',
    '• canceling, once-per-symbol activation and shape levels;',
    '• the six effects, the power cap, the Pact and the Red String;',
    '• the Mimic, the Mystery and the Shifter.',
    'Old hard-coded fares in other tests are now computed from the data. Everything passes.',
  ],
  watch: [
    'The human-like bot still reaches 76F, far from “a normal player ends around 60F”. It now seats riders very well (4.6 green links a floor), and real players may not; this needs human playtests.',
    'Both “not affluent” checks still fail (62.4%; median 26 coins left after a shop), from the skilled bot’s spare coins at 20–60F.',
    'Street and Spirit are harder to build around (active on only 37–38% of floors in the style test); dark riders’ boarding sits at 15–20%.',
    'Symbols are emoji, which look different on each system; on phones the card symbols are 22px.',
  ],
};

export const V101_ZH: ChangelogEntry = {
  version: '10.1.0', date: '2026-09-25', title: '自己画的符号图标，江湖和幽冥也能搭',
  summary: '表情符号太幼稚，换成自己画的线稿图标，和电梯的装饰风格一致。同时修了两个不好搭的符号：专门去凑江湖和幽冥，也只有 36–40% 的楼层能连上，别的符号有 56–66%。',
  changes: [
    '六个符号图标都重画成金色线稿风格，每个符号一种颜色：热闹是放射的星芒，安静是闭着的眼睛，秩序是装饰艺术风的立柱，江湖是假面，人间是亮着窗的小屋，幽冥是一弯新月。卡片、座位、连线、“这一层的链接”面板都用新图标；文字里一律写符号名称，不再夹表情。',
    '说明书“符号与链接”一节开头加了六个图标的图例（图标、名称、效果），下面的正文不再重复列效果。',
    '江湖：绿线从“+3 币、+1 躁动”改为“+2 币”。带江湖的乘客（小偷、醉汉、炸弹客……）本身就有风险，符号不必再扣躁动。',
    '快递员和维修工的符号从“江湖·人间”改为“江湖·幽冥”。幽冥原来是白天最少见的符号，它的反面人间又在最常见的乘客身上。',
    '监工车费 8→9。',
  ],
  experiments: [
    '问题：专门偏爱某个符号的机器人，自己的符号生效的楼层比例：热闹 64%、安静 66%、人间 62%、秩序 58%，江湖只有 36%，幽冥 40%。',
    '江湖（每种 60 局 × 6 种单符号流派 + 100 局 × 4 种机器人）：去掉 +1 躁动后 36%→52%；改成“+4 币、+1 躁动”仍只有 37%（机器人把 1 点躁动算作约 3 币，净收益几乎为零）。',
    '幽冥：改效果都没用。省电不设上限 42%，深渊发作 −10% 42%，两者都加 43%；发作 −10% 还让合作型到 100 层的比例升到 7–9%。问题出在供给，不在效果。',
    '试过把儿童改成“热闹·幽冥”（幽冥 44–45%），但护士（人间·秩序）要照顾儿童，人间和幽冥相反，这对故事搭档会变成红线，放弃。改成快递员和维修工（没有依赖人间的能力搭档）：六个符号都到 52–66%（江湖 56%、幽冥 56%）。',
    '江湖 +3 币时离开 70 层商店的钱：真人型 102、均衡型 124、合作型 128；+2 币时 87、87、107（v9.22 是 81），江湖生效率 54% 几乎不变，所以取 +2。',
    '最终数值下的单符号流派：热闹 60%、安静 68%、秩序 56%、江湖 54%、人间 52%、幽冥 55%，都在 87–89 层；新手 31 层，真人型 81 层，均衡型 88 层，到 100 层 0–1%。',
    '最终验收 4200 局：五种流派 87–88 层（98.9%）；均衡型中位 88 层（p10–p90 80–95）；抵达 100 层 0.8%；熟练型死因 断电 47.0% / 躁动 51.9% / 炸弹 1.0%；新手 31 层；真人型 81 层。上车率只有监工 14.7% 越界，车费 8→9 后 300 局复查 19.1%，其余都在 15–63%。“不宽裕”：68.0%、离店中位 34 币。',
    '浏览器检查（中文窄屏、英文手机）：六个图标在卡片、座位、连线和面板上都清楚；一个四人“安静方块”在面板上显示为“安静 · 方块 ×3，省 3 电”；说明书图例正常。verify 全部通过。',
  ],
  watch: [
    '钱比 v10.0 多（70 层离店从 29/77 回到 87/87），“不宽裕”两项验收仍不通过。',
    '真人型机器人到 79–81 层，普通玩家 60 层的目标还没解决。',
    '形状（一排、方块、满车）只在面板里写出来，车厢里还没有高亮。',
  ],
};

export const V101_EN: ChangelogEntry = {
  version: '10.1.0', date: '2026-09-25', title: 'Hand-drawn symbol icons, and Street and Spirit worth building around',
  summary: 'The emoji looked childish, so the symbols are now hand-drawn line icons in the cabin’s style. This release also fixes the two symbols that were hard to build around: a bot favouring Street or Spirit got its own symbol active on only 36–40% of floors, against 56–66% for the others.',
  changes: [
    'All six symbol icons are redrawn as gold line art, one colour per symbol:',
    '• Lively: a starburst. Quiet: a closed eye. Order: an Art Deco column.',
    '• Street: a masquerade mask. Hearth: a house with a lit window. Spirit: a crescent moon.',
    'Cards, seats, link lines and the “Links this floor” panel use the new icons; text always names the symbol instead of showing an emoji.',
    'The manual’s “Symbols and links” section opens with a legend of the six icons (icon, name, effect), and the text below no longer repeats the effects.',
    'Street: its green link now gives +2 coins, instead of +3 coins and +1 agitation. Street riders (Thief, Drunk, Bomb Carrier…) already carry their own risk, so the symbol no longer adds agitation.',
    'The Courier and the Mechanic are now Street·Spirit instead of Street·Hearth. Spirit was the scarcest day symbol, and its opposite, Hearth, sat on the most common riders.',
    'Taskmaster fare 8→9.',
  ],
  experiments: [
    'The problem: a bot favouring one symbol got its own symbol active on Lively 64%, Quiet 66%, Hearth 62% and Order 58% of floors, but Street only 36% and Spirit 40%.',
    'Street (60 runs × six single-symbol styles, 100 runs × four bots):',
    '• Without the +1 agitation it went from 36% to 52%.',
    '• “+4 coins, +1 agitation” stayed at 37%: bots price one agitation at about 3 coins, so the net was close to nothing.',
    'Spirit: changing its effect did not help.',
    '• Uncapped power saving: 42%. Abyss outbursts −10%: 42%. Both: 43%.',
    '• The outburst cut also raised the cooperation bot’s 100F rate to 7–9%.',
    '• The problem was supply, not effect.',
    'Moving Spirit onto riders:',
    '• Making the Child Lively·Spirit (44–45%) was rejected: the Nurse (Hearth·Order) cares for the Child, and Hearth opposes Spirit, so the story pair would become a red link.',
    '• The Courier and the Mechanic have no Hearth-based ability partners. With them moved, all six symbols reach 52–66% (Street 56%, Spirit 56%).',
    'Street coins, measured as coins left after the 70F shop (human-like / balanced / cooperation):',
    '• At +3: 102 / 124 / 128.',
    '• At +2: 87 / 87 / 107 (v9.22: 81). Street activation stays 54%, so +2 it is.',
    'Single-symbol styles at the final values:',
    '• Own symbol active: Lively 60%, Quiet 68%, Order 56%, Street 54%, Hearth 52%, Spirit 55%; all end at 87–89F.',
    '• Novice 31F, human-like 81F, balanced 88F; 100F reached in 0–1% of runs.',
    'Final acceptance, 4,200 runs:',
    '• Five styles at 87–88F (98.9%); balanced median 88F (p10–p90 80–95); 100F reached in 0.8% of runs.',
    '• Skilled endings: 47.0% power, 51.9% agitation, 1.0% bomb. Novice 31F, human-like 81F.',
    '• Only the Taskmaster fell outside the boarding band (14.7%). A 300-run recheck after his fare went 8→9 gives 19.1%; everyone else is within 15–63%.',
    '• “Not affluent”: 68.0%, with a median of 34 coins left after a shop.',
    'Browser check (Chinese on a narrow window, English on a phone):',
    '• All six icons are clear on cards, seats, link lines and the panel.',
    '• A four-rider Quiet square shows as “Quiet · square ×3, −3 power”.',
    '• The manual legend renders.',
    'verify passes.',
  ],
  watch: [
    'There is more money than in v10.0: coins left after the 70F shop rose from 29 / 77 to 87 / 87 (human-like / balanced). Both “not affluent” checks still fail.',
    'The human-like bot reaches 79–81F; the 60F target for normal players is still open.',
    'Shapes (row, square, full cabin) are named in the panel but not yet highlighted in the cabin.',
  ],
};

export const V1011_ZH: ChangelogEntry = {
  version: '10.1.1', date: '2026-09-25', title: '卡片不再显示“送达 净 ±N 金币”',
  summary: '车费降了四成以后，很多乘客单独坐时卡上显示“净 −2、−3”，看起来像“别带他”。其实他们的价值在链接里。卡片上的净收益估算和“配某人 +N”两个标签都去掉了。',
  changes: [
    '候客卡和已上车的卡都不再显示“送达 净 ±N 金币”和“配某人 +N”的虚线标签。卡片只留车费、耗电、躁动三个数字和一句能力说明，链接的收益看“这一层的链接”面板。',
    '只隐藏负数会让“没有标签”本身变成“亏钱”的意思，所以正负都去掉。',
    '两条提示改写，不再引用被删掉的标签：“X 单看不划算，和 Y 挨着坐就赚：一起带上。”“空着的座位也在耗运转电：多带几位，让相同符号的人挨着坐，常常能赚回来。”',
  ],
  experiments: [
    '只改界面，规则和数值不变，沿用 v10.1.0 的验收（4200 局：熟练型 断电 47.0% / 躁动 51.9% / 炸弹 1.0%，抵达 100 层 0.8%）。净收益的计算还在，模拟器里的真人型机器人和测试仍在用。verify 全部通过；浏览器检查了中英文卡片。',
  ],
  watch: [
    '没有净收益标签后，新玩家要靠三个数字和链接面板自己判断值不值得带，需要真人试玩看是否更难上手。',
  ],
};

export const V1011_EN: ChangelogEntry = {
  version: '10.1.1', date: '2026-09-25', title: 'Cards no longer show “On arrival ±N coins”',
  summary: 'After fares dropped by 40%, many riders showed “−2” or “−3” on their own, which read as “don’t board him”, while their value was really in the links. The net-value estimate and the “w/ someone +N” tag are gone from cards.',
  changes: [
    'Waiting and seated cards no longer show “On arrival ±N coins” or the dashed “w/ someone +N” tag. A card keeps its fare, power and agitation numbers and one ability line; what links earn is in the “Links this floor” panel.',
    'Hiding only negative values would make “no tag” mean “loses money”, so both are gone.',
    'Two hints no longer quote the removed tags:',
    '• “X does little on its own but earns beside Y: take them together.”',
    '• “Empty seats still cost motor power: take a few more riders and seat those who share a symbol together; it often pays back.”',
  ],
  experiments: [
    'Interface only; rules and numbers unchanged, so the v10.1.0 acceptance stands (4,200 runs: skilled 47.0% power / 51.9% agitation / 1.0% bomb; 100F reached in 0.8% of runs).',
    'The net-value calculation remains; the human-like simulation bot and the tests still use it.',
    'verify passes; cards were checked in the browser in Chinese and English.',
  ],
  watch: [
    'Without the net tag, new players judge a rider from the three numbers and the links panel; human playtests should show whether that is harder to learn.',
  ],
};

export const V102_ZH: ChangelogEntry = {
  version: '10.2.0', date: '2026-09-25', title: '试玩反馈：悬停说明、符号图鉴、信物图标、新幽灵、大师音乐家、前 40 层电价六折',
  summary: '根据第一局真人试玩（v10.1.1，26 层断电）和反馈：链接和标签看不懂为什么加减、大纸箱的画不对、信物没有形象、幽灵太穷、夜莺的信物太弱、前期钱不够。这一版逐条处理，并升级了本局记录。',
  changes: [
    '链接悬停说明：鼠标移到连线上的标签（手机上点一下），会弹出说明，写清是哪两个人、哪个符号相同或相反、效果是多少；坏人链接和小偷偷钱也有说明。',
    '符号图鉴：点卡片或座位上的符号图标，打开这一类人的图鉴：符号的效果、相反的符号、形状规则，以及所有带这个符号的乘客（白天和午夜后分开）；没遇到过的人物是黑框“？？？”。没有暗黑版带的符号（人间）会直接写明。',
    '卡片上的符号直接写效果：例如“安静 省1电 · 秩序 −1躁动”，不再只是两个图标。人物搭档标签只在能力说明没写的时候补上好处（如“+驱魔师 · 受控：到站 +2 币、每层省 1 电”），避免重复。',
    '大纸箱：拖动时的预览是一个占满整列的高箱子（原来是两个小纸箱）；放下后箱子的画填满上下两格，不再上下留空，也不再被座位的暗化盖掉。',
    '信物有了图标：扳手、红绳、怀表、查房记录、黑胶唱片、招魂铃、股票凭证，都是和符号同风格的线稿。平时只显示图标和名字，效果在悬停（手机上点一下）时出现。',
    '幽灵重做：车费按路程算，每坐一层 1 币（路程 5–10 层，所以 5–10 币），仍然不耗电；没人管时每层 +1 躁动（“幽灵作祟”），另外每 3 层延误一位邻座。被驱魔师、召魂人或灵媒管住时不作祟、不延误，每层抵消 1 点人物耗电、到站再多 2 币。',
    '夜莺的信物“黑胶唱片”改为升级：所有音乐家变成“大师音乐家”，车费翻倍，中躁动时每位演出 +6 币/层（普通 +2），把躁动往中档拉最多 3 点（普通 2 点），从第 1 层起就会出现、出现次数翻倍；拿到信物时车上的音乐家当场升级。原来的“每位到站乘客小费 +2”去掉。',
    '前 40 层商店电价六折（原来前 20 层八五折）。',
    '文字修正：律师不再写“抵消红线金币损失”（红线已经不扣钱）；黑警、月老的说明去掉过时的红线和默契描述；两位怨偶相邻会吵架（各 +1 躁动/层，虽然符号相同），卡面写明。',
    '本局记录升级为第 2 版：每层多了每个座位的符号、链接（生效的符号和等级、红线数、链接赚的钱、省的电、压下的躁动）、收入/电量/躁动的逐项明细、这一层里做过的操作（补电、安抚、道具、请离、换位，以及金币/电/躁动的变化）、事件（发作、事故、偷窃、同化）；商店记录多了买过的每一样东西。',
  ],
  experiments: [
    '复盘第一局真人记录（按记录里的车厢重算每层链接）：25 层里链接一共只赚了 30 币，省了 30 电、压了 45 躁动；车厢以安静、人间为主（恋人、通勤者、护士），这两种符号不赚钱。红线加了 36 躁动，14–17 层小偷夹在警察和护士之间，每层 4–7 条红线，躁动涨到 11/12。25 层总收入 239 币（每层约 9.6），电费每层 10–18 币；10 层商店后剩 0 币，20 层只充到 24/60，26 层断电。机器人里“真人型”能到 79 层，和真人差得很远；更接近的是新手机器人（31 层）。',
    '钱不够的两种修法（每种 150 局 × 3–4 种机器人）：白天车费调回原来的 80%，新手 31→37 层，但真人型、均衡型 70 层离店的钱涨到 205、146，高手又变富。前期电价打折更精准：前 30 层七折，新手 39 层；前 40 层六折，新手 54 层，熟练型不变（87–88 层），到 100 层不变。取前 40 层六折。',
    '幽灵（均衡型 300 局 + 真人型、新手各 120 局）：原来均衡型上车率 63.7%；按路程每层 1 币后升到 73.6%（超过 65%）；加上没人管 +1 躁动后 50.9%，熟练型 88 层、到 100 层 0.7%；+2 躁动时真人型几乎不带他（9.8%），太重。取每层 1 币 + 没人管 +1 躁动。',
    '最终验收 4200 局：五种流派 87–88 层；均衡型中位 87 层（p10–p90 80–94）；抵达 100 层 1.2%；熟练型死因 断电 44.7% / 躁动 54.8% / 炸弹 0.5%；新手 32→58 层；真人型 81 层；均衡型上车率全部在 18–53%（幽灵 53%）。“不宽裕”仍不通过，而且更宽了（73.3%，离店中位 50 币），这是前期电价打折的代价。',
    '浏览器检查：连线悬停说明、符号图鉴（人间：白天 3/4，一位没遇到的黑框）、卡片符号效果、大纸箱整列显示、信物图标和悬停、大师音乐家（车费 10、中躁动演出 +6）、幽灵（7 站车费 7、没人管“幽灵作祟 +1”）、本局记录第 2 版的复制。verify 全部通过。',
  ],
  watch: [
    '前期变便宜后，熟练玩家到中期更富裕；“不宽裕”还要回头处理。',
    '真人型机器人仍比真人强得多，需要更多真人记录（新版记录能看清钱和电花在哪）。',
    '其他传奇的信物以后也可以做成“升级”（例如扳手让维修工变成大师维修工）。',
  ],
};

export const V102_EN: ChangelogEntry = {
  version: '10.2.0', date: '2026-09-25', title: 'Playtest feedback: hover explanations, a symbol codex, keepsake icons, a new Ghost, the Master Musician, 40% off power until 40F',
  summary: 'This release works through the first human playtest of v10.1.1, which ran out of power at 26F, and the feedback that came with it. Link lines and tags did not say why they added or took away. The big box art was wrong, keepsakes had no picture, the Ghost earned too little, the Nightingale’s keepsake was weak, and money ran out early. Each point is handled below, and the run record is upgraded.',
  changes: [
    'Link explanations: hover over a label on a link line (tap on phones) to see which two riders it joins, which symbols match or clash, and what that does. Troublemaker links and a Thief’s pickpocketing are explained too.',
    'Symbol codex: tapping a symbol icon on a card or seat opens that symbol’s page.',
    '• It shows the symbol’s effect, its opposite, the shape rules, and every rider who carries it (day and after-midnight shown apart).',
    '• Riders you have not met show as dark “???” boxes.',
    '• A symbol no dark rider carries (Hearth) says so.',
    'Cards spell out their symbols’ effects, e.g. “Quiet −1 power · Order −1 agitation”, instead of two bare icons.',
    'A partner tag adds its benefit only when the ability line does not already say it (e.g. “+Warden · held: +2 on arrival, −1 power a floor”), so nothing is said twice.',
    'The big box:',
    '• While dragging, it previews as one tall box over the whole column (it used to show a small box in each seat).',
    '• Once seated, its picture fills both seats top to bottom, and the seat dimming no longer hides it.',
    'Keepsakes have icons: Wrench, Red String, Pocket Watch, Rounds Log, Vinyl Record, Bell and Share Certificate, drawn in the same line style as the symbols. Normally only the icon and name show; the effect appears on hover (tap on phones).',
    'The Ghost is reworked. He still uses no power.',
    '• His fare is by distance: 1 coin a floor. He rides 5–10 floors, so he pays 5–10.',
    '• Unheld, he adds 1 agitation a floor (“Ghost haunting”) and delays a neighbour every third floor.',
    '• Held by a Warden, Summoner or the Medium, he neither haunts nor delays, offsets 1 rider power a floor and pays 2 more on arrival.',
    'The Nightingale’s Vinyl Record is now an upgrade: every Musician becomes a Master Musician.',
    '• Fare doubled.',
    '• +6 coins a floor each at medium agitation (a Musician +2).',
    '• Pulls agitation up to 3 toward medium (a Musician 2).',
    '• Appears from floor 1, twice as often; Musicians aboard when the Vinyl arrives are promoted at once.',
    '• The old “+2 tip per arrival” is gone.',
    'Shops sell power at 40% off until 40F (it was 15% off until 20F).',
    'Text fixes:',
    '• The Lawyer no longer claims to offset red-link coin losses (red links cost no coins now).',
    '• The Crooked Cop’s and the Matchmaker’s descriptions lose outdated red-link and bond lines.',
    '• Two Exes side by side fight: +1 agitation each a floor, even though their symbols match; the card says so.',
    'The run record, version 2. Each floor now includes:',
    '• every seat’s symbols;',
    '• the links: active symbols and levels, red links, coins earned, power saved and agitation calmed;',
    '• itemized income, power and agitation;',
    '• actions taken on that floor (charges, calming, items, dismissals, moves) with their coin, power and agitation changes;',
    '• events (outbursts, incidents, thefts, corruption).',
    'Shop entries list every purchase.',
  ],
  experiments: [
    'Replaying the first human record (each floor’s links recomputed from the recorded cabins):',
    '• Over 25 floors the links earned only 30 coins, saved 30 power and calmed 45 agitation. The cabins were mostly Quiet and Hearth (Lovers, Commuters, Nurses), which pay no coins.',
    '• Red links added 36 agitation. At 14–17F Thieves sat between Officers and Nurses, making 4–7 red links a floor, and agitation reached 11/12.',
    '• 239 coins in 25 floors (about 9.6 a floor) against 10–18 coins of power a floor. After the 10F shop 0 coins were left; at 20F power reached only 24/60; the run died at 26F.',
    '• The human-like bot reaches 79F, far from this player; the novice bot (31F) is closer.',
    'Two ways to fix the money (150 runs × 3–4 bots each):',
    '• Daytime fares back to 80% of the originals: novice 31→37F, but the human-like and balanced bots left the 70F shop with 205 and 146 coins, so skilled play was rich again.',
    '• A deeper early power discount targets better. 30% off to 30F: novice 39F. 40% off to 40F: novice 54F, with skilled play (87–88F) and the 100F rate unchanged. Chose 40% off to 40F.',
    'Ghost (balanced 300 runs, human-like and novice 120 each):',
    '• He was boarded 63.7%. With 1 coin a floor he rose to 73.6%, over the 65% limit.',
    '• Adding +1 agitation unheld brought him to 50.9%, with skilled 88F and 100F reached 0.7%.',
    '• At +2 the human-like bot almost never took him (9.8%), too harsh. Chose 1 coin a floor with +1 unheld.',
    'Final acceptance, 4,200 runs:',
    '• Five styles at 87–88F; balanced median 87F (p10–p90 80–94); 100F reached in 1.2% of runs.',
    '• Skilled endings: 44.7% power, 54.8% agitation, 0.5% bomb.',
    '• Novice 32→58F; human-like 81F.',
    '• Every balanced boarding rate is within 18–53% (Ghost 53%).',
    '• “Not affluent” still fails, and more widely (73.3%; median 50 coins after a shop), the cost of cheaper early power.',
    'Browser checks:',
    '• link hover explanations;',
    '• the symbol codex (Hearth: day 3/4, one dark box for a rider not yet met);',
    '• card symbol effects and the full-column big box;',
    '• keepsake icons and their hover;',
    '• the Master Musician (fare 10, +6 at medium agitation);',
    '• the Ghost (a 7-stop Ghost pays 7; unheld shows “Ghost haunting +1”);',
    '• copying a version-2 run record.',
    'verify passes.',
  ],
  watch: [
    'With cheaper early power, skilled players are richer by mid-game; “not affluent” needs another pass.',
    'The human-like bot is still much stronger than a real player; more human records are needed (the new record shows where coins and power go).',
    'Other legends’ keepsakes could become upgrades too (e.g. the Wrench turning Mechanics into Master Mechanics).',
  ],
};

export const V1021_ZH: ChangelogEntry = {
  version: '10.2.1', date: '2026-09-25', title: '乘客卡改成竖版卡牌',
  summary: '候车乘客的卡片原来是横向的一条，画像很小，信息挤在右边。现在改成竖版卡牌（像宝可梦卡、炉石卡）：大画像在上，数值压在画像的角上，下面是符号和能力。',
  changes: [
    '卡片从上到下：名字栏 → 大画像 → 符号效果 → 能力说明框（信物、搭档、操作按钮在最下面）。',
    '数值放在画像上：左上金色圆币是车费，右上是路程（几站），左下青色圆章是耗电，右下红色圆章是躁动；传奇、易燃、悬赏等标签贴在画像左侧。传奇卡不付车费、不耗电，画像底部改为一行说明。',
    '排列：宽屏时右侧一列两张，四位乘客正好 2×2；超过四位时这一列可以上下滚动，卡片不再被压扁。中等宽度（701–1100 像素）时卡片在车厢上方排成一行，多了可以左右滑动。手机上两列。',
    '只改卡片的排版，卡上的信息和原来一样，没有增加或删掉内容。',
  ],
  experiments: [
    '只改界面，规则和数值不变，沿用 v10.2.0 的验收（4200 局）。',
    '浏览器检查了三种宽度，4 位和 6 位乘客：手机 375（两列）、800（一行，可左右滑动）、1440×900（右侧 2×2，6 位时整列滚动）；每种情况下所有卡片的内容都没有被截掉，页面没有横向滚动。verify 全部通过。',
  ],
  watch: [
    '宽屏上超过四位乘客时要往下滚才能看到后面的人，需要真人试玩看会不会漏看。',
  ],
};

export const V1021_EN: ChangelogEntry = {
  version: '10.2.1', date: '2026-09-25', title: 'Rider cards become upright trading cards',
  summary: 'Waiting riders used to be wide strips with a small portrait and the details squeezed to the right. They are now upright trading cards, in the manner of Pokémon or Hearthstone cards: a large portrait on top with the numbers set on its corners, and the symbols and ability below.',
  changes: [
    'Top to bottom, a card reads: name bar, large portrait, symbol effects, ability box (keepsake, partners and action buttons at the foot).',
    'The numbers sit on the portrait:',
    '• fare in the gold coin at top left;',
    '• trip length (stops) at top right;',
    '• power in the cyan badge at bottom left;',
    '• agitation in the red badge at bottom right.',
    'Tags such as Legend, Volatile and Bounty sit on the portrait’s left edge. Legends pay no fare and use no power, so their portrait ends in a one-line note instead.',
    'Layout:',
    '• On wide screens the right column holds two cards a row, so four riders form a 2×2 grid; with more than four the column scrolls instead of squashing the cards.',
    '• At medium width (701–1100 px) the cards form one row above the cabin and scroll sideways when there are more.',
    '• Phones show two columns.',
    'Only the layout changed: the cards carry exactly the information they did before.',
  ],
  experiments: [
    'Interface only; rules and numbers unchanged, so the v10.2.0 acceptance (4,200 runs) stands.',
    'Checked in the browser at three widths with 4 and 6 riders: phone 375 (two columns), 800 (one row, sideways scroll) and 1440×900 (2×2 on the right, the column scrolls with 6). No card had clipped content and the page never scrolled sideways. verify passes.',
  ],
  watch: [
    'With more than four riders on a wide screen, the rest are below the fold; playtests should show whether players miss them.',
  ],
};

export const V1022_ZH: ChangelogEntry = {
  version: '10.2.2', date: '2026-09-25', title: '乘客卡：画像不再被遮挡，卡片按屏幕大小排版',
  summary: 'v10.2.1 的竖版卡在大屏上排成了三列，卡片又窄又挤，下面却空着；车费、耗电等数字压在画像上。现在画像在上面、完整露出，数值放在画像下方单独的属性栏，卡片大小按右栏的实际宽高来定。',
  changes: [
    '卡面从上到下：名字栏 → 画像（不压任何东西）→ 属性栏（金币车费、路程站数、耗电、躁动，四格一排，图标和座位上的一致）→ 标签（传奇、急躁、悬赏等）→ 符号效果 → 能力说明。',
    '画像按比例裁切填满画框，不再被拉伸变形。规则按钮挪进名字栏右端。',
    '宽屏：1–4 位乘客排成两列（2×2），5–6 位在右栏够宽（≥600 像素）时排成三列；卡片宽度会收一点，让两排尽量完整放下，最窄 190 像素；右栏矮而宽时，一排能放下三张。实在放不下时右栏上下滚动，下一排会露出一截提示还有人。',
    '宽屏卡片的画像固定为宽 : 高 = 1 : 0.8，文字多的卡片整张变高，不再挤小画像。卡片较窄时（250 像素以下）符号只显示图标和效果，名字在图标的悬停提示和图鉴里。',
    '中等宽度（701–1100 像素）：卡片那一排从 340 像素加高到 400 像素，放得下属性栏；卡片宽 200–240 像素、居中，一行里的画像同样高。',
    '搭档、信物标签过长时在卡内换行，不再伸出卡边。',
  ],
  experiments: [
    '只改界面，规则和数值不变，沿用 v10.2.0 的验收（4200 局）。',
    '浏览器批量检查：从各楼层生成 41 种普通乘客加 8 位传奇，按 3/4/5/6 人一组逐组上架（每个尺寸 196–200 张卡），检查卡片内容有没有被截掉、有没有伸出卡边。1101×700、1280×720、1440×900、1536×864、1728×960、1728×1117、1920×1080、800×900 全部 0 处。',
    '一屏能完整看到几张：1920×1080 时 3–6 人全部可见；1728×960 和 1728×1117 时 3–4 人全部可见，5–6 人先看到 4 张；1101×700 和 1280×720 时先看到 3 张；1440×900 和 1536×864 时文字多的卡片最少只能完整看到 2 张；看不到的往下滚。手机两列、中等宽度一行都检查过。verify 全部通过。',
  ],
  watch: [
    '1440×900 这类较矮的屏幕上，第二排常要滚动才能看全；如果试玩觉得不方便，可以再压缩文字区（例如把能力说明缩短）。',
  ],
};

export const V1022_EN: ChangelogEntry = {
  version: '10.2.2', date: '2026-09-25', title: 'Rider cards: the portrait is never covered, and cards size to the screen',
  summary: 'On large screens the v10.2.1 upright cards fell into three narrow, crowded columns with empty space below, and the fare, power and agitation numbers sat on top of the portrait. The portrait now sits uncovered at the top, the numbers have their own stat bar beneath it, and card size follows the real width and height of the right-hand column.',
  changes: [
    'Top to bottom, a card reads: name bar, portrait (nothing on it), stat bar, tags (Legend, Impatient, Bounty and so on), symbol effects, ability text.',
    '• The stat bar is one row of four cells: fare in coins, trip in stops, power and agitation, with the same icons as the seats.',
    'Portraits are cropped to fill their frame instead of being stretched. The rules button moves into the right end of the name bar.',
    'Wide screens:',
    '• 1–4 riders form two columns (2×2); 5–6 form three columns when the column is at least 600px wide.',
    '• Cards narrow a little so that two rows fit where possible, down to 190px wide; a short, wide column then fits three across.',
    '• When everyone still can’t fit, the column scrolls and the next row peeks out.',
    'On wide screens the portrait keeps a fixed 1 : 0.8 frame; a card with more text grows taller instead of shrinking its portrait. On cards narrower than 250px, symbols show only their icon and effect; the name is in the icon’s tooltip and the codex.',
    'Medium width (701–1100px): the card row grows from 340px to 400px to hold the stat bar; cards are 200–240px wide and centred, and portraits in a row share one height.',
    'Long partner and keepsake tags wrap inside the card instead of running past its edge.',
  ],
  experiments: [
    'Interface only; rules and numbers unchanged, so the v10.2.0 acceptance (4,200 runs) stands.',
    'Batch browser check:',
    '• 41 ordinary riders drawn from floors across the run, plus 8 Legends, shown in groups of 3, 4, 5 and 6 (196–200 cards per size).',
    '• Each card was checked for clipped content and for anything running past its edge.',
    '• Zero at 1101×700, 1280×720, 1440×900, 1536×864, 1728×960, 1728×1117, 1920×1080 and 800×900.',
    'How many cards are fully in view:',
    '• 1920×1080: all of 3–6;',
    '• 1728×960 and 1728×1117: all of 3–4, and 4 of 5–6;',
    '• 1101×700 and 1280×720: 3;',
    '• 1440×900 and 1536×864: as few as 2 when cards carry a lot of text.',
    'The rest are a scroll away.',
    'Phone (two columns) and medium width (one row) were checked too. verify passes.',
  ],
  watch: [
    'On shorter screens such as 1440×900 the second row often needs a scroll; if that gets in the way in playtests, the text area can be tightened (for example with shorter ability lines).',
  ],
};

export const V1023_ZH: ChangelogEntry = {
  version: '10.2.3', date: '2026-09-25', title: '修复：商店里花掉抢救钱后离店直接失败；拖拽卡顿',
  summary: '一局试玩在 29 层带着躁动 13/8 进了 30 层商店（金币 101，最低抢救要 48）。先免费选了电池、再花 40 加购惯性飞轮、又升了一级配电箱，剩 33 币，付不起抢救，一离店就输了。另一个反馈是拖动乘客卡时一卡一卡的。',
  changes: [
    '商店里躁动或电量失控时，最低抢救的钱会先留出来：能力加购、重抽、能力升 2 级、配电箱、道具和夜市，凡是会让剩下的钱不够抢救的，都不能买，按钮上写“先留 N 币抢救”。免费选取、充电、安抚这类本身能缓解失控的，只要买完仍付得起抢救就照常可买。',
    '失控提示多一句：“抢救要 N 币，这笔钱先留着：能力、配电箱、道具都不能花掉它。”离店按钮在付得起时仍是“最低抢救 · N 金币”。',
    '本局记录：在商店里结束的局，最后一次商店（买了什么、进店时的躁动和上限）也会记下来，并标明在这里结束。以前只有成功离店才记录。',
    '拖拽更顺：拖动时每换一个目标座位，整个游戏界面都要重新生成一次，其中一大半花在两件没打开的东西上：一是更新日志和乘客档案的全部内容（关着也在生成），二是英文界面把每段文字重新翻译一遍。现在这两个弹窗只在打开时才生成内容，翻译结果也会缓存。',
  ],
  experiments: [
    '复盘这局记录：29 层结算后躁动 13、上限 8，最低抢救 6 点 × 8 = 48 币。新增检查 verify-shop-rescue 用同样的数重放：电池免费可选、飞轮加购（剩 61）可买、配电箱一级（15，会剩 46）被拒绝、抢救后躁动 7 能继续上行；不抢救离店仍然失败。',
    '拖拽计时（同一台机器，正式版，英文，1728×1117，拖动时依次经过 5 个座位，重复 4 次）：线上 v10.2.2 换目标座位中位 26 毫秒、最慢 40 毫秒，开始拖动 33–48 毫秒；修复后中位 8 毫秒、最慢 15 毫秒，开始拖动 11–21 毫秒，都在一帧（16 毫秒）左右。开发版里同样的操作从每次约 650–700 毫秒降到约 100 毫秒。',
    '数值没有改。验收 4200 局与 v10.2.0 完全相同：熟练型死因 电量 44.7% / 躁动 54.8% / 炸弹 0.5%，抵达 100 层 1.2%，新手 58 层、真人型 81 层，均衡型上车率 18–53%（机器人从不在失控时乱花抢救钱，所以不受影响）。模拟器里商店安抚的循环加了“买不了就停”，避免新规则下空转。verify 全部通过。',
  ],
  watch: [
    '失控时被锁住的按钮会不会让人困惑，需要真人试玩看；如果需要，可以把“先抢救”做成进店时的一步。',
    '更慢的电脑上拖拽还可能有轻微卡顿；下一步可以把座位和卡片拆成独立组件，只重画变化的部分。',
  ],
};

export const V1023_EN: ChangelogEntry = {
  version: '10.2.3', date: '2026-09-25', title: 'Fixes: spending the rescue money in the shop ended the run on leaving; dragging stuttered',
  summary: 'A playtest reached the 30F shop at agitation 13/8 with 101 coins, when the minimum rescue cost 48. The player took Battery free, bought Inertia Flywheel for 40 and a power-box level, and was left with 33 coins, too few for the rescue, so leaving the shop ended the run. Separately, dragging rider cards stuttered.',
  changes: [
    'When agitation or power is critical in the shop, the minimum rescue’s coins are held back first.',
    '• An extra ability, a reroll, a level-2 raise, a power-box level, an item or a night-market item cannot be bought if it would leave too little for the rescue; its button says “Keep N coins for the rescue”.',
    '• The free pick, charging and calming, which ease the crisis themselves, stay available as long as the rescue still fits afterwards.',
    'The crisis note adds: “The rescue costs N coins and that money is held back: abilities, the power box and items cannot spend it.” While affordable, the leave button still reads “Minimum rescue · N coins”.',
    'Run record: a run that ends in a shop now records that last shop too (what was bought, agitation and its cap on arrival), marked as where the run ended. Before, a shop was recorded only when you left it and carried on.',
    'Smoother dragging. Each time a drag crossed onto a new seat, the whole game screen was rebuilt, and most of that time went on two things that were not even visible:',
    '• the full changelog and passenger archive, built even while their dialogs were closed;',
    '• the English interface translating every line again.',
    'Those two dialogs now build their contents only while open, and translations are cached.',
  ],
  experiments: [
    'Replaying the record: after 29F agitation was 13 with a cap of 8, so the minimum rescue was 6 points × 8 = 48 coins.',
    'A new check, verify-shop-rescue, replays those numbers:',
    '• the free Battery pick is allowed;',
    '• the Flywheel extra (leaving 61) is allowed;',
    '• a power-box level (15, which would leave 46) is refused;',
    '• after the rescue agitation is 7 and the shift continues;',
    '• leaving without the rescue still ends the shift.',
    'Drag timing: same machine, production builds, English, 1728×1117, a drag crossing 5 seats, repeated 4 times.',
    '• Live v10.2.2: a seat change took 26 ms (median, max 40); starting a drag took 33–48 ms.',
    '• Fixed: a seat change takes 8 ms (median, max 15); starting a drag takes 11–21 ms, about one frame (16 ms).',
    '• In the development build the same step fell from about 650–700 ms to about 100 ms.',
    'Numbers unchanged. The 4,200-run acceptance matches v10.2.0 exactly:',
    '• skilled endings: power 44.7% / agitation 54.8% / bomb 0.5%;',
    '• 100F reached in 1.2% of runs;',
    '• novice 58F, human-like 81F;',
    '• balanced-bot boarding 18–53%.',
    'The bots never spend rescue money in a crisis, so they are unaffected. The simulator’s shop-calming loop now stops when a purchase is refused, so the new rule cannot stall it. verify passes.',
  ],
  watch: [
    'Playtests should show whether the locked buttons in a crisis confuse anyone; if so, the rescue could become a step on entering the shop.',
    'Slower computers may still stutter slightly; the next step would be splitting seats and cards into their own components so only what changed is redrawn.',
  ],
};

export const V1024_ZH: ChangelogEntry = {
  version: '10.2.4', date: '2026-09-25', title: '浏览器试玩十局后的修正：卡面、抵消的邻座、提示用词、手机操作',
  summary: '在浏览器里玩了十局（中英文，手机、平板、笔记本和大屏各种尺寸；有自己手动玩的开局，也有熟练型和“新手型”自动玩），边玩边改。这一版修掉玩的时候看不懂、看错或不准确的地方，数值没有改。',
  changes: [
    '窄卡片不再省略符号名称：以前只剩“+2币 · 省1电”，看起来像人物自己的数值，醉汉更是显示成“+2币 · +2币”。现在永远写“江湖 +2币 · 幽冥 省1电”，放不下就分两行。',
    '互相抵消的邻座会显示出来：两人有一个相同符号、又有一对相反符号时，按规则一绿一红抵消、没有链接（比如警察挨着通勤者：都有秩序，但热闹和安静相反）。以前什么都不显示，现在接缝处有一个淡色虚线“±0”，悬停（手机点一下）说明是哪两个符号抵消了。',
    '去掉剩下的表情符号：座位上的“红线 🔥 +1”改成“红线 +1躁动”；红线说明、说明书标题里的 🔥⚡🪙 改成文字；团伙标签的锁链、炸弹倒计时的秒表换成和符号同风格的线稿图标。',
    '躁动来源里的减号统一成“−1”（以前有些写成 “-1”）。',
    '失控提示分清“必定”和“可能”：最好的情况也会超过上限时，写“这一层躁动必定失控”“这一层必定断电”，再按一次上行的提示改成“＝结束本班”；只是有风险时仍写“可能”“冒险出发”。',
    '电量和躁动同时耗尽时，结束页也会点名这一层躁动的主要来源和对应办法（以前只说“双重失控，下一班留好维修预算”），再补一句电量也在这一层用完。',
    '手机和平板：开局提示从“把候选人物拖进站位”改成“先点一位候客人物，再点一个空位”；上行按钮上的键盘提示“ENTER”在触屏上不再显示。',
    '大师音乐家上车时，提示写“大师音乐家已站到…”，不再是“音乐家”。',
    '百变人变化的提示和前一句之间加了分隔“ · ”，不再连在一起。',
  ],
  experiments: [
    '十局结果：熟练型自动玩 95、95、86、95、93、78、94 层（死因多是深渊里几位暗黑版同时发作，或午夜后电量掉得快）；新手型（按顺序坐满、不看链接、无视警告）18、8、13 层，都是没人管的小偷、没带纸箱的快递员和随便坐出来的红线把躁动推满。',
    '新手型那两局里游戏已经提前警告了（“这一层躁动可能失控：5/8，下一站 +4 · 安抚 −2 · 12币”），是脚本没理会；所以改的是用词（这种情况其实是“必定”），不是规则。',
    '手动玩的开局看到：安静符号（通勤者、恋人）叠成方块或满车后，前 10 层电量几乎不掉（一层只 −1～−2），躁动一直是 0；熟练玩法到 55 层有 170 多币、78 层有 220 多币。“钱不宽裕”仍没达标，这次没有改数值，留给之后单独处理。',
    '新增检查 verify-playtest-v1024：警察和通勤者、游客和恋人会被识别为抵消的邻座，两个通勤者不会；双重失控的结束提示含躁动来源且英文里没有中文；红线说明里没有表情符号。verify 全部通过，lint 没有新增问题。',
    '每日班次这次没测到：它在页面第一次绘制时发牌，而测试用的浏览器面板是隐藏的；这对真人玩家没有影响。',
  ],
  watch: [
    '安静叠满后前期太省电、熟练玩家中后期太有钱，需要一起看。',
    '“±0”标签会不会让车厢太杂，需要真人看看。',
  ],
};

export const V1024_EN: ChangelogEntry = {
  version: '10.2.4', date: '2026-09-25', title: 'Fixes from ten browser runs: card faces, cancelled neighbours, warning wording, touch controls',
  summary: 'Ten runs were played in the browser, in Chinese and English, at phone, tablet, laptop and large-screen sizes. Some openings were played by hand, and the rest by the skilled and “novice” autopilots. Fixes were made along the way. This release clears up what was hard to read, easy to misread or inaccurate. No numbers change.',
  changes: [
    'Narrow cards keep the symbol names.',
    '• Before, a card showed only “+2 coins · −1 power”, which read like the rider’s own numbers; the Drifter even showed “+2 coins · +2 coins”.',
    '• Cards now always say “Street +2 coins · Spirit −1 power”, on two lines if needed.',
    'Neighbours who cancel out are shown. When two riders share one symbol but also carry an opposing pair, the green and the red cancel under the rules and there is no link (an Officer beside a Commuter shares Order, but Lively opposes Quiet). Nothing used to appear; now a faint dashed “±0” sits on the seam, and hovering (or tapping on phones) names the symbols that cancel.',
    'The last emoji are gone.',
    '• Seats read “Red link +1 agitation” instead of “Red link 🔥 +1”.',
    '• Red-link descriptions and the manual heading use words instead of 🔥, ⚡ and 🪙.',
    '• The crew chain and the bomb stopwatch are line-art icons in the style of the symbols.',
    'Agitation sources use a proper minus sign, “−1” (some showed “-1”).',
    'Warnings now tell “will” from “can”.',
    '• When even the best case passes the limit, they read “Agitation will boil over this floor” or “This floor will run you out of power”, and the second-press note reads “ends the shift”.',
    '• A merely risky floor still says “can” and “risk it”.',
    'When power and agitation both run out, the ending names the main agitation source and its fix, as a single failure does (it used to say only “budget for both repairs next shift”), and adds that power ran out on the same floor.',
    'Phones and tablets: the opening hint says “Tap a waiting rider, then tap a seat” instead of “Drag a candidate into a position”, and the ascend button no longer shows the keyboard hint “ENTER”.',
    'A boarding Master Musician is named “Master Musician” in the placement message, not “Musician”.',
    'The Shifter’s change note is separated from the sentence before it by “ · ” instead of running on.',
  ],
  experiments: [
    'The ten runs:',
    '• the skilled autopilot reached 95, 95, 86, 95, 93, 78 and 94F, usually ending when several dark riders lashed out at once in the abyss, or when power fell fast after midnight;',
    '• the novice autopilot (fills seats in order, ignores links and warnings) reached 18, 8 and 13F, pushed over by unguarded Thieves, Couriers without their box and red links from random seating.',
    'In both novice deaths the game had warned beforehand (“Agitation can boil over this floor: 5/8 now, next +4 · Calm −2 · 12c”) and the script ignored it. So the fix is the wording (that floor was a certain loss), not the rules.',
    'Hand-played openings showed:',
    '• once Quiet riders (Commuters, Lovers) form a square or a full cabin, power barely drops for the first 10 floors (−1 to −2 a floor) and agitation stays at 0;',
    '• skilled play held 170+ coins at 55F and 220+ at 78F.',
    '“Not affluent” is still unmet. No numbers changed this time; it is left for a separate pass.',
    'A new check, verify-playtest-v1024:',
    '• an Officer with a Commuter and a Tourist with a Lover are reported as cancelled pairs; two Commuters are not;',
    '• the both-failure ending names the agitation source and has no Chinese left in English;',
    '• red-link descriptions contain no emoji.',
    'verify passes; lint adds nothing.',
    'The daily shift was not tested: it deals on the page’s first frame and the test browser pane was hidden. Real players are unaffected.',
  ],
  watch: [
    'Quiet stacking makes early power too cheap and skilled play too rich mid-to-late; the two should be looked at together.',
    'Playtests should show whether the “±0” labels clutter the cabin.',
  ],
};

export const V1025_ZH: ChangelogEntry = {
  version: '10.2.5', date: '2026-09-26', title: '中后期少一点钱：31 层起车费 75 折，61 层起充电贵 25%',
  summary: '按实验决定参数。先查清钱从哪来、在哪多出来：前 10 层普通和熟练玩法都“刚好够用”（10 层商店充满电后只剩 0–25 币），多出来的钱从 20 层起在熟练玩法里越攒越多（每十层收入从约 95 涨到约 200，离店常剩 50–110 币）。这一版只动中后期，前期不变。',
  changes: [
    '31 层起上车的乘客，基础车费打 75 折（向上取整）。卡片上显示的就是折后价；邻座奖励、小费、符号绿线和暂存收益不打折。',
    '61 层起（午夜后）商店充电贵 25%：2 币/电 → 2.5 币/电（变压器等级照常降低）。商店里写着“午夜后贵 25%”。',
    '监工车费 9 → 12、疯炸客 40 → 52：它们只在午夜后出现，打折后分别是 9 和 39，和以前差不多；不补的话机器人几乎不载他们（上车率 13–14%）。',
    '说明书更新：“三个数字”改为“卡片上的数字”（画像下面一排：车费、路程、耗电、躁动），并写明 31 层起车费打折；“电量”一条写明 40 层前 6 折、61 层起贵 25%。',
  ],
  experiments: [
    '收入分析（新加的按来源、按十层统计，均衡型 / 真人型 / 新手型各 120 局）：收入很分散，最大一项（通勤者到站）只占 7–10%；中后期涨得最多的是热闹和江湖的绿线金币，以及检查员、教练、游客等每次到站 11–16 币的人物。',
    '试过的改法（每种 1120 局，看“进店宽裕”和离店中位金币；原来 73% / 48 币）：形状加级减半 72% / 42；取消安静好评 70% / 39；热闹、江湖每级减半 68% / 36，但新手从 61 层掉到 54 层，链接也更不值钱；电池加成减半 72% / 43；31 层起车费 75 折 71% / 42；61 层起充电贵 25% 71% / 47；后两项一起 69% / 41。',
    '一个关键发现：减少收入几乎不影响熟练玩家能走多远（都在 87–88 层，死于深渊发作），钱只是攒着用不上；而大幅减收会先伤到新手。所以这次选了温和、看得见的两项（车费打折写在卡上，电价写在商店），不去大砍链接收入。',
    '最终验收 4200 局：死因 电量 49.8% / 躁动 49.3% / 炸弹 0.8%（原来 44.7 / 54.8，更接近一半一半）；抵达 100 层 0.3%；均衡型中位 88 层（p10–p90 77–94）；新手 57 层、真人型 84 层；均衡型上车率全部在 15–65%；五种流派 87–88 层。“不宽裕”仍不通过：进店宽裕 69.3%（原来 73.3%）、离店中位 42 币（原来 50）。',
    'verify 全部通过（复制人、神秘人的车费检查按新规则更新）。',
  ],
  watch: [
    '“不宽裕”的验收目标（≤15%、离店 ≤15 币）按现在的收入结构只能靠大幅减收达到，而那会先伤新手；真人型和新手型本来就不宽裕（0–3%）。可能要改成只衡量普通玩法，或者给中期加值得花钱的东西。',
  ],
};

export const V1025_EN: ChangelogEntry = {
  version: '10.2.5', date: '2026-09-26', title: 'A little less money mid-to-late: 75% fares from 31F, 25% dearer power from 61F',
  summary: 'The parameters were chosen by experiment. The first step was finding where the money comes from and where it piles up. In the first 10 floors both normal and skilled play have just enough: after charging at the 10F shop, 0–25 coins are left. The surplus builds from 20F in skilled play: income per ten floors rises from about 95 to about 200, and 50–110 coins are often left after a shop. This release only touches the middle and late game; the early game is unchanged.',
  changes: [
    'Riders who board from 31F on pay 75% of their base fare (rounded up).',
    '• The card shows the reduced price.',
    '• Neighbour rewards, tips, symbol green links and stashes are not reduced.',
    'From the 61F shop on (after midnight), shop power costs 25% more: 2 coins a power becomes 2.5, and Transformer levels still lower it. The shop says “+25% after midnight”.',
    'Fare rises for the two riders who only appear after midnight, where the discount always applies:',
    '• Taskmaster 9 → 12, which pays 9 after the discount, about as before;',
    '• Mad Bomber 40 → 52, which pays 39 after the discount.',
    'Without the rise, the bots hardly took them (13–14% boarding).',
    'Manual updates:',
    '• “Three numbers” becomes “The numbers on a card”: the row under the portrait with fare, trip, power and agitation, plus the late fare discount.',
    '• “Power” mentions 40% off until 40F and 25% more from 61F.',
  ],
  experiments: [
    'Income analysis: a new per-source, per-ten-floors breakdown over 120 runs each of the balanced, human-like and novice bots.',
    '• Income is spread thin: the largest single source, Commuter arrivals, is only 7–10%.',
    '• What grows most mid-to-late is Lively and Street green-link coins, plus riders who pay 11–16 per arrival: Inspector, Coach and Tourist.',
    'Options tried, 1,120 runs each. Figures are the share of shop visits where the player was affluent on arrival, then median coins left on exit; the baseline was 73% / 48.',
    '• Half shape levels: 72% / 42.',
    '• No low-agitation tip: 70% / 39.',
    '• Lively and Street halved: 68% / 36, but the novice fell from 61F to 54F and links would matter even less.',
    '• Half Battery bonus: 72% / 43.',
    '• 75% fares from 31F: 71% / 42.',
    '• 25% dearer power from 61F: 71% / 47.',
    '• The last two together: 69% / 41.',
    'A key finding: cutting income barely changes how far skilled play goes (87–88F, ending in abyss outbursts), because the money simply sits unused, while deep cuts hurt novices first. So this release takes two mild, visible measures (the discount is on the card, the price in the shop) rather than cutting link income hard.',
    'Final acceptance, 4,200 runs:',
    '• endings power 49.8% / agitation 49.3% / bomb 0.8% (was 44.7 / 54.8, now closer to half and half);',
    '• 100F reached in 0.3% of runs;',
    '• balanced median 88F (p10–p90 77–94);',
    '• novice 57F, human-like 84F;',
    '• balanced-bot boarding all within 15–65%;',
    '• all five styles 87–88F.',
    '“Not affluent” still fails: affluent on arrival 69.3% (was 73.3%), median coins on exit 42 (was 50).',
    'verify passes; the Mimic and Mystery fare checks were updated for the new rule.',
  ],
  watch: [
    'The “not affluent” target (≤15%, ≤15 coins on exit) could only be met by deep income cuts, which hurt novices first. The human-like and novice bots are already not affluent (0–3%). The target may need to measure normal play only, or the middle game needs things worth buying.',
  ],
};

export const V1026_ZH: ChangelogEntry = {
  version: '10.2.6', date: '2026-09-26', title: '幽灵不吃 31 层后的车费折扣',
  summary: '上一版试玩时发现：31 层后上车的幽灵，卡上写“每坐一层 1 币”、路程 9 站，车费却显示 7（9 × 75% 向上取整），规则和数字对不上。幽灵的车费本来就是按路程算的，所以不再打折。',
  changes: [
    '幽灵的车费始终等于要坐的层数（每层 1 币），31 层后上车也一样；其他乘客照旧打 75 折。',
  ],
  experiments: [
    '检查：35 层上车坐 9 站的幽灵车费 9；同层上车的通勤者 3（原价 4）；20 层上车的通勤者 4。',
    '均衡型 300 局：幽灵上车率 54%（v10.2.5 为 53%），全部人物在 15–65%；死因 电量 62.3% / 躁动 36.7%（只看均衡型一种机器人）。verify 全部通过。',
    '浏览器又玩了 4 局（81、96、86 层；一局在 1 层被热更新重置）：31 层后卡片车费显示正确（监工 9、警察 3），61 层起商店写“2.5 币/电 · 午夜后贵 25%”，中后期金币明显更紧（86 层断电时剩 0–5 币）。',
  ],
  watch: [
    '中后期更紧之后，新手和普通玩家在 60–80 层会不会觉得太难，需要真人记录。',
  ],
};

export const V1026_EN: ChangelogEntry = {
  version: '10.2.6', date: '2026-09-26', title: 'The Ghost keeps his fare after 31F',
  summary: 'A playtest of the last release showed a Ghost boarding after 31F whose card promised 1 coin a floor for a 9-stop trip, yet showed a fare of 7 (9 × 75%, rounded up). The rule and the number disagreed. His fare already follows the distance, so it is no longer reduced.',
  changes: [
    'The Ghost always pays 1 coin per floor ridden, also when he boards from 31F on; every other rider still pays 75% there.',
  ],
  experiments: [
    'Checks:',
    '• a Ghost boarding at 35F for 9 stops pays 9;',
    '• a Commuter boarding there pays 3 (base 4);',
    '• a Commuter boarding at 20F pays 4.',
    '300 balanced-bot runs:',
    '• Ghost boarding 54% (53% in v10.2.5), every rider within 15–65%;',
    '• endings power 62.3% / agitation 36.7% (balanced bot only).',
    'verify passes.',
    'Four more browser runs (81, 96 and 86F; one was reset at 1F by a hot reload):',
    '• card fares after 31F show correctly (Taskmaster 9, Officer 3);',
    '• from 61F the shop reads “2.5 c/power · +25% after midnight”;',
    '• coins are visibly tighter mid-to-late: 0–5 left at an 86F power-out.',
  ],
  watch: [
    'With tighter money mid-to-late, human playtests should show whether 60–80F now feels too hard for normal players.',
  ],
};

export const V1027_ZH: ChangelogEntry = {
  version: '10.2.7', date: '2026-09-26', title: '真人试玩（82 层）后的修正：剪线婆看得见、请离券说清楚、车费下限',
  summary: '一位真人玩家玩到 82 层（躁动失控）。逐条核对了记录里的疑点：剪线婆的规则没显示在连线上（确认是界面问题，已改）；请离券不能请离剪线婆（确认是故意的，但没有任何提示，已补）；高躁动门槛不随上限变化（仪表盘本来就画对了，只补说明）；短途加后期折扣后恋人只付 1 币（已加下限）；80 层商店买不起保命道具（查了数据，是这局的取舍，不改）。',
  changes: [
    '剪线婆在车上时，连线标签直接显示她的效果：绿线上多一个“剪刀 · 火焰 +1”（每条绿线每层 +1 躁动，绿线原本的效果照旧），红线上多一个“剪刀 +3 币”；悬停说明也写明。“这一层的链接”面板多一行“剪线婆：绿线 +N 躁动，红线 +N 币”。以前只在躁动明细里看得到“剪线婆剪断绿线 +3”，玩家一直在凑绿线。',
    '请离券：点到传奇（包括剪线婆）时不再默默取消，而是提示“传奇不用请离券：点开他的人物详情，「请离」就能免费让他下车”；黑老大会提示要付赔偿。道具说明也加上“传奇本来就能免费请离，不用券”。',
    '安全余量的说明加上“高躁动仍从5起算”。',
    '车费下限：基础车费 2 币以上的乘客，短途和 31 层后的折扣叠加后，至少仍付 2 币（这局 65 层一位短途恋人只付了 1 币）。',
  ],
  experiments: [
    '请离核对：剪线婆（和其他传奇）在人物详情里请离免费，而且不占每十层 2 次的请离次数，即使次数用完也可以；请离券对传奇无效是原本的设计（券的作用是省下普通乘客的请离次数），问题只是没有提示。',
    '80 层商店：这位玩家进店 68 币、离店 0，没钱买照明弹。同规则下机器人 80 层商店进店 211–353 币、离店 45–93。差别来自这局的选择：配电箱累计 140 币、安抚和道具 100 多币。这正是“钱刚好够用”的效果，不改。',
    '这局各商店离店金币 24、27、11、14、0、3、0、0，整局没有宽裕过；81 层死于一次约 10% 的赌博（狂徒发作 +3）。',
    '验证：均衡型 / 新手各 300 局，88 层 / 57 层，上车率全部在 15–65%，和上一版一致。新增回归检查：请离券对剪线婆无效、剪线婆可免费请离、短途恋人 31 层后付 2、幽灵照旧按层数付费。verify 全部通过；浏览器里核对了剪线婆的连线标签、链接面板和请离券提示。',
  ],
  watch: [
    '剪线婆的规则现在看得见了，还需要真人看看会不会主动去凑红线。',
    '高躁动门槛是否该跟着上限一起涨，是设计问题，暂不改。',
  ],
};

export const V1027_EN: ChangelogEntry = {
  version: '10.2.7', date: '2026-09-26', title: 'Fixes after an 82F human playtest: the Severer is visible, the Exit Pass explains itself, a fare floor',
  summary: 'A human player reached 82F and lost to agitation. Each suspected problem in the record was checked. Two were real and are fixed, one was working as designed but silent and now explains itself, one needed only a note, and one was not a problem.',
  changes: [
    'With the Severer aboard, link labels show her effect.',
    '• Green links get a “scissors · flame +1”: +1 agitation per green link a floor, on top of the link’s usual effect.',
    '• Red links get a “scissors +3 coins”.',
    '• The hover text says so, and the “Links this floor” panel adds a line: “Severer: green +N agitation, red +N coins”.',
    'Before, only the agitation breakdown showed “Severer cuts green links +3”, and the player kept building green links.',
    'Exit Pass: tapping a legend (the Severer included) no longer silently cancels.',
    '• It says: “Legends need no Exit Pass: open their rider details and Dismiss lets them off for free.”',
    '• The Kingpin’s note says dismissing him costs compensation.',
    '• The item text adds that legends already leave free without a pass.',
    'The Safety Margin text adds that high agitation still starts at 5.',
    'Fare floor: a rider whose base fare is 2 or more still pays at least 2 after the short-trip and after-31F discounts combine. In this run, a short-trip Lover at 65F paid 1.',
  ],
  experiments: [
    'Checked and fixed:',
    '• the Severer’s rule was invisible on the links (an interface problem);',
    '• a short-trip Lover paid 1 coin after both discounts (now at least 2).',
    'Working as designed, now explained:',
    '• the Exit Pass never takes a legend.',
    '• Any legend, the Severer included, leaves free through Dismiss in the rider details, without using one of the 2 dismissals per ten floors, even when those are spent.',
    '• The pass exists to save a normal rider’s dismissal; the only problem was the silence.',
    'Only a note needed: high agitation starts at 5 whatever the cap. The gauge already drew it that way.',
    'Not a problem: the 80F shop.',
    '• The player arrived with 68 coins and left with 0, unable to buy a Flare.',
    '• Under the same rules the bots arrive with 211–353 and leave with 45–93.',
    '• The difference is this run’s choices: 140 coins on the power box, over 100 on calming and items. That is “just enough money” working, so it stays.',
    'This run left shops with 24, 27, 11, 14, 0, 3, 0 and 0 coins: never affluent. It ended at 81F on a roughly 10% gamble (a Brawler outburst, +3).',
    'Verification:',
    '• balanced and novice bots, 300 runs each: 88F and 57F, boarding all within 15–65%, as in the last release;',
    '• new regression checks: the Exit Pass refuses the Severer, the Severer leaves free, a short-trip Lover after 31F pays 2, and the Ghost still pays by floors;',
    '• verify passes;',
    '• the Severer’s link labels, links panel and Exit Pass note were checked in the browser.',
  ],
  watch: [
    'Now that the Severer’s rule is visible, playtests should show whether players start building red links on purpose.',
    'Whether the high-agitation threshold should rise with the cap is a design question and is left as is.',
  ],
};
