import type { ChangelogEntry } from './changelog';

export const V10_ZH: ChangelogEntry = {
  version: '10.0.0', date: '2026-09-25', title: '符号链接：绿线红线由符号决定，一眼看懂，组合更多',
  summary: '以前的绿线红线是一张手写名单：每人只喜欢一两个特定人物、讨厌零到两个，要靠背；统计显示真人型玩家 78% 的楼层车里一条绿线都没有，链接几乎不起作用。v10 把名单换成符号：每位乘客两个符号，相同符号挨着坐是绿线，相反符号是红线，每种符号的绿线有自己的效果。人物能力（警察管住小偷、恋人配对、护士、教练……）不变。规则和数值都是模拟实验里一轮轮试出来的，下面列出了每一步。',
  changes: [
    '六个符号，三组相反：🎉热闹↔🤫安静、📋秩序↔🎲江湖、🏠人间↔👻幽冥。每位乘客两个（不会是相反的一对），显示在卡片和座位的名字旁，悬停可看规则。暗黑版多是热闹、江湖、幽冥，和白天的乘客容易起冲突。',
    '绿线和红线：邻座有相同符号＝绿线，有相反符号＝红线；同一对邻座的相同和相反符号一对一抵消（一个相同、一个相反＝没有线）。',
    '每种符号只要车里有一条它的绿线，每层就生效一次：🎉 +2 币；🎲 +3 币但 +1 躁动；📋 −1 躁动；🏠 −1 躁动；🤫 省 1 电；👻 省 1 电（省电不超过乘客自己的耗电）。同一符号连成一排再加 1 级、四人方块加 2 级、满车加 4 级。',
    '红线只有一种：每条每层 +1 躁动。原来的“红线耗电”“红线扣钱”“耗电翻倍”“赌局红线”都取消了。',
    '卡片不再列“协作 / 冲突”的名单，只留人物能力带来的搭档（如警察—小偷）。人物详情里新增“符号”一栏，写清每个符号的绿线效果和相反符号。',
    '新面板“这一层的链接”：列出生效的符号、等级、效果和红线数；连线上显示共同的符号，红线显示 🔥+1。说明书新增“符号与链接”，躁动说明和邻座说明也改写了。',
    '车费：白天乘客 ×0.6（链接成了主要收入）；暗黑版为 v9.22 的 80%（劫匪保留 14、召魂人 6）；幽灵 1；神秘人四种身份 6 / 16 / 20 / 6。',
    '能力与信物：默契契约和红绳改为“🎉🎲 每级绿线每层 +2 币”（契约 2 级 +3）；绝缘衬层只剩“每条红线每层 +1 币冲突小费（最多 3）”。',
    '发牌：和主牌一起发的搭档一定和他真的有链接（能力搭档，或不抵消的符号关系），也会发和他有共同符号的人；“冲突包”发的是和他有相反符号的人。',
  ],
  experiments: [
    '改之前的统计（每种机器人 100 局）：真人型每层 0.26 条绿线、78% 的楼层没有绿线；均衡型 0.75 条、53%。',
    '规则是按实验一步步定的（每步 150 局 × 3–4 种机器人）：',
    '① 每条绿线每层 +1 币、红线 +1 躁动：真人型机器人 15 层就被躁动压垮（一对邻座 58% 的机会有相反符号），熟练型离开 70 层商店时还有 317 币。',
    '② 加入“相同减相反”：红线机会降到 42%，真人型到 63–68 层；但钱仍然太多（617 币）。',
    '③ 每种符号的绿线各管一种资源：钱不再只从链接里涨，但新手从 34 层变成 68 层——按每条线计的奖励叠得太多，所有人都变容易了。',
    '④ 改成“每种符号有一条绿线就生效一次，形状加级”：新手回到 59 层、钱降下来；再把车费降到 ×0.6：新手 29–32 层、熟练型 87 层。',
    '红线 +2 躁动和 +1 几乎没有区别，保留 +1（更简单）。',
    '单符号流派（每种各 100 局，只偏爱带这个符号的乘客）：六种都在 87–88 层；每个流派最常生效的都是自己的符号（热闹 64%、安静 65%、人间 63%、秩序 53%、江湖 38%、幽冥 37%）。',
    '18 种符号流派（6 种单符号 + 12 种双符号，每种 60 局，最终数值）：都在 86–88 层。单符号流派差别明显，自己的符号生效率最高（热闹 64%、安静 66%、人间 62%、秩序 58%）；含江湖或幽冥的双符号流派和普通打法差别不大（自己的符号只有 21–30%）。',
    '最终验收 4200 局：五种流派 86–87 层（98.9%）；均衡型中位 87 层（p10–p90 80–94）；抵达 100 层 0.5%；熟练型死因 断电 43.6% / 躁动 55.5% / 炸弹 0.9%；新手 32 层；真人型 76 层；均衡型上车率全部在 16–64%。躁动来源第一是红线（29.9%），这是站位能控制的部分。',
    '链接现在的存在感（每种 150 局）：真人型每层 4.6 条绿线、只有 4% 的楼层没有；均衡型 3.0 条、19%。离开 70 层商店时剩余金币：真人型 29（v9.22 是 81），均衡型 77（64）。',
    '组合数：6 个座位 × 43 种人物（加空座）约 72.6 亿种坐法；只看符号，每个座位 14 种状态（空、无符号、12 种符号组合），共 7,529,536 种符号布局，产生 6,593 种不同的链接结果、33,598 种“哪些符号几级 + 几条红线”的组合。',
    '调人物的过程：×0.6 后有 4–5 位暗黑版上车率跌破 15%（监工、狂徒、劫匪、疯炸客……），暗黑版改为 v9.22 的 80%；之后劫匪、召魂人、神秘人在边缘，劫匪 14、召魂人 6、神秘人身份车费 ×0.8；幽灵两个符号都省电、自己又不耗电，上车率 67.6%，车费降到 1 后 64%。',
    '浏览器试玩（中文窄屏、英文手机）：卡片和座位的符号、连线上的符号、“这一层的链接”面板、人物详情的符号栏、躁动说明都看过；英文模式从 1 层自动跑到 66 层，界面里没有中文。试玩中把 ⚖️ 换成 📋（灰色的天平在深色座位上看不清，🚦 缩小后是一条细线）；把座位上的符号放大；人物详情里重复的符号说明删掉。',
    'verify：verify-conflicts 改写成符号规则的测试（每人两个不相反的符号、每个符号至少 4 位白天乘客、抵消、单次生效、形状等级、六种效果、省电上限、契约和红绳、复制人、神秘人、百变人）；其他测试里写死的旧车费改成按数据计算。全部通过。',
  ],
  watch: [
    '真人型机器人仍到 76 层，离“普通玩家 60 层左右”还远。它现在很会排座（每层 4.6 条绿线），真实玩家可能没这么熟练；需要真人试玩确认。',
    '“不宽裕”两项验收仍不通过（62.4%，离店中位 26 币），来自熟练型机器人 20–60 层的富余。',
    '江湖和幽冥更难搭（流派实验里只有 37–38% 的楼层生效），暗黑版的上车率贴着 15–20%。',
    '符号用表情显示，不同系统的表情样式不同；卡片上的符号在手机上是 22px。',
  ],
};

export const V10_EN: ChangelogEntry = {
  version: '10.0.0', date: '2026-09-25', title: 'Symbol links: green and red links come from symbols, readable at a glance, with far more combinations',
  summary: 'Green and red links used to come from a hand-written list: each rider liked one or two specific riders and avoided up to two, and you had to memorise it. On 78% of the human-like bot’s floors there was not a single green link; links barely mattered. v10 replaces the list with symbols. Every rider carries two symbols; neighbours sharing a symbol get a green link, neighbours with opposite symbols a red one, and each symbol’s green link has its own effect. Rider abilities (the Officer holding a Thief, the Lovers’ pairing, the Nurse, the Coach…) are unchanged. The rules and numbers were found step by step in simulation; every step is listed below.',
  changes: [
    'Six symbols in three opposite pairs: 🎉 Lively↔🤫 Quiet, 📋 Order↔🎲 Street, 🏠 Hearth↔👻 Spirit. Every rider carries two (never an opposite pair), shown beside the name on cards and seats with the rule in the tooltip. Dark riders are mostly Lively, Street and Spirit, so they clash easily with daytime riders.',
    'Green and red links: neighbours who share a symbol = green link; neighbours with opposite symbols = red link. A pair’s matches and clashes cancel one for one: one match and one clash draw no line.',
    'Each symbol with at least one green link in the cabin works once a floor, all effects per floor:',
    '• 🎉: +2 coins.',
    '• 🎲: +3 coins, but +1 agitation.',
    '• 📋 and 🏠: −1 agitation each.',
    '• 🤫 and 👻: 1 power saved each (never more than the riders use).',
    'Shapes raise a symbol’s level: a row of one symbol adds 1, a 2×2 square 2, a full cabin 4.',
    'Red links are one kind only: +1 agitation per red link per floor. Red links that cost power or coins, doubled power and gamble links are gone.',
    'Cards no longer list named partners and opponents; only ability partners remain (e.g. Officer–Thief). The rider sheet has a new “Symbols” block with each symbol’s green-link effect and its opposite.',
    'New “Links this floor” panel: the active symbols, their levels and effects, and the red-link count. Link lines show the shared symbols, and red ones show 🔥+1. The manual has a new “Symbols and links” section, and the agitation and neighbour notes were rewritten.',
    'Fares:',
    '• Daytime riders ×0.6, since links became the main income.',
    '• Dark riders 80% of v9.22 (the Robber keeps 14, the Summoner 6).',
    '• Ghost 1; the Mystery’s four identities 6 / 16 / 20 / 6.',
    'Abilities and keepsakes:',
    '• The Cooperation Pact and the Red String now give “🎉🎲 +2 coins per green-link level per floor” (Pact level 2: +3).',
    '• Insulation keeps only its conflict tip: +1 coin per red link per floor, at most 3.',
    'Offers: the partner dealt with an anchor card always really links with him (an ability partner, or a symbol relation that does not cancel). Riders who share a symbol with him are dealt too. A tense packet deals someone with an opposite symbol.',
  ],
  experiments: [
    'Before the change (100 runs per bot): the human-like bot averaged 0.26 green links a floor with none on 78% of floors; the balanced bot 0.75 and 53%.',
    'The rules were settled step by step (150 runs × 3–4 bots each):',
    '• Step 1, every green link +1 coin a floor and red links +1 agitation. The human-like bot broke down by 15F: a random pair of neighbours has a 58% chance of an opposite symbol. The skilled bot left the 70F shop with 317 coins.',
    '• Step 2, “matches minus opposites”. The red chance fell to 42% and the human-like bot reached 63–68F, but money was still far too plentiful (617 coins).',
    '• Step 3, each symbol’s green link paying in its own resource. Money no longer grew from links alone, but the novice went from 34F to 68F: per-link rewards stacked up and made the game easier for everyone.',
    '• Step 4, “a symbol with any green link works once, shapes add levels”. The novice fell back to 59F and money came down. Fares ×0.6 then gave novice 29–32F and skilled 87F.',
    'Red links at +2 agitation behaved almost the same as +1, so +1 stays (simpler).',
    'Single-symbol styles, 100 runs each, favouring only riders with that symbol:',
    '• All six end at 87–88F.',
    '• In each style its own symbol is the one most often active: Lively 64%, Quiet 65%, Hearth 63%, Order 53%, Street 38%, Spirit 37%.',
    'Eighteen symbol styles (6 single-symbol, 12 two-symbol; 60 runs each, final numbers):',
    '• All end at 86–88F.',
    '• The single-symbol styles clearly differ: their own symbol is the most active one (Lively 64%, Quiet 66%, Hearth 62%, Order 58%).',
    '• Two-symbol styles with Street or Spirit barely differ from ordinary play (their own symbols active only 21–30% of floors).',
    'Final acceptance, 4,200 runs:',
    '• Five styles at 86–87F (98.9%).',
    '• Balanced median 87F (p10–p90 80–94); 100F reached in 0.5% of runs.',
    '• Skilled endings: 43.6% power, 55.5% agitation, 0.9% bomb.',
    '• Novice 32F, human-like 76F.',
    '• Every balanced boarding rate is within 16–64%.',
    '• Red links are the largest agitation source (29.9%), the part a player controls by seating.',
    'How much links matter now, 150 runs per bot:',
    '• Human-like: 4.6 green links a floor, with none on only 4% of floors.',
    '• Balanced: 3.0 a floor, none on 19%.',
    '• Coins left after the 70F shop: human-like 29 (v9.22: 81), balanced 77 (v9.22: 64).',
    'Combinations:',
    '• 6 seats × 43 rider kinds (plus empty) give about 7.26 billion seatings.',
    '• By symbols alone, each seat has 14 states (empty, no symbol, or one of 12 symbol pairs): 7,529,536 symbol layouts.',
    '• These produce 6,593 distinct link results and 33,598 distinct “which symbols at which level + how many red links” patterns.',
    'Rider tuning:',
    '• After ×0.6, four or five dark riders dropped under 15% boarding (Taskmaster, Brawler, Robber, Mad Bomber…). Dark fares went to 80% of v9.22.',
    '• The Robber, Summoner and Mystery then sat at the edge: Robber 14, Summoner 6, Mystery identity fares ×0.8.',
    '• The Ghost, whose two symbols both save power and who uses none himself, was at 67.6%; fare 1 brings him to 64%.',
    'Browser playtest (Chinese on a narrow window, English on a phone):',
    '• Checked: symbols on cards and seats, symbols on link lines, the “Links this floor” panel, the sheet’s Symbols block and the agitation notes.',
    '• An English autopilot run from 1F to 66F showed no Chinese in the interface.',
    '• Fixed along the way: ⚖️ became 📋 (the grey scales vanished on dark seats, and 🚦 shrank to a thin bar); seat symbols were enlarged; the repeated symbol lines on the rider sheet were removed.',
    'verify: verify-conflicts is rewritten as the symbol rulebook. It tests:',
    '• two non-opposite symbols per rider, and each symbol on at least four day riders;',
    '• canceling, once-per-symbol activation and shape levels;',
    '• the six effects, the power cap, the Pact and the Red String;',
    '• the Mimic, the Mystery and the Shifter.',
    'Old hard-coded fares in other tests are now computed from the data. Everything passes.',
  ],
  watch: [
    'The human-like bot still reaches 76F, far from “a normal player ends around 60F”. It now seats riders very well (4.6 green links a floor), and real players may not; this needs human playtests.',
    'Both “not affluent” checks still fail (62.4%; median 26 coins left after a shop), from the skilled bot’s spare coins at 20–60F.',
    'Street and Spirit are harder to build around (active on only 37–38% of floors in the style test); dark riders’ boarding sits at 15–20%.',
    'Symbols are emoji, which look different on each system; on phones the card symbols are 22px.',
  ],
};

export const V101_ZH: ChangelogEntry = {
  version: '10.1.0', date: '2026-09-25', title: '自己画的符号图标，江湖和幽冥也能搭',
  summary: '表情符号太幼稚，换成自己画的线稿图标，和电梯的装饰风格一致。同时修了两个不好搭的符号：专门去凑江湖和幽冥，也只有 36–40% 的楼层能连上，别的符号有 56–66%。',
  changes: [
    '六个符号图标都重画成金色线稿风格，每个符号一种颜色：热闹是放射的星芒，安静是闭着的眼睛，秩序是装饰艺术风的立柱，江湖是假面，人间是亮着窗的小屋，幽冥是一弯新月。卡片、座位、连线、“这一层的链接”面板都用新图标；文字里一律写符号名称，不再夹表情。',
    '说明书“符号与链接”一节开头加了六个图标的图例（图标、名称、效果），下面的正文不再重复列效果。',
    '江湖：绿线从“+3 币、+1 躁动”改为“+2 币”。带江湖的乘客（小偷、醉汉、炸弹客……）本身就有风险，符号不必再扣躁动。',
    '快递员和维修工的符号从“江湖·人间”改为“江湖·幽冥”。幽冥原来是白天最少见的符号，它的反面人间又在最常见的乘客身上。',
    '监工车费 8→9。',
  ],
  experiments: [
    '问题：专门偏爱某个符号的机器人，自己的符号生效的楼层比例：热闹 64%、安静 66%、人间 62%、秩序 58%，江湖只有 36%，幽冥 40%。',
    '江湖（每种 60 局 × 6 种单符号流派 + 100 局 × 4 种机器人）：去掉 +1 躁动后 36%→52%；改成“+4 币、+1 躁动”仍只有 37%（机器人把 1 点躁动算作约 3 币，净收益几乎为零）。',
    '幽冥：改效果都没用。省电不设上限 42%，深渊发作 −10% 42%，两者都加 43%；发作 −10% 还让合作型到 100 层的比例升到 7–9%。问题出在供给，不在效果。',
    '试过把儿童改成“热闹·幽冥”（幽冥 44–45%），但护士（人间·秩序）要照顾儿童，人间和幽冥相反，这对故事搭档会变成红线，放弃。改成快递员和维修工（没有依赖人间的能力搭档）：六个符号都到 52–66%（江湖 56%、幽冥 56%）。',
    '江湖 +3 币时离开 70 层商店的钱：真人型 102、均衡型 124、合作型 128；+2 币时 87、87、107（v9.22 是 81），江湖生效率 54% 几乎不变，所以取 +2。',
    '最终数值下的单符号流派：热闹 60%、安静 68%、秩序 56%、江湖 54%、人间 52%、幽冥 55%，都在 87–89 层；新手 31 层，真人型 81 层，均衡型 88 层，到 100 层 0–1%。',
    '最终验收 4200 局：五种流派 87–88 层（98.9%）；均衡型中位 88 层（p10–p90 80–95）；抵达 100 层 0.8%；熟练型死因 断电 47.0% / 躁动 51.9% / 炸弹 1.0%；新手 31 层；真人型 81 层。上车率只有监工 14.7% 越界，车费 8→9 后 300 局复查 19.1%，其余都在 15–63%。“不宽裕”：68.0%、离店中位 34 币。',
    '浏览器检查（中文窄屏、英文手机）：六个图标在卡片、座位、连线和面板上都清楚；一个四人“安静方块”在面板上显示为“安静 · 方块 ×3，省 3 电”；说明书图例正常。verify 全部通过。',
  ],
  watch: [
    '钱比 v10.0 多（70 层离店从 29/77 回到 87/87），“不宽裕”两项验收仍不通过。',
    '真人型机器人到 79–81 层，普通玩家 60 层的目标还没解决。',
    '形状（一排、方块、满车）只在面板里写出来，车厢里还没有高亮。',
  ],
};

export const V101_EN: ChangelogEntry = {
  version: '10.1.0', date: '2026-09-25', title: 'Hand-drawn symbol icons, and Street and Spirit worth building around',
  summary: 'The emoji looked childish, so the symbols are now hand-drawn line icons in the cabin’s style. This release also fixes the two symbols that were hard to build around: a bot favouring Street or Spirit got its own symbol active on only 36–40% of floors, against 56–66% for the others.',
  changes: [
    'All six symbol icons are redrawn as gold line art, one colour per symbol:',
    '• Lively: a starburst. Quiet: a closed eye. Order: an Art Deco column.',
    '• Street: a masquerade mask. Hearth: a house with a lit window. Spirit: a crescent moon.',
    'Cards, seats, link lines and the “Links this floor” panel use the new icons; text always names the symbol instead of showing an emoji.',
    'The manual’s “Symbols and links” section opens with a legend of the six icons (icon, name, effect), and the text below no longer repeats the effects.',
    'Street: its green link now gives +2 coins, instead of +3 coins and +1 agitation. Street riders (Thief, Drunk, Bomb Carrier…) already carry their own risk, so the symbol no longer adds agitation.',
    'The Courier and the Mechanic are now Street·Spirit instead of Street·Hearth. Spirit was the scarcest day symbol, and its opposite, Hearth, sat on the most common riders.',
    'Taskmaster fare 8→9.',
  ],
  experiments: [
    'The problem: a bot favouring one symbol got its own symbol active on Lively 64%, Quiet 66%, Hearth 62% and Order 58% of floors, but Street only 36% and Spirit 40%.',
    'Street (60 runs × six single-symbol styles, 100 runs × four bots):',
    '• Without the +1 agitation it went from 36% to 52%.',
    '• “+4 coins, +1 agitation” stayed at 37%: bots price one agitation at about 3 coins, so the net was close to nothing.',
    'Spirit: changing its effect did not help.',
    '• Uncapped power saving: 42%. Abyss outbursts −10%: 42%. Both: 43%.',
    '• The outburst cut also raised the cooperation bot’s 100F rate to 7–9%.',
    '• The problem was supply, not effect.',
    'Moving Spirit onto riders:',
    '• Making the Child Lively·Spirit (44–45%) was rejected: the Nurse (Hearth·Order) cares for the Child, and Hearth opposes Spirit, so the story pair would become a red link.',
    '• The Courier and the Mechanic have no Hearth-based ability partners. With them moved, all six symbols reach 52–66% (Street 56%, Spirit 56%).',
    'Street coins, measured as coins left after the 70F shop (human-like / balanced / cooperation):',
    '• At +3: 102 / 124 / 128.',
    '• At +2: 87 / 87 / 107 (v9.22: 81). Street activation stays 54%, so +2 it is.',
    'Single-symbol styles at the final values:',
    '• Own symbol active: Lively 60%, Quiet 68%, Order 56%, Street 54%, Hearth 52%, Spirit 55%; all end at 87–89F.',
    '• Novice 31F, human-like 81F, balanced 88F; 100F reached in 0–1% of runs.',
    'Final acceptance, 4,200 runs:',
    '• Five styles at 87–88F (98.9%); balanced median 88F (p10–p90 80–95); 100F reached in 0.8% of runs.',
    '• Skilled endings: 47.0% power, 51.9% agitation, 1.0% bomb. Novice 31F, human-like 81F.',
    '• Only the Taskmaster fell outside the boarding band (14.7%). A 300-run recheck after his fare went 8→9 gives 19.1%; everyone else is within 15–63%.',
    '• “Not affluent”: 68.0%, with a median of 34 coins left after a shop.',
    'Browser check (Chinese on a narrow window, English on a phone):',
    '• All six icons are clear on cards, seats, link lines and the panel.',
    '• A four-rider Quiet square shows as “Quiet · square ×3, −3 power”.',
    '• The manual legend renders.',
    'verify passes.',
  ],
  watch: [
    'There is more money than in v10.0: coins left after the 70F shop rose from 29 / 77 to 87 / 87 (human-like / balanced). Both “not affluent” checks still fail.',
    'The human-like bot reaches 79–81F; the 60F target for normal players is still open.',
    'Shapes (row, square, full cabin) are named in the panel but not yet highlighted in the cabin.',
  ],
};

export const V1011_ZH: ChangelogEntry = {
  version: '10.1.1', date: '2026-09-25', title: '卡片不再显示“送达 净 ±N 金币”',
  summary: '车费降了四成以后，很多乘客单独坐时卡上显示“净 −2、−3”，看起来像“别带他”。其实他们的价值在链接里。卡片上的净收益估算和“配某人 +N”两个标签都去掉了。',
  changes: [
    '候客卡和已上车的卡都不再显示“送达 净 ±N 金币”和“配某人 +N”的虚线标签。卡片只留车费、耗电、躁动三个数字和一句能力说明，链接的收益看“这一层的链接”面板。',
    '只隐藏负数会让“没有标签”本身变成“亏钱”的意思，所以正负都去掉。',
    '两条提示改写，不再引用被删掉的标签：“X 单看不划算，和 Y 挨着坐就赚：一起带上。”“空着的座位也在耗运转电：多带几位，让相同符号的人挨着坐，常常能赚回来。”',
  ],
  experiments: [
    '只改界面，规则和数值不变，沿用 v10.1.0 的验收（4200 局：熟练型 断电 47.0% / 躁动 51.9% / 炸弹 1.0%，抵达 100 层 0.8%）。净收益的计算还在，模拟器里的真人型机器人和测试仍在用。verify 全部通过；浏览器检查了中英文卡片。',
  ],
  watch: [
    '没有净收益标签后，新玩家要靠三个数字和链接面板自己判断值不值得带，需要真人试玩看是否更难上手。',
  ],
};

export const V1011_EN: ChangelogEntry = {
  version: '10.1.1', date: '2026-09-25', title: 'Cards no longer show “On arrival ±N coins”',
  summary: 'After fares dropped by 40%, many riders showed “−2” or “−3” on their own, which read as “don’t board him”, while their value was really in the links. The net-value estimate and the “w/ someone +N” tag are gone from cards.',
  changes: [
    'Waiting and seated cards no longer show “On arrival ±N coins” or the dashed “w/ someone +N” tag. A card keeps its fare, power and agitation numbers and one ability line; what links earn is in the “Links this floor” panel.',
    'Hiding only negative values would make “no tag” mean “loses money”, so both are gone.',
    'Two hints no longer quote the removed tags:',
    '• “X does little on its own but earns beside Y: take them together.”',
    '• “Empty seats still cost motor power: take a few more riders and seat those who share a symbol together; it often pays back.”',
  ],
  experiments: [
    'Interface only; rules and numbers unchanged, so the v10.1.0 acceptance stands (4,200 runs: skilled 47.0% power / 51.9% agitation / 1.0% bomb; 100F reached in 0.8% of runs).',
    'The net-value calculation remains; the human-like simulation bot and the tests still use it.',
    'verify passes; cards were checked in the browser in Chinese and English.',
  ],
  watch: [
    'Without the net tag, new players judge a rider from the three numbers and the links panel; human playtests should show whether that is harder to learn.',
  ],
};
