import type {ChangelogEntry} from './changelog';
export const V836_ZH:ChangelogEntry={version:'8.36',date:'2026-09-06',title:'多一位短途候客',summary:'31层起，每批一位候客按该人物正常最短旅程出现；原升级价格与人物组合保持不变。',
changes:['31层起，每批轮换一位候客，行程为该人物正常最短行程，快速升级随后生效；其余两位照常随机。人物、风险和随机数消耗不变，不根据当前资源救场。','保留公开v8.35固定价格：默契30、扩容35、舒缓35、礼宾40、稳压45、快速45、小费盒30、并联30、共乘40、计价器25。撤回未公开实验降价，不是公开版本涨价。每店一项、已选不再出现不变。','运转耗电、票价、躁动、游客/教练组合、坏人暂存与充电价格不变；保留其余正常长途候客，不统一缩短支持人物。'],
experiments:['累计336次合成执行，含重复开发对照，不是336个独立种子或人类游戏。每次执行保留逐步哈希回放。经营型策略只读公开信息，五层四样本推演，保留危险乘客应急请离费用。','最新独立对照每组规划/经营/少接人各8局：升级1.75→1.875、2→2.25；共同30–59层拒客52/136→47/136、64/146→58/146；共同最长拒客均值3→2.25、2.875→2.625。拒客不等于证明无解。','最新主动策略超过60层4/16→3/16，候选最高65；少接人8局完全不变。规划中位57.5→44，经营50→54，非统一变容易，也非人类成功概率。','拒绝最短旅程叠加降价：此前16次主动策略中4次超过100层。早期候选静音实玩100层仍存活、378金币；截尾不是通关。当前修订等待完整静音实玩验收，尚未公开。'],
watch:['观察有意义的选择、投资与长途人物价值。有限测试不能证明所有玩法等强。']};
export const V836_EN:ChangelogEntry={version:'8.36',date:'2026-09-06',title:'One local passenger',summary:'From31, one offer uses its role’s normal shortest trip; public upgrade prices and combinations stay intact.',
changes:['From31, one rotating offer uses its role minimum trip, then Express applies; other offers roll normally. Roles, risks and RNG consumption unchanged. No resource-adaptive rescue.','Retain public v8.35 fixed prices: battery30, capacity35, calm35, concierge40, reinforced45, express45, tipjar30, relay30, crowd40, meter25. Withdraw unpublished discounts, not a public price rise. Purchase limits remain.','Motor, fares, agitation, Tourist/Coach combinations, criminal banking and charging prices unchanged. Normal long trips remain; no blanket support shortening.'],
experiments:['336 synthetic executions including repeated controls, not336 independent seeds; step-hash replay retained. Public-only operator uses five-floor/four-sample planning and emergency dismissal funds.','Latest fresh comparison:8 per planner/operator/minimalist per arm. Upgrades1.75→1.875 and2→2.25; common30–59 refusals52/136→47/136 and64/146→58/146; mean longest3→2.25 and2.875→2.625. Refusals are not proofs of no solution.','Active-policy above60:4/16→3/16, candidate maximum65. All8 minimalist outcomes unchanged. Medians57.5→44 and50→54; not uniformly easier or a human success rate.','Rejected minimum trips plus discounts:4/16 earlier active samples exceeded100. Earlier muted browser candidate censored alive at100 with378 coins, not a win. Current revision awaits full muted browser acceptance and is not public.'],
watch:['Watch meaningful choices, viable investments and long-trip roles. Finite tests do not prove universal strategy parity.']};
