import type {ChangelogEntry} from './changelog';
export const V836_ZH:ChangelogEntry={version:'8.36',date:'2026-09-06',title:'为下一笔投资留一点空间',summary:'适度降低永久能力价格，后段每批保留一位较短行程乘客；不降低运转压力，不削弱人物组合。',
changes:['固定价格调整：扩容35→30、礼宾40→35、稳压45→40、快速45→35、小费盒30→25、并联30→25、共乘40→30、计价器25→20；默契30、舒缓35不变。每店一项、每局不重复不变。','31层起，每批轮换一位候客，其行程至多为该人物正常最短行程+1层；其余两位照常随机，快速升级随后生效。不改变人物种类、风险或随机数消耗，不根据剩余金币或电量救场。','运转耗电、人物正常行程范围、票价、躁动、游客与教练倍率、坏人暂存、充电价格均不变。'],
experiments:['静音浏览器从1层连续操作至100层仍存活：9/70电、378金币、4项升级，98层首次用应急电池。125次接客、18种人物；31–59层有空位却全拒3/26层。约29.5分钟含工具操作，不是人类时长。100层截尾不是死亡或通关，候选暂不发布；实验策略未覆盖这条长期续航循环。','160次合成策略执行（含8次重复基线），不是160个独立种子或人类游戏。分别测试运转减耗、大幅降价、适度降价、支持人物缩短行程与短行程候客。保留逐步哈希回放。','最终新种子对照：每组规划型、机会型、少接人各8局。规划型每局升级0.75→1，机会型1.25→1.875；平均最长连续拒客5.125→4.75、4→3.375。少接人8局结果完全不变。','最终对照中两种主动策略超过60层由1/16变为0/16；规划型中位层数47.5→46.5，机会型39.5→44.5。改善不均匀，不宣称彻底平衡；开发样本仍出现100层截尾。'],
watch:['观察真实玩家后段是否仍频繁空过、投资是否有感、短行程是否挤压长途计价器；保留强组合与困难反例。']};
export const V836_EN:ChangelogEntry={version:'8.36',date:'2026-09-06',title:'Room for the next investment',summary:'Moderately cheaper permanent upgrades and one shorter-trip offer in later packets; motor pressure and character combinations remain.',
changes:['Fixed prices: capacity35→30, concierge40→35, reinforced45→40, express45→35, tipjar30→25, relay30→25, crowd40→30, meter25→20; battery30 and calm35 unchanged. One purchase per shop and no owned repeats remain.','From floor31, one rotating offer has its trip capped at that role’s normal minimum+1; the other two roll normally. Express applies afterward. No changed roles, risks or RNG consumption, and no resource-adaptive rescue.','Motor costs, normal role ranges, fares, agitation, Tourist/Coach multipliers, criminal banking and charging prices stay unchanged.'],
experiments:['One continuous muted browser sample censored alive at100:9/70 power,378 coins,4 upgrades, first reserve use at98.125 boardings across18 roles;3/26 space-available floors31–59 skipped. About29.5 minutes including automation overhead, not human timing. Not a death or completed game; hold publication pending stronger long-run policy coverage.','160 synthetic executions including8 repeated controls, not160 independent seeds or human games. Test motor relief, large/moderate discounts, shorter supports and a short-trip slot with step-hash replay.','Final fresh-seed comparison:8 games per planner, opportunist and minimalist per arm. Upgrades/game0.75→1 and1.25→1.875; mean longest refusal streak5.125→4.75 and4→3.375. All8 minimalist outcomes unchanged.','Above60 among active policies1/16→0/16. Median floors47.5→46.5 for planner,39.5→44.5 for opportunist. Uneven gains, not balance certification; development samples still included a100-floor censor.'],
watch:['Watch real late refusals, meaningful investment and pressure on long-trip builds; retain powerful combinations and difficult counterexamples.']};
