import type {ChangelogEntry} from './changelog';
export const V835_ZH:ChangelogEntry={version:'8.35',date:'2026-09-06',title:'把决定讲清楚，把组合留下来',summary:'仪表内反馈、充电滑杆和完整人物关系；保留游客叠加，日常躁动不再能用金币调档。',
changes:['桌面三张候客并排展示，完整列出绿线与红线对象及效果，不再显示“等几种”，不再按尚未解锁角色隐藏关系。出场解锁节奏不变。','左侧仪表取消滚动和外侧变化数字；实际结算保留数字动画、卡框反馈与独立音效，遵守静音设置。','充电改为一个滑杆与确认按钮，默认目标50电（当前更高时不放电）；2币/电不变，显示支付金额与支付后余额，不足时提示调低目标。','取消日常按点舒缓。仅已失控抵达商店时可按8币/点抢救至上限以下1点；保留原有抢救价格、升级舒缓和人物控场。','游客基价8、每位邻座+2、中躁动+3、邻名人额外协作1（升级后3）全部保留。说明本人到站收款、同层互算、先离开不再算；教练只放大基价。'],
experiments:['2166种游客邻座/躁动/协作升级结算检查，1053种失控抢救与金币边界检查；12种坏人到站预览检查，补上最后一层暂存，不改收益。','28局合成策略抽样：2局超过60层；不是人类胜率或流派平衡认证。只顾收入的策略仍会有钱无电，续航规划优于简单堆人。','静音浏览器完整实玩1局：67层电量耗尽，最后6电需7电，剩7金币，仅安装1项能力。高躁动护士/醉汉、游客同层到站、坏人暂存和幽灵节能均有价值；后段频繁拒客、投资机会不足仍需研究。修复商店旧舒缓说明与初见标记挤出操作文字。'],
watch:['继续观察满载收益与续航的取舍、去掉日常舒缓后中高躁动的可控性，以及较小窗口完整规则的可读性。']};
export const V835_EN:ChangelogEntry={version:'8.35',date:'2026-09-06',title:'Clear decisions, intact combinations',summary:'In-instrument feedback, a charging slider and complete relationships; Tourist synergies stay, everyday agitation cannot be bought down.',
changes:['Three desktop offers sit side by side with every green/red target and effect listed. No hidden “more types” or locked-role relationship omissions; encounter unlock pacing is unchanged.','The status rail no longer scrolls or projects delta badges outside its cards. Actual changes retain number animation, card feedback and resource sounds, respecting mute preferences.','One charging slider and confirmation button; default target50, or current power if higher. Price remains2 coins/power. Shows cost, remaining coins and a lower-target prompt when unaffordable.','Remove routine soothing. Critical agitation at a shop can still be rescued for8 coins/point to1 below the cap, preserving emergency cost and rider/upgrade control.','Tourist base8,2 per neighbor,3 at medium agitation and1 extra per Celebrity bond (3 upgraded) all remain. Clarify who earns, same-floor counting and departed neighbors; Coaches multiply base fare only.'],
experiments:['2166 Tourist adjacency/agitation/bond-upgrade checks,1053 emergency/coin boundary checks and12 next-arrival bank quotes. Quotes include the final guaranteed bank step; payouts are unchanged.','28 synthetic policy samples:2 exceeded floor60. Not human win rates or strategy-balance certification. Income-focused policies can die with coins left; power planning still matters.','One complete muted browser playthrough ended at67 from power depletion:6 power versus7 needed,7 coins left and only1 upgrade installed. High-agitation Nurse/Drunk play, aligned Tourists, criminal banking and controlled Ghosts were useful. Late refusals and scarce investment opportunities remain open. Fix stale shop soothing text and debut badges displacing action text.'],
watch:['Watch full-cabin income versus endurance, medium/high control without routine soothing, and complete-rule readability on smaller windows.']};
