import type { PassengerKind } from './game-data';

/** One short vignette per rider, unlocked the first time they are delivered. */
export const STORIES: Record<PassengerKind, [string, string]> = {
  commuter: ['他每天坐同一班电梯，站在同一个角落。今晚他第一次发现，这栋楼没有他要去的那一层——但他还是按了按钮。', 'He takes the same lift every night and stands in the same corner. Tonight he noticed the building has no floor for where he is going—and pressed the button anyway.'],
  tourist: ['相机里全是走廊。她说每一层的地毯花纹都不一样，要全部拍下来，回去给朋友看“真正的夜晚”。', 'Her camera is full of corridors. Every floor has a different carpet, she says; she will photograph them all and show her friends “the real night”.'],
  courier: ['包裹上的收件人写着“顶层”。他跑了很多年，从没找到顶层，但包裹一直准时送到了。', 'The label says “Top Floor”. He has run this route for years and never found it, yet every parcel arrives on time.'],
  mechanic: ['她听得出电机的每一种咳嗽。“这台老家伙还能撑，”她拍拍墙壁，“只要有人肯听它说话。”', 'She can tell every cough of the motor. “The old thing will hold,” she says, patting the wall, “as long as someone listens to it.”'],
  lover: ['两个人约好在某一层见面，却谁都记不清是哪一层。所以他们一直坐着电梯，一层一层地找。', 'They agreed to meet on a floor neither can remember. So they keep riding, floor by floor, looking.'],
  musician: ['他把电梯的嗡鸣当作定音。据说在他演奏过的楼层，灯会亮得久一点。', 'He tunes to the hum of the cables. On the floors where he has played, they say, the lights stay on a little longer.'],
  thief: ['他从不偷钱，只偷别人落下的时间。“反正你们也用不完，”他说，然后把怀表塞进袖子。', 'He never takes money—only the time people leave lying around. “You would not have used it,” he says, sliding a watch up his sleeve.'],
  cop: ['巡逻了二十年，她最擅长的是站在正确的位置。小偷一看见她，就会自己把手放回口袋。', 'Twenty years on patrol taught her one thing: where to stand. Thieves see her and put their hands back in their own pockets.'],
  lawyer: ['他的公文包里有这栋楼每一条规定的副本，包括那些没人写下来的。', 'His briefcase holds a copy of every rule in the building—including the ones nobody wrote down.'],
  drunk: ['他说自己只是在找回家的路。每次门开，他都笑着说“就是这里”，然后又不下去。', 'He says he is only looking for the way home. Each time the doors open he laughs, “This is it,” and stays put.'],
  nurse: ['夜班做久了，她能从脚步声里听出谁快撑不住。她会先站到那个人旁边，什么都不说。', 'After years of nights she can hear, from footsteps alone, who is about to break. She stands beside them first, and says nothing.'],
  child: ['他数电梯按钮数到一百就不会了。“那后面的楼层，”他认真地问，“是不是还没有人住？”', 'He can count the buttons up to a hundred, then stops. “The floors after that,” he asks very seriously, “does nobody live there yet?”'],
  ghost: ['她在这栋楼里等了很久，久到忘了在等谁。有人陪着的时候，她会安静一点。', 'She has waited in this building so long she has forgotten who for. When someone keeps her company, she is quieter.'],
  exorcist: ['他不驱赶鬼魂，只是提醒它们：该下车了。大多数都会点点头，在正确的楼层离开。', 'He does not banish ghosts; he reminds them it is their stop. Most nod, and leave on the right floor.'],
  coach: ['她对每个人都说“你可以的”，连对电梯也说。奇怪的是，它好像真的跑得更稳了。', 'She tells everyone “you have got this”—the lift included. Strangely, it does seem to run steadier.'],
  celebrity: ['他习惯了被围住，却从没习惯被认出来之后的沉默。所以他只想要一个人陪着说话。', 'He is used to crowds, never to the silence after being recognised. So he only wants one person to talk to.'],
  inspector: ['她的笔记本上有一栏叫“安静”。只有连续两层都安静的电梯，才能得到她的印章。', 'Her notebook has a column headed “Quiet”. Only a lift that stays calm two floors running earns her stamp.'],
  bomb: ['箱子里的滴答声不是炸弹，他坚持说，是一颗心。只是这颗心，很怕迟到。', 'The ticking in the case is not a bomb, he insists—it is a heart. A heart that is very afraid of being late.'],
  mystery: ['没人记得他在哪一层上车。到站时他留下的车费每次都不一样，像是按心情付的。', 'Nobody remembers where he got on. The fare he leaves is different every time, as if he pays by mood.'],
  shifter: ['每到一层，她就换一副样子。“我只是还没决定，”她说，“今晚要当谁。”', 'At every floor she wears a different face. “I just have not decided,” she says, “who to be tonight.”'],
  mimic: ['他总是学站在他上方的人。有一次学得太像，连对方都以为自己已经下了车。', 'He always copies whoever stands above him. Once he did it so well the original thought they had already got off.'],
  parcel: ['没人知道箱子里装的是什么。快递员说，只要它准时到，里面是什么都不重要。', 'Nobody knows what is in the box. The courier says that as long as it arrives on time, what is inside does not matter.'],
  operator: ['老周开了四十年电梯，退休那天没人来送他。于是他每晚回来坐第一班，从一楼坐到十楼，替新人把电机捂热。', 'Zhou ran this lift for forty years; nobody came to see him off when he retired. So he rides the first car every night, one to ten, warming the motor for whoever is new.'],
  matchmaker: ['她口袋里总有一团红线，说是在这栋楼里捡到的。她把线头交给谁，谁就会在某一层遇见另一个人。', 'She always carries a tangle of red thread, found somewhere in the building. Whoever she hands an end to meets someone, on some floor.'],
  don: ['他从不大声说话。整栋楼的坏人见了他都会摘下帽子，然后乖乖把钱存进他的账上。', 'He never raises his voice. Every crook in the building takes off his hat when he boards—and quietly pays into his account.'],
  matron: ['她值了三十年夜班，记得这栋楼每一个呼叫铃的声音。她走过的车厢，总会安静下来。', 'Thirty years of night shifts; she knows the sound of every call bell in the building. Any car she walks through goes quiet.'],
  nightingale: ['夜店层最后一场演出结束后，她还在电梯里唱。她说，歌要唱给还没睡的人听。', 'After the last set in the nightclub she keeps singing in the lift. Songs, she says, are for the people still awake.'],
  medium: ['她能看见这栋楼里所有没下车的人。她不怕他们，只是替他们找一个能坐下的位置。', 'She can see everyone in this building who never got off. She is not afraid of them—she just finds them somewhere to sit.'],
  tycoon: ['这栋楼一半的楼层写着他的名字，他却只肯坐这台旧电梯。“新的太快了，”他说，“来不及想事情。”', 'Half the floors in this building bear his name, yet he will only ride this old lift. “The new ones are too fast,” he says. “No time to think.”'],
  stranger: ['登记簿上，十三号房一直空着。可每天夜里，总有人从那里走进电梯，带着一件别人的东西。', 'In the register, room thirteen has always been empty. Yet every night someone steps into the lift from there, carrying something that belongs to someone else.'],
  nightoperator: ['午夜以后，老周又回来上班了。他熟悉这台电梯的每一声咳嗽，也知道关掉哪盏灯能省下最多的电。只是灯一灭，车厢里的人就开始不安。', 'After midnight, Old Zhou comes back to work. He knows every cough of this lift, and which light to switch off to save the most power. But once the lights go out, the riders grow restless.'],
  severer: ['白天她牵红线，夜里她剪红线。她说，吵架的人最诚实，互相帮忙的人都在演戏。她的剪刀很快，快到你来不及说再见。', 'By day she ties red threads; by night she cuts them. People who quarrel are honest, she says; people who help each other are acting. Her scissors are fast, too fast to say goodbye.'],
  kingpin: ['教父讲规矩，黑老大不讲。他在每一层都收一份，送到了才分你一半。中途让他下车？那份钱就当交学费了。', 'The Don kept rules. The Kingpin keeps none. He collects a share on every floor and gives you your cut only when he arrives. Put him off early and consider the money your tuition.'],
  coldmatron: ['她的查房本换成了镇静剂。被她扎过一针的人都很安静，安静得像一排冷藏柜。冷藏柜是要用电的。', 'Her rounds log has become a case of sedatives. Everyone she treats goes quiet, quiet as a row of refrigerators. And refrigerators need power.'],
  banshee: ['夜莺最后一首歌没有唱完。现在她只唱给要离开的人听。车厢越乱，她唱得越动听，给的钱也越多。', 'The Nightingale never finished her last song. Now she only sings for those about to leave. The wilder the cabin, the sweeter her voice, and the more she pays.'],
  necromancer: ['灵媒以前替亡魂找座位，现在她替自己找随从。车里黑夜里的人越多，她的水晶球就越亮。', 'The Medium used to find seats for the dead. Now she recruits followers. The more night people in the cabin, the brighter her crystal ball.'],
  highroller: ['大亨输掉了半栋楼，只剩下一副骰子。他要赌最后一把：车厢越乱，他押得越多；可要是真闹翻了天，谁也拿不到钱。', 'The Tycoon lost half the building and kept only a pair of dice. One last bet: the wilder the cabin, the more he stakes; let it truly boil over and nobody collects.'],
  otherthirteen: ['镜子里的十三号房也有一位房客。他穿着同样的衣服，笑得却不一样。他带来的不是别人的东西，而是别人的运气。', 'Room thirteen in the mirror has a guest too. Same clothes, a different smile. He doesn’t carry someone else’s things; he carries someone else’s luck.'],
  overtimer: ['午夜之后，他还站在同一个角落。怀表停在十一点五十九分。“再坐一层，”他说，“加班费照算。”他已经很久没回家了。', 'After midnight he still stands in the same corner. His watch stopped at 11:59. “One more floor,” he says, “overtime counts.” He has not been home in a long time.'],
  voyeur: ['她的相机不再拍走廊了。她拍的是乘客——睡着的、哭着的、说谎的。“真正的夜晚，”她说，“都在别人的脸上。”', 'Her camera no longer shoots corridors. She shoots the riders: sleeping, crying, lying. “The real night,” she says, “is on other people’s faces.”'],
  smuggler: ['收件人还是“顶层”，但箱子变黑了，封着红蜡。他不再问里面是什么。“你也别问，”他说，“问了就得分一半。”', 'The label still says “Top Floor”, but the box is black now, sealed in red wax. He no longer asks what is inside. “Don’t you ask either,” he says, “or you’ll want half.”'],
  scrapper: ['她还是听得出电机的每一种咳嗽，只是现在她在算每一根铜线值多少钱。“这台老家伙撑不了多久，”她拍拍墙，“不如先卖了。”', 'She can still hear every cough of the motor, but now she prices each copper wire. “The old thing won’t last,” she pats the wall, “might as well sell it first.”'],
  exlover: ['那张合照撕成了两半，她只留下自己那一半。另一半在电梯里的某个人手里。他们总是坐同一班电梯，总是隔着一个人。', 'The photo is torn in two; she kept her half. The other half is in someone’s hand on this same lift. They always ride together, always with someone between them.'],
  noisemaker: ['他说降 B 调太温柔了。琴弦断了三根，他拉得更响。“安静的人听不见真相，”他咧嘴一笑，“吵起来就听见了。”', 'He says B-flat was too gentle. Three strings snapped and he plays louder. “Quiet people never hear the truth,” he grins. “Make some noise and they do.”'],
  robber: ['他不再偷偷摸摸了。“口袋太小，”他掂了掂棍子，“钱包才够分量。”电梯停下的时候，他总是站在离你最近的地方。', 'He no longer sneaks. “Pockets are too small,” he weighs the cosh. “Wallets are worth the trip.” When the lift stops, he is always the one standing nearest to you.'],
  crookedcop: ['他还是说“都站好”，只是现在后面多了一句：“一人三块。”他的金表很准，准到能算出每一层该收多少。', 'He still says “Everyone stand still”, now with a second line: “Three each.” His gold watch is precise, precise enough to know what every floor is worth.'],
  shyster: ['合同已经履行，但他找到了新条款：只要有人吵架，就有人要赔钱。他的笔在滴红墨水。“我记下了，”他说，“全部记下了。”', 'The contract is fulfilled, but he found a new clause: wherever there is a quarrel, someone pays. His pen drips red. “Noted,” he says. “All of it.”'],
  brawler: ['他不再找错楼层了。他在找人。碎酒瓶在灯下闪了一下，所有人都往后退了半步——只有噪音越来越大的时候，他才会笑。', 'He no longer looks for the wrong floor. He looks for someone. The broken bottle glints and everyone steps back half a pace; he only smiles when the noise gets louder.'],
  pusher: ['“谁不舒服？”她晃了晃药瓶，里面的药片在发光。吃过的人都说好多了。只是等她下车以后，所有人都开始发抖。', '“Who’s not feeling well?” She rattles the bottle; the pills glow. Everyone who takes one feels better. It is only after she leaves that they all start to shake.'],
  creepychild: ['兔子的眼睛是两颗纽扣。他不再问能不能按按钮了，他只是站着，看着你。等电梯里只剩他一个人的时候，他才会笑。', 'The rabbit has button eyes. He no longer asks to press the button; he just stands and watches you. Only when he is alone in the lift does he smile.'],
  wraith: ['它想起来了——想起来的不是自己的名字，而是谁欠了它。黑影一层比一层浓，灯每闪一下，电梯就慢一点。', 'It remembers now, not its own name but who owes it. The shadow thickens floor by floor, and each time the lights flicker the lift slows a little.'],
  summoner: ['他不再赶走它们了。铃声一响，空着的座位上就多了一个冰冷的乘客。“它们也要回家，”他说，“车费照付。”', 'He no longer sends them away. At each ring of his bell a cold passenger fills an empty seat. “They want to go home too,” he says. “They pay their fare.”'],
  taskmaster: ['“打起精神！”变成了“再快一点！”。他手里的秒表从来不停，鞭子也是。跟着他的人都赚得更多，也都更累。', '“Look alive!” has become “Faster!”. His stopwatch never stops, nor does the whip. Everyone beside him earns more, and tires more.'],
  scandal: ['她不再说“别拍照”了。闪光灯越多越好，丑闻越大越红。只是千万别让穿制服的人站到她旁边。', 'She no longer says “No photos.” The more flashbulbs the better; the bigger the scandal, the brighter she shines. Just never let a uniform stand beside her.'],
  grafter: ['他还在盖章，只是章盖在钱上。“合格，”他说，一边把钞票塞进公文包，“你们都合格，只要交一点检查费。”', 'He still stamps things, only now he stamps money. “Passed,” he says, stuffing banknotes into the briefcase. “You all pass, for a small inspection fee.”'],
  madbomber: ['他不再护着箱子，而是抱着一颗缝满针脚的怪炸弹，里面的绿色液体在冒泡。“快，快，快，”他笑着说，“这一次真的会响。”', 'He no longer guards a case; he hugs a stitched-together contraption bubbling with green fluid. “Faster, faster,” he laughs. “This time it really goes off.”'],
};

export const STORIES_KEY = 'elevator-tales-stories-v1';
